services:
  db:
    image: postgres:16
    container_name: charsheet_db
    environment:
      POSTGRES_DB: charsheet
      POSTGRES_USER: charsheet
      POSTGRES_PASSWORD: charsheet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: