# Generated by Django 5.2.11 on 2026-02-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("max_levels", models.IntegerField(default=0)),
                ("points_per_level", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Disadvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("max_levels", models.IntegerField(default=0)),
                ("points_per_level", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_level", models.IntegerField(default=3)),
                ("can_read_and_write", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_st", models.IntegerField(default=0)),
                ("min_con", models.IntegerField(default=0)),
                ("min_dex", models.IntegerField(default=0)),
                ("min_per", models.IntegerField(default=0)),
                ("min_int", models.IntegerField(default=0)),
                ("min_wil", models.IntegerField(default=0)),
                ("min_cha", models.IntegerField(default=0)),
                ("max_st", models.IntegerField(default=0)),
                ("max_con", models.IntegerField(default=0)),
                ("max_dex", models.IntegerField(default=0)),
                ("max_per", models.IntegerField(default=0)),
                ("max_int", models.IntegerField(default=0)),
                ("max_wil", models.IntegerField(default=0)),
                ("max_cha", models.IntegerField(default=0)),
                ("base_movement", models.IntegerField(default=0)),
                ("march_movement", models.IntegerField(default=0)),
                ("sprint_movement", models.IntegerField(default=0)),
                ("swimming_movement", models.IntegerField(default=0)),
                ("size_class", models.IntegerField(default=2)),
                ("skill_bonus", models.JSONField(default=dict)),
                ("special_abilities", models.JSONField(default=dict)),
                ("start_attribute_points", models.IntegerField(default=40)),
                ("start_skill_points", models.IntegerField(default=50)),
                ("start_free_points", models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("level", models.IntegerField(default=0)),
                ("skill_bonus", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "base_attribute",
                    models.CharField(
                        choices=[
                            ("ST", "Strength"),
                            ("KON", "Constitution"),
                            ("GE", "Geschick"),
                            ("WA", "Wahrnehmung"),
                            ("INT", "Intelligenz"),
                            ("WIL", "Willenskraft"),
                            ("CHA", "Charisma"),
                        ],
                        max_length=3,
                    ),
                ),
                ("max_level", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("strength", models.IntegerField()),
                ("constitution", models.IntegerField()),
                ("dexterity", models.IntegerField()),
                ("perception", models.IntegerField()),
                ("intelligence", models.IntegerField()),
                ("willpower", models.IntegerField()),
                ("charisma", models.IntegerField()),
                ("skills", models.JSONField(blank=True, default=dict)),
                ("schools", models.JSONField(blank=True, default=dict)),
                ("advantages", models.JSONField(blank=True, default=dict)),
                ("disadvantages", models.JSONField(blank=True, default=dict)),
                ("experience_points", models.IntegerField(default=0)),
                ("damage_points", models.IntegerField(default=0)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.race",
                    ),
                ),
            ],
        ),
    ]
