# Generated by Django 5.2.11 on 2026-02-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_characterlanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="learned_languages",
            field=models.ManyToManyField(
                through="characters.CharacterLanguage", to="characters.language"
            ),
        ),
    ]
