# Generated by Django 5.2.11 on 2026-02-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_character_learned_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="can_read_and_write",
        ),
    ]
