# Generated by Django 5.2.11 on 2026-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_remove_language_can_read_and_write"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="base_fly_speed",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="race",
            name="can_fly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="race",
            name="march_fly_speed",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="race",
            name="sprint_fly_speed",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="race",
            name="base_movement",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="race",
            name="march_movement",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="race",
            name="sprint_movement",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="race",
            name="swimming_movement",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
