# Generated by Django 5.2.11 on 2026-02-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_race_base_fly_speed_race_can_fly_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_combat_maneuver",
            field=models.BooleanField(default=False, verbose_name="Ist Kampfmanöver"),
        ),
        migrations.AlterField(
            model_name="race",
            name="size_class",
            field=models.IntegerField(default=3),
        ),
    ]
