# Generated by Django 5.2.11 on 2026-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0006_skill_is_combat_maneuver_alter_race_size_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_knowlage_skill",
            field=models.BooleanField(
                default=False, verbose_name="ist Wissensfähigkeit"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="is_combat_maneuver",
            field=models.BooleanField(default=False, verbose_name="ist Kampfmanöver"),
        ),
    ]
