# Generated by Django 5.2.11 on 2026-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0007_skill_is_knowlage_skill_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "rs_bonus",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Natürlicher RS"
                    ),
                ),
                (
                    "sr_bonus",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="SR Bonus"
                    ),
                ),
                (
                    "damage_dice",
                    models.CharField(
                        blank=True,
                        help_text="z.B. 1w10",
                        max_length=20,
                        null=True,
                        verbose_name="Schadenswürfel",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="race",
            name="special_abilities",
        ),
        migrations.AddField(
            model_name="race",
            name="special_abilities",
            field=models.ManyToManyField(blank=True, to="characters.specialability"),
        ),
    ]
