# Generated by Django 5.2.11 on 2026-02-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0008_specialability_remove_race_special_abilities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="skill_bonus",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="specialability",
            name="rs_bonus",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="RS Bonus"
            ),
        ),
    ]
