# Generated by Django 5.2.11 on 2026-02-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0009_alter_race_skill_bonus_alter_specialability_rs_bonus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z.B. Künstlerische Begabung", max_length=100
                    ),
                ),
                (
                    "num_choices",
                    models.IntegerField(
                        default=1, verbose_name="Anzahl der wählbaren Skills"
                    ),
                ),
                ("bonus_value", models.IntegerField(default=2)),
                (
                    "available_skills",
                    models.ManyToManyField(blank=True, to="characters.skill"),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choice_boni",
                        to="characters.race",
                    ),
                ),
            ],
        ),
    ]
