# Generated by Django 5.2.11 on 2026-02-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0010_choicebonus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="is_knowlage_skill",
            new_name="is_knowledge_skill",
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="skill",
            name="base_attribute",
            field=models.CharField(
                choices=[
                    ("ST", "Strength"),
                    ("KON", "Konstitution"),
                    ("GE", "Geschick"),
                    ("WA", "Wahrnehmung"),
                    ("INT", "Intelligenz"),
                    ("WIL", "Willenskraft"),
                    ("CHA", "Charisma"),
                ],
                max_length=3,
            ),
        ),
    ]
