# Generated by Django 5.2.11 on 2026-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
