# Generated by Django 5.2.11 on 2026-03-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0002_skill_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
