# Generated by Django 5.2.11 on 2026-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0003_skillcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillcategory",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
