# Generated by Django 5.2.11 on 2026-03-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0004_alter_skillcategory_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("race", "Race"),
                            ("school", "School"),
                            ("technique", "Technique"),
                            ("spell", "Spell"),
                            ("aspect", "Aspect"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_id", models.PositiveBigIntegerField()),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("skill", "Skill"), ("category", "Category")],
                        max_length=30,
                    ),
                ),
                ("target_slug", models.CharField(max_length=120)),
                ("value", models.SmallIntegerField()),
                (
                    "min_school_level",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="charsheet.schooltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgressionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_level", models.PositiveBigIntegerField(default=1)),
                (
                    "grant_kind",
                    models.CharField(
                        choices=[
                            ("technique_choice", "Technique Choice"),
                            ("spell_choice", "Spell Choice"),
                            ("aspect_access", "Aspect Access"),
                            ("aspect_spell", "Aspect Spell"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(default=1)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "school_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charsheet.schooltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="charsheet.character",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_entries",
                        to="charsheet.school",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "school"), name="uniq_character_school"
                    )
                ],
            },
        ),
    ]
