# Generated by Django 5.2.11 on 2026-03-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0005_modifier_schooltype_school_progressionrule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("level", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="techniques",
                        to="charsheet.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school__name", "level", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "level", "name"),
                        name="uniq_technique_school_level_name",
                    )
                ],
            },
        ),
    ]
