# Generated by Django 5.2.11 on 2026-03-02 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0006_technique"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modifier",
            name="source_id",
        ),
        migrations.RemoveField(
            model_name="modifier",
            name="source_kind",
        ),
        migrations.AddField(
            model_name="modifier",
            name="source_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="source_object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="min_school_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="charsheet_m_source__1e69f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["target_kind", "target_slug"],
                name="charsheet_m_target__96bdf0_idx",
            ),
        ),
    ]
