# Generated by Django 5.2.11 on 2026-03-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0007_remove_modifier_source_id_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifier",
            name="source_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="source_object_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]
