# Generated by Django 5.2.11 on 2026-03-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0008_alter_modifier_source_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="modifier",
            name="charsheet_m_source__1e69f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="modifier",
            name="charsheet_m_target__96bdf0_idx",
        ),
        migrations.AddField(
            model_name="modifier",
            name="cap_mode",
            field=models.CharField(
                choices=[("none", "None"), ("min", "Min"), ("max", "Max")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="cap_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("school_level", "School level"),
                    ("fame_total", "Fame total"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="div",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="modifier",
            name="mode",
            field=models.CharField(
                choices=[("flat", "Flat"), ("scaled", "Scaled")],
                default="flat",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="mul",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="modifier",
            name="round_mode",
            field=models.CharField(
                choices=[("floor", "Floor"), ("ceil", "Ceil")],
                default="floor",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="scale_school",
            field=models.ForeignKey(
                blank=True,
                help_text="Only used if scale_source == school_level",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scale_modifiers",
                to="charsheet.school",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="scale_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("school_level", "School level"),
                    ("fame_total", "Fame total"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("skill", "Skill"),
                    ("category", "Category"),
                    ("stat", "Stat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="value",
            field=models.SmallIntegerField(default=0),
        ),
    ]
