# Generated by Django 5.2.11 on 2026-03-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0009_remove_modifier_charsheet_m_source__1e69f9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="current_damage",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
