# Generated by Django 5.2.11 on 2026-03-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0010_character_current_damage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("armor", "Armor"),
                            ("weapon", "Weapon"),
                            ("misc", "Misc"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("stackable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArmorStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rs_head", models.PositiveIntegerField(default=0)),
                ("rs_torso", models.PositiveIntegerField(default=0)),
                ("rs_arm_left", models.PositiveIntegerField(default=0)),
                ("rs_arm_right", models.PositiveIntegerField(default=0)),
                ("rs_leg_left", models.PositiveIntegerField(default=0)),
                ("rs_leg_right", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="charsheet.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=1)),
                ("equipped", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charsheet.character",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="charsheet.item"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "item"), name="unique_item_per_character"
                    )
                ],
            },
        ),
    ]
