# Generated by Django 5.2.11 on 2026-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0011_item_armorstats_characteritem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
