# Generated by Django 5.2.11 on 2026-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0012_alter_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="armorstats",
            name="rs_total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
