# Generated by Django 5.2.11 on 2026-03-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0013_armorstats_rs_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "trait_type",
                    models.CharField(
                        choices=[
                            ("advantage", "Advantage"),
                            ("disadvantage", "Disadvantage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("max_level", models.PositiveIntegerField(default=1)),
                ("points_per_level", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trait_level", models.PositiveIntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charsheet.character",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charsheet.trait",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trait", "owner"), name="unique_trait_per_character"
                    )
                ],
            },
        ),
    ]
