# Generated by Django 5.2.11 on 2026-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0014_trait_charactertrait"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="charactertrait",
            name="unique_trait_per_character",
        ),
        migrations.AddField(
            model_name="trait",
            name="min_level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="charactertrait",
            constraint=models.UniqueConstraint(
                fields=("owner", "trait"), name="unique_trait_per_character"
            ),
        ),
    ]
