# Generated by Django 5.2.11 on 2026-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0015_remove_charactertrait_unique_trait_per_character_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifier",
            name="cap_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("school_level", "School level"),
                    ("fame_total", "Fame total"),
                    ("trait_level", "Trait Level"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="scale_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("school_level", "School level"),
                    ("fame_total", "Fame total"),
                    ("trait_level", "Trait Level"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
