# Generated by Django 5.2.11 on 2026-03-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0017_damagetype_item_price_weaponstats"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DamageType",
            new_name="DamageSource",
        ),
        migrations.RenameField(
            model_name="weaponstats",
            old_name="damage_type",
            new_name="damage_source",
        ),
    ]
