# Generated by Django 5.2.11 on 2026-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0018_rename_damagetype_damagesource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="age",
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="appearance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="eye_color",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("männlich", "Männlich"), ("weiblich", "Weiblich")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="hair_color",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="height",
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name="character",
            name="religion",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="skin_color",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="weight",
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
