# Generated by Django 5.2.11 on 2026-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0019_character_age_character_appearance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="appearance",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
