# Generated by Django 5.2.11 on 2026-03-07 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0020_alter_character_appearance"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="money",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="appearance",
            field=models.TextField(blank=True, max_length=55, null=True),
        ),
    ]
