# Generated by Django 5.2.11 on 2026-03-08 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0023_language_alter_character_appearance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="race",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="school",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="technique",
            name="slug",
        ),
        migrations.AlterField(
            model_name="attribute",
            name="short_name",
            field=models.CharField(
                choices=[
                    ("GE", "Geschicklichkeit"),
                    ("WA", "Wahrnehmung"),
                    ("INT", "Intelligenz"),
                    ("WILL", "Willenskraft"),
                    ("ST", "Stärke"),
                    ("KON", "Konstitution"),
                ],
                max_length=4,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="div",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="schooltype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("magic", "Magic"),
                    ("divine", "Divine"),
                    ("combat", "Combat"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="skillcategory",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("skill_fine_motor", "Feinmotorische Fertigkeiten"),
                    ("skill_gross_motor", "Grobmotorische Fertigkeiten"),
                    ("skill_craft", "Handwerk"),
                    ("skill_social", "Soziale Fertigkeiten"),
                    ("skill_combat", "Waffenfertigkeiten"),
                    ("skill_knowledge", "Wissensfertigkeiten"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
