# Generated by Django 5.2.11 on 2026-03-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0024_remove_item_slug_remove_race_slug_remove_school_slug_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="overall_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="short_name",
            field=models.CharField(
                choices=[
                    ("GE", "Geschicklichkeit"),
                    ("WA", "Wahrnehmung"),
                    ("INT", "Intelligenz"),
                    ("WILL", "Willenskraft"),
                    ("ST", "Stärke"),
                    ("KON", "Konstitution"),
                    ("CHA", "Charisma"),
                ],
                max_length=4,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="current_experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
