# Generated by Django 5.2.11 on 2026-03-08 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0025_character_overall_experience_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="phase_1_attribute_points",
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name="race",
            name="phase_2_skill_points",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="race",
            name="phase_3_dis_points",
            field=models.PositiveIntegerField(
                default=20, validators=[django.core.validators.MaxValueValidator(20)]
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="phase_4_additional_points",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name="CharacterCreationDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_phase",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(4)],
                    ),
                ),
                ("state", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="charsheet.race"
                    ),
                ),
            ],
        ),
    ]
