# Generated by Django 5.2.11 on 2026-03-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0026_race_phase_1_attribute_points_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="race",
            old_name="phase_1_attribute_points",
            new_name="phase_1_points",
        ),
        migrations.RenameField(
            model_name="race",
            old_name="phase_2_skill_points",
            new_name="phase_2_points",
        ),
        migrations.RenameField(
            model_name="race",
            old_name="phase_3_dis_points",
            new_name="phase_3_points",
        ),
        migrations.RenameField(
            model_name="race",
            old_name="phase_4_additional_points",
            new_name="phase_4_points",
        ),
    ]
