# Generated by Django 5.2.11 on 2026-03-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0028_character_is_archived_character_last_opened_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponstats",
            name="two_handed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="two_handed_damage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="weight_class",
            field=models.CharField(
                choices=[("K", "K"), ("M", "M"), ("G", "G")], default="M", max_length=1
            ),
        ),
    ]
