# Generated by Django 5.2.11 on 2026-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0029_weaponstats_two_handed_weaponstats_two_handed_damage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="artefact_rank",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="personal_fame_point",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="personal_fame_rank",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="sacrefice_rank",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="character",
            name="current_damage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
