# Generated by Django 5.2.11 on 2026-03-10 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0030_character_artefact_rank_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="sacrefice_rank",
            new_name="sacrifice_rank",
        ),
        migrations.AlterField(
            model_name="character",
            name="personal_fame_point",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
