# Generated by Django 5.2.11 on 2026-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0031_rename_sacrefice_rank_character_sacrifice_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_consumable",
            field=models.BooleanField(default=False),
        ),
    ]
