# Generated by Django 5.2.11 on 2026-03-13 08:26

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0032_item_is_consumable"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSchoolPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": ["character", "school__type__name", "school__name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": [
                    "character",
                    "technique__school__name",
                    "technique__level",
                    "technique__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="SchoolPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["school__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "technique__school__name",
                    "technique__name",
                    "excluded_technique__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniqueRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_school_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": [
                    "technique__school__name",
                    "technique__level",
                    "technique__name",
                    "id",
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="characterschool",
            options={"ordering": ["character", "school__type__name", "school__name"]},
        ),
        migrations.AlterModelOptions(
            name="modifier",
            options={
                "ordering": [
                    "target_kind",
                    "target_slug",
                    "source_content_type",
                    "source_object_id",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="progressionrule",
            options={"ordering": ["school_type", "min_level", "grant_kind", "id"]},
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"ordering": ["type__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="schooltype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="technique",
            options={"ordering": ["school__name", "level", "sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="technique",
            name="acquisition_type",
            field=models.CharField(
                choices=[("automatic", "Automatic"), ("choice", "Choice")],
                default="automatic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("action", "Action"),
                    ("reaction", "Reaction"),
                    ("free", "Free"),
                    ("preparation", "Preparation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="activation_cost",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technique",
            name="activation_cost_resource",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="technique",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="technique",
            name="technique_type",
            field=models.CharField(
                choices=[
                    ("passive", "Passive"),
                    ("active", "Active"),
                    ("situational", "Situational"),
                ],
                default="passive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="usage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("at_will", "At Will"),
                    ("per_scene", "Per Scene"),
                    ("per_combat", "Per Combat"),
                    ("per_day", "Per Day"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="charsheet_m_source__1e69f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["target_kind", "target_slug"],
                name="charsheet_m_target__96bdf0_idx",
            ),
        ),
        migrations.AddField(
            model_name="characterschoolpath",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_school_paths",
                to="charsheet.character",
            ),
        ),
        migrations.AddField(
            model_name="characterschoolpath",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_path_choices",
                to="charsheet.school",
            ),
        ),
        migrations.AddField(
            model_name="charactertechnique",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learned_techniques",
                to="charsheet.character",
            ),
        ),
        migrations.AddField(
            model_name="charactertechnique",
            name="technique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_techniques",
                to="charsheet.technique",
            ),
        ),
        migrations.AddField(
            model_name="schoolpath",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to="charsheet.school",
            ),
        ),
        migrations.AddField(
            model_name="characterschoolpath",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_choices",
                to="charsheet.schoolpath",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techniques",
                to="charsheet.schoolpath",
            ),
        ),
        migrations.AddField(
            model_name="techniqueexclusion",
            name="excluded_technique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excluded_by",
                to="charsheet.technique",
            ),
        ),
        migrations.AddField(
            model_name="techniqueexclusion",
            name="technique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exclusions",
                to="charsheet.technique",
            ),
        ),
        migrations.AddField(
            model_name="techniquerequirement",
            name="required_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_for_techniques",
                to="charsheet.schoolpath",
            ),
        ),
        migrations.AddField(
            model_name="techniquerequirement",
            name="required_technique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_for_requirements",
                to="charsheet.technique",
            ),
        ),
        migrations.AddField(
            model_name="techniquerequirement",
            name="technique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="charsheet.technique",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactertechnique",
            constraint=models.UniqueConstraint(
                fields=("character", "technique"), name="uniq_character_technique"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolpath",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uniq_school_path_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterschoolpath",
            constraint=models.UniqueConstraint(
                fields=("character", "school"), name="uniq_character_school_path"
            ),
        ),
        migrations.AddConstraint(
            model_name="techniqueexclusion",
            constraint=models.UniqueConstraint(
                fields=("technique", "excluded_technique"),
                name="uniq_technique_exclusion_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="techniqueexclusion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Least(
                    "technique", "excluded_technique"
                ),
                django.db.models.functions.comparison.Greatest(
                    "technique", "excluded_technique"
                ),
                name="uniq_technique_exclusion_pair",
            ),
        ),
    ]
