# Generated by Django 5.2.11 on 2026-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0033_characterschoolpath_charactertechnique_schoolpath_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="height_class",
            field=models.CharField(
                default="M",
                max_length=5,
                verbose_name=[
                    ("S", "S"),
                    ("F", "F"),
                    ("W", "W"),
                    ("K", "K"),
                    ("M", "M"),
                    ("G", "G"),
                    ("R", "R"),
                    ("Gi", "Gi"),
                    ("Kol", "Kol"),
                ],
            ),
        ),
    ]
