# Generated by Django 5.2.11 on 2026-03-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0034_race_height_class"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="techniqueexclusion",
            name="uniq_technique_exclusion_pair",
        ),
    ]
