# Generated by Django 5.2.11 on 2026-03-13 08:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0035_remove_techniqueexclusion_uniq_technique_exclusion_pair"),
    ]

    operations = [
        migrations.AddField(
            model_name="techniquerequirement",
            name="required_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_for_techniques",
                to="charsheet.skill",
            ),
        ),
        migrations.AddField(
            model_name="techniquerequirement",
            name="required_skill_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="techniquerequirement",
            name="required_trait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_for_techniques",
                to="charsheet.trait",
            ),
        ),
        migrations.AddField(
            model_name="techniquerequirement",
            name="required_trait_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
