# Generated by Django 5.2.11 on 2026-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0036_techniquerequirement_required_skill_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="race",
            old_name="height_class",
            new_name="size_class",
        ),
        migrations.RemoveField(
            model_name="weaponstats",
            name="weight_class",
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="size_class",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("F", "F"),
                    ("W", "W"),
                    ("K", "K"),
                    ("M", "M"),
                    ("G", "G"),
                    ("R", "R"),
                    ("Gi", "Gi"),
                    ("Kol", "Kol"),
                ],
                default="M",
                max_length=5,
            ),
        ),
    ]
