# Generated by Django 5.2.11 on 2026-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0038_skillfamily_skill_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="choice_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional group key for alternative techniques or shared choice buckets on the same level.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="is_choice_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="Mark placeholder rows such as 'choose one technique' or 'pick a skill'.",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="selection_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short editor-facing note that explains what exactly must be chosen.",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="support_level",
            field=models.CharField(
                choices=[
                    ("computed", "Computed"),
                    ("structured", "Structured"),
                    ("descriptive", "Descriptive"),
                ],
                default="computed",
                help_text="How far the engine can resolve this technique beyond status and requirements.",
                max_length=20,
            ),
        ),
    ]
