# Generated by Django 5.2.11 on 2026-03-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0039_technique_choice_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolpath",
            options={"ordering": ["school__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="technique",
            options={"ordering": ["school__name", "level", "name"]},
        ),
        migrations.RemoveField(
            model_name="schoolpath",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="technique",
            name="sort_order",
        ),
    ]
