# Generated by Django 5.2.11 on 2026-03-13 12:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0040_alter_schoolpath_options_alter_technique_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="choice_bonus_value",
            field=models.SmallIntegerField(
                default=0,
                help_text="Fixed computed bonus applied to the chosen skill or skill family.",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="choice_limit",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many persistent character choices this technique may store.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="choice_target_kind",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("skill", "Skill"),
                    ("skill_family", "Skill Family"),
                ],
                default="none",
                help_text="Persistent choice type that must be stored for this technique, if any.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CharacterTechniqueChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_choices",
                        to="charsheet.character",
                    ),
                ),
                (
                    "selected_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_technique_choices",
                        to="charsheet.skill",
                    ),
                ),
                (
                    "selected_skill_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_technique_choices",
                        to="charsheet.skillfamily",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_choices",
                        to="charsheet.technique",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "character__name",
                    "technique__school__name",
                    "technique__level",
                    "technique__name",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("selected_skill__isnull", False)),
                        fields=("character", "technique", "selected_skill"),
                        name="uniq_character_technique_selected_skill",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("selected_skill_family__isnull", False)),
                        fields=("character", "technique", "selected_skill_family"),
                        name="uniq_character_technique_selected_family",
                    ),
                ],
            },
        ),
    ]
