# Generated by Django 5.2.11 on 2026-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0041_technique_choice_bonus_value_technique_choice_limit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="requires_specification",
            field=models.BooleanField(default=False),
        ),
    ]
