# Generated by Django 5.2.11 on 2026-03-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0042_skill_requires_specification"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterskill",
            name="specification",
            field=models.CharField(blank=True, default="*", max_length=25),
        ),
    ]
