# Generated by Django 5.2.11 on 2026-03-13 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0044_characterdiaryentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="specialization_slot_grants",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many school-bound specialization slots this technique unlocks once it is learned and currently available.",
            ),
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "support_level",
                    models.CharField(
                        choices=[
                            ("computed", "Computed"),
                            ("structured", "Structured"),
                            ("descriptive", "Descriptive"),
                        ],
                        default="structured",
                        help_text="How far the engine can resolve this specialization beyond basic status tracking.",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="charsheet.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learned_specializations",
                        to="charsheet.character",
                    ),
                ),
                (
                    "source_technique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_specializations",
                        to="charsheet.technique",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_specializations",
                        to="charsheet.specialization",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "character",
                    "specialization__school__name",
                    "specialization__sort_order",
                    "specialization__name",
                    "id",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="specialization",
            constraint=models.UniqueConstraint(
                fields=("school", "slug"), name="uniq_specialization_school_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterspecialization",
            constraint=models.UniqueConstraint(
                fields=("character", "specialization"),
                name="uniq_character_specialization",
            ),
        ),
    ]
