# Generated by Django 5.2.11 on 2026-03-13 20:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0045_technique_specialization_slot_grants_specialization_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechniqueChoiceBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short editor-facing label used to identify the rulebook choice block.",
                        max_length=120,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional school level at which this choice block becomes relevant.",
                        null=True,
                    ),
                ),
                (
                    "min_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Minimum number of techniques that must be learned from this block.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum number of techniques that may be learned from this block.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Rulebook wording that explains what the player must choose here.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["school__name", "level", "sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueChoiceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Readable label that identifies this choice requirement in rulebook terms.",
                        max_length=120,
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("skill", "Skill"),
                            ("skill_family", "Skill Family"),
                            ("skill_category", "Skill Category"),
                            ("item", "Item"),
                            ("item_category", "Item Category"),
                            ("specialization", "Specialization"),
                            ("text", "Free Text"),
                            ("entity", "Other Entity"),
                        ],
                        help_text="What kind of thing must be selected for this technique decision.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short rulebook prompt that explains what exactly must be chosen.",
                    ),
                ),
                (
                    "min_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Minimum number of stored selections required for this one decision.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum number of stored selections allowed for this one decision.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, the technique stays incomplete until this decision reaches min_choices.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": [
                    "technique__school__name",
                    "technique__level",
                    "technique__name",
                    "sort_order",
                    "name",
                    "id",
                ],
            },
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="selected_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_technique_choice_targets",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="selected_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_technique_choices",
                to="charsheet.item",
            ),
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="selected_item_category",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="selected_object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="selected_skill_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_technique_choices",
                to="charsheet.skillcategory",
            ),
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="selected_specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_technique_choices",
                to="charsheet.specialization",
            ),
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="selected_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="modifier",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_target_relations",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="target_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modifiers",
                to="charsheet.item",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="target_object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modifier",
            name="target_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modifiers",
                to="charsheet.skill",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="target_skill_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modifiers",
                to="charsheet.skillcategory",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="target_specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modifiers",
                to="charsheet.specialization",
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="source_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_source_relations",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("skill", "Skill"),
                    ("category", "Skill Category"),
                    ("stat", "Stat"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("entity", "Other Entity"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="target_slug",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="technique",
            name="choice_target_kind",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("skill", "Skill"),
                    ("skill_family", "Skill Family"),
                    ("skill_category", "Skill Category"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("text", "Free Text"),
                    ("entity", "Other Entity"),
                ],
                default="none",
                help_text="Persistent choice type that must be stored for this technique, if any.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="charsheet_m_target__f7da17_idx",
            ),
        ),
        migrations.AddField(
            model_name="techniquechoiceblock",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional school path restriction for this block.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technique_choice_blocks",
                to="charsheet.schoolpath",
            ),
        ),
        migrations.AddField(
            model_name="techniquechoiceblock",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technique_choice_blocks",
                to="charsheet.school",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="choice_block",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional rule choice block that defines mandatory or limited technique picks.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techniques",
                to="charsheet.techniquechoiceblock",
            ),
        ),
        migrations.AddField(
            model_name="techniquechoicedefinition",
            name="technique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choice_definitions",
                to="charsheet.technique",
            ),
        ),
        migrations.AddField(
            model_name="charactertechniquechoice",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_choices",
                to="charsheet.techniquechoicedefinition",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactertechniquechoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("selected_skill_category__isnull", False)),
                fields=(
                    "character",
                    "technique",
                    "definition",
                    "selected_skill_category",
                ),
                name="uniq_character_technique_selected_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactertechniquechoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("selected_item__isnull", False)),
                fields=("character", "technique", "definition", "selected_item"),
                name="uniq_character_technique_selected_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactertechniquechoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("selected_specialization__isnull", False)),
                fields=(
                    "character",
                    "technique",
                    "definition",
                    "selected_specialization",
                ),
                name="uniq_character_technique_selected_specialization",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactertechniquechoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("selected_item_category", ""), _negated=True),
                fields=(
                    "character",
                    "technique",
                    "definition",
                    "selected_item_category",
                ),
                name="uniq_character_technique_selected_item_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactertechniquechoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("selected_object_id__isnull", False)),
                fields=(
                    "character",
                    "technique",
                    "definition",
                    "selected_content_type",
                    "selected_object_id",
                ),
                name="uniq_character_technique_selected_entity",
            ),
        ),
    ]
