# Generated by Django 5.2.11 on 2026-03-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0046_techniquechoiceblock_techniquechoicedefinition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactertechniquechoice",
            name="selected_skill_family",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="family",
        ),
        migrations.DeleteModel(
            name="SkillFamily",
        ),
    ]
