# Generated by Django 5.2.11 on 2026-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0047_remove_charactertechniquechoice_selected_skill_family_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "charsheet_charactertechniquechoice" '
                        'DROP CONSTRAINT IF EXISTS "uniq_character_technique_selected_family";'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="charactertechniquechoice",
                    name="uniq_character_technique_selected_family",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="specialization",
            name="support_level",
            field=models.CharField(
                choices=[
                    ("computed", "Automated"),
                    ("structured", "Partially Automated"),
                    ("descriptive", "Manual (Rule Text Only)"),
                ],
                default="structured",
                help_text="How far the engine can resolve this specialization beyond basic status tracking.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="choice_bonus_value",
            field=models.SmallIntegerField(
                default=0, help_text="Fixed computed bonus applied to the chosen skill."
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="choice_target_kind",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("skill", "Skill"),
                    ("skill_category", "Skill Category"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("text", "Free Text"),
                    ("entity", "Other Entity"),
                ],
                default="none",
                help_text="Persistent choice type that must be stored for this technique, if any.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="support_level",
            field=models.CharField(
                choices=[
                    ("computed", "Automated"),
                    ("structured", "Partially Automated"),
                    ("descriptive", "Manual (Rule Text Only)"),
                ],
                default="computed",
                help_text="How far the engine can resolve this technique beyond status and requirements.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="techniquechoicedefinition",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("skill", "Skill"),
                    ("skill_category", "Skill Category"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("text", "Free Text"),
                    ("entity", "Other Entity"),
                ],
                help_text="What kind of thing must be selected for this technique decision.",
                max_length=20,
            ),
        ),
    ]
