# Generated by Django 5.2.11 on 2026-03-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0048_remove_charactertechniquechoice_uniq_character_technique_selected_family_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quality",
            field=models.CharField(
                choices=[
                    ("wretched", "Extrem schlechte Qualität"),
                    ("very_poor", "Sehr schlechte Qualität"),
                    ("poor", "Schlechte Qualität"),
                    ("common", "Normale Qualität"),
                    ("fine", "Gute Qualität"),
                    ("excellent", "Exzellente Qualität"),
                    ("legendary", "Legendäre Qualität"),
                ],
                default="common",
                max_length=20,
            ),
        ),
    ]
