# Generated by Django 5.2.11 on 2026-03-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0049_item_quality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="quality",
            new_name="default_quality",
        ),
    ]
