# Generated by Django 5.2.11 on 2026-03-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0050_rename_item_quality_default_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShieldStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rs", models.PositiveIntegerField(default=0)),
                ("encumbrance", models.PositiveIntegerField(default=0)),
                ("min_st", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="characteritem",
            name="unique_item_per_character",
        ),
        migrations.RemoveField(
            model_name="weaponstats",
            name="damage",
        ),
        migrations.RemoveField(
            model_name="weaponstats",
            name="size_class",
        ),
        migrations.RemoveField(
            model_name="weaponstats",
            name="two_handed",
        ),
        migrations.RemoveField(
            model_name="weaponstats",
            name="two_handed_damage",
        ),
        migrations.AddField(
            model_name="armorstats",
            name="encumbrance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="armorstats",
            name="min_st",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="quality",
            field=models.CharField(
                choices=[
                    ("wretched", "Extrem schlechte Qualität"),
                    ("very_poor", "Sehr schlechte Qualität"),
                    ("poor", "Schlechte Qualität"),
                    ("common", "Normale Qualität"),
                    ("fine", "Gute Qualität"),
                    ("excellent", "Exzellente Qualität"),
                    ("legendary", "Legendäre Qualität"),
                ],
                default="common",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="size_class",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("F", "F"),
                    ("W", "W"),
                    ("K", "K"),
                    ("M", "M"),
                    ("G", "G"),
                    ("R", "R"),
                    ("Gi", "Gi"),
                    ("Kol", "Kol"),
                ],
                default="M",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="damage_dice_amount",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="damage_dice_faces",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="damage_flat_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="h2_dice_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="h2_dice_faces",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="h2_flat_bonus",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="wield_mode",
            field=models.CharField(
                choices=[
                    ("1h", "Einhändig"),
                    ("2h", "Zweihändig"),
                    ("vh", "Ein- und Zweihändig"),
                ],
                default="1h",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("armor", "Rüstung"),
                    ("weapon", "Waffe"),
                    ("shield", "Schild"),
                    ("consumable", "verbrauchbar"),
                    ("misc", "Misc"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shieldstats",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="charsheet.item"
            ),
        ),
    ]
