# Generated by Django 5.2.11 on 2026-03-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0051_shieldstats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("armor", "Rüstung"),
                    ("weapon", "Waffe"),
                    ("shield", "Schild"),
                    ("consumable", "verbrauchbar"),
                    ("ammo", "Monition"),
                    ("misc", "Misc"),
                ],
                max_length=20,
            ),
        ),
    ]
