# Generated by Django 5.2.11 on 2026-03-16 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0052_alter_item_item_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dddice_enabled", models.BooleanField(default=False)),
                (
                    "dddice_api_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dddice_room_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dddice_room_password",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dddice_dice_box",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
