# Generated by Django 5.2.11 on 2026-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0053_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="dddice_theme_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
