# Generated by Django 5.2.11 on 2026-03-17 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0054_usersettings_dddice_theme_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_family",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="charsheet.attribute",
            ),
        ),
    ]
