# Generated by Django 5.2.11 on 2026-03-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0055_skill_skill_family_alter_skill_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="charsheet.attribute",
            ),
        ),
    ]
