# Generated by Django 5.2.11 on 2026-03-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0056_alter_skill_attribute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="skill_family",
        ),
        migrations.AlterField(
            model_name="attribute",
            name="short_name",
            field=models.CharField(
                choices=[
                    ("GE", "Geschicklichkeit"),
                    ("WA", "Wahrnehmung"),
                    ("INT", "Intelligenz"),
                    ("WILL", "Willenskraft"),
                    ("ST", "Stärke"),
                    ("KON", "Konstitution"),
                    ("CHA", "Charisma"),
                    ("spz.", "Spezial"),
                ],
                max_length=4,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="charsheet.attribute"
            ),
        ),
    ]
