# Generated by Django 5.2.11 on 2026-03-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0057_remove_skill_skill_family_alter_attribute_short_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="family",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="techniquechoicedefinition",
            name="allowed_skill_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technique_choice_definitions",
                to="charsheet.skillcategory",
            ),
        ),
        migrations.AddField(
            model_name="techniquechoicedefinition",
            name="allowed_skill_family",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("skill", "Skill"),
                    ("category", "Skill Category"),
                    ("stat", "Stat"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("entity", "Other Entity"),
                    ("family", "Skill Family"),
                ],
                max_length=30,
            ),
        ),
    ]
