# Generated by Django 5.2.11 on 2026-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0058_skill_family_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifier",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("skill", "Skill"),
                    ("category", "Skill Category"),
                    ("stat", "Stat"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("entity", "Other Entity"),
                ],
                max_length=30,
            ),
        ),
    ]
