# Generated by Django 5.2.11 on 2026-03-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0059_alter_modifier_target_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="target_choice_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targeting_modifiers",
                to="charsheet.techniquechoicedefinition",
            ),
        ),
    ]
