# Generated by Django 5.2.11 on 2026-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0061_modifier_target_choice_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactertechnique",
            name="specification_value",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="technique",
            name="has_specification",
            field=models.BooleanField(default=False),
        ),
    ]
