# Generated by Django 5.2.11 on 2026-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0062_charactertechnique_specification_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="size_class",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("F", "F"),
                    ("W", "W"),
                    ("K", "K"),
                    ("M", "M"),
                    ("G", "G"),
                    ("R", "R"),
                    ("Gi", "Gi"),
                    ("Kol", "Kol"),
                ],
                default="M",
                max_length=5,
                verbose_name="SizeClass",
            ),
        ),
    ]
