# Generated by Django 5.2.11 on 2026-03-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0063_alter_race_size_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techniques",
                        to="charsheet.race",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_links",
                        to="charsheet.technique",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("race", "technique"), name="uniq_race_technique"
                    )
                ],
            },
        ),
    ]
