# Generated by Django 5.2.11 on 2026-03-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0064_racetechnique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="level",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techniques",
                to="charsheet.school",
            ),
        ),
    ]
