# Generated by Django 5.2.11 on 2026-03-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0065_alter_technique_level_alter_technique_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techniques",
                to="charsheet.school",
            ),
        ),
    ]
