# Generated by Django 5.2.11 on 2026-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0066_alter_technique_level_alter_technique_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="appearance",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
