# Generated by Django 5.2.11 on 2026-03-30 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0068_alter_race_swimming_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceStartingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=1)),
                ("quality", models.CharField(blank=True, default="", max_length=30)),
                ("equipped", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_starting_items",
                        to="charsheet.item",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_items",
                        to="charsheet.race",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("race", "item"), name="uniq_race_starting_item"
                    )
                ],
            },
        ),
    ]
