# Generated by Django 5.2.11 on 2026-03-30 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0071_backfill_race_items_equipped_locked"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceChoiceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Readable label that identifies this race choice in rulebook terms.",
                        max_length=120,
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("skill", "Skill"),
                            ("skill_category", "Skill Category"),
                            ("item", "Item"),
                            ("item_category", "Item Category"),
                            ("specialization", "Specialization"),
                            ("text", "Free Text"),
                            ("entity", "Other Entity"),
                        ],
                        help_text="What kind of thing must be selected for this race decision.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short rulebook prompt that explains what exactly must be chosen.",
                    ),
                ),
                (
                    "min_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Minimum number of stored selections required for this race decision.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum number of stored selections allowed for this race decision.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, the race stays incomplete until this decision reaches min_choices.",
                    ),
                ),
                ("allowed_skill_family", models.SlugField(blank=True, default="")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allowed_skill_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="race_choice_definitions",
                        to="charsheet.skillcategory",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choice_definitions",
                        to="charsheet.race",
                    ),
                ),
            ],
            options={
                "ordering": ["race__name", "sort_order", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="modifier",
            name="target_race_choice_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targeting_modifiers",
                to="charsheet.racechoicedefinition",
            ),
        ),
        migrations.CreateModel(
            name="CharacterRaceChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_item_category",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "selected_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "selected_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_choices",
                        to="charsheet.character",
                    ),
                ),
                (
                    "selected_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_race_choice_targets",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "selected_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_race_choices",
                        to="charsheet.item",
                    ),
                ),
                (
                    "selected_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_race_choices",
                        to="charsheet.skill",
                    ),
                ),
                (
                    "selected_skill_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_race_choices",
                        to="charsheet.skillcategory",
                    ),
                ),
                (
                    "selected_specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_race_choices",
                        to="charsheet.specialization",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_choices",
                        to="charsheet.racechoicedefinition",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "character__name",
                    "definition__race__name",
                    "definition__sort_order",
                    "definition__name",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("selected_skill__isnull", False)),
                        fields=("character", "definition", "selected_skill"),
                        name="uniq_character_race_choice_selected_skill",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("selected_skill_category__isnull", False)),
                        fields=("character", "definition", "selected_skill_category"),
                        name="uniq_character_race_choice_selected_category",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("selected_item__isnull", False)),
                        fields=("character", "definition", "selected_item"),
                        name="uniq_character_race_choice_selected_item",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("selected_specialization__isnull", False)),
                        fields=("character", "definition", "selected_specialization"),
                        name="uniq_character_race_choice_selected_specialization",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("selected_item_category", ""), _negated=True
                        ),
                        fields=("character", "definition", "selected_item_category"),
                        name="uniq_character_race_choice_selected_item_category",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("selected_object_id__isnull", False)),
                        fields=(
                            "character",
                            "definition",
                            "selected_content_type",
                            "selected_object_id",
                        ),
                        name="uniq_character_race_choice_selected_entity",
                    ),
                ],
            },
        ),
    ]
