# Generated by Django 5.2.11 on 2026-03-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0072_racechoicedefinition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("mounted_two_handed", "-"),
                            ("first_round_init", "I"),
                            ("chain_fumble", "$"),
                            ("requires_dex", "(Ge)"),
                            ("can_entangle", "^"),
                            ("drag_target", "^^"),
                            ("caltrop_effect", "+"),
                            ("explode_on_fumble", "#"),
                            ("set_against_charge", "→"),
                            ("parry_bonus", "P"),
                            ("unarmed_damage", "*"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="weaponstats",
            name="damage_source",
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="damage_type",
            field=models.CharField(
                choices=[("B", "B"), ("T", "T")], default="T", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="flags",
            field=models.ManyToManyField(blank=True, to="charsheet.weaponflag"),
        ),
    ]
