# Generated by Django 5.2.11 on 2026-03-30 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0073_weaponflag_remove_weaponstats_damage_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponstats",
            name="damage_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="charsheet.damagesource",
            ),
        ),
    ]
