# Generated by Django 5.2.11 on 2026-03-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0074_weaponstats_damage_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponstats",
            name="damage_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="charsheet.damagesource"
            ),
        ),
    ]
