# Generated by Django 5.2.11 on 2026-03-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0075_alter_weaponstats_damage_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="weaponstats",
            name="damage_flat_bonus",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="weaponstats",
            name="h2_flat_bonus",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="runes",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="charsheet.rune"
            ),
        ),
    ]
