# Generated by Django 5.2.11 on 2026-03-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0076_rune_alter_weaponstats_damage_flat_bonus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rune",
            name="image",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
