# Generated by Django 5.2.11 on 2026-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0078_characteritem_runes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rune",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="runes/"),
        ),
    ]
