# Generated by Django 5.2.11 on 2026-04-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0001_squashed_0079_alter_rune_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifier",
            name="scale_skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Only used if scale_source or cap_source uses a skill-based value.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scale_modifiers",
                to="charsheet.skill",
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="cap_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("school_level", "School level"),
                    ("fame_total", "Fame total"),
                    ("trait_level", "Trait Level"),
                    ("skill_level", "Skill level"),
                    ("skill_total", "Skill total"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="scale_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("school_level", "School level"),
                    ("fame_total", "Fame total"),
                    ("trait_level", "Trait Level"),
                    ("skill_level", "Skill level"),
                    ("skill_total", "Skill total"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
