# Generated by Django 5.2.11 on 2026-04-20 15:05

from decimal import Decimal

import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models


CLOTHING_ITEMS = [
    {
        "name": "Bauernkleidung",
        "price": 60,
        "weight": Decimal("2.00"),
        "default_quality": "poor",
        "description": (
            "Unterwaesche aus einfachem Leinen, Hemd, Hose und Lederschuhe. "
            "Schlechte Qualitaet."
        ),
    },
    {
        "name": "Festtagskleidung",
        "price": 460,
        "weight": Decimal("2.50"),
        "default_quality": "fine",
        "description": (
            "Unterwaesche, Hemd, Hose, Hut, Schuhe, Struempfe, Guertel und Cape. "
            "Gute Qualitaet."
        ),
    },
    {
        "name": "Hofkleidung",
        "price": 900,
        "weight": Decimal("2.75"),
        "default_quality": "excellent",
        "description": (
            "Rueschenhemd, Samtkniebundhose, Struempfe, Unterwaesche, Hut, Schuhe, "
            "Guertel, Samthandschuhe und Cape oder Rockjacke. Exzellente Qualitaet."
        ),
    },
    {
        "name": "Jagdkleidung",
        "price": 500,
        "weight": Decimal("4.50"),
        "default_quality": "fine",
        "description": (
            "Unterwaesche, Struempfe, Kapuzenumhang, Lederhemd, Wildlederhose, "
            "Stulpenstiefel, Guertel, Guerteltaschen und Stulpenhandschuhe. Gute Qualitaet."
        ),
    },
    {
        "name": "Lumpen",
        "price": 5,
        "weight": Decimal("0.50"),
        "default_quality": "wretched",
        "description": "Zusammengebundene Fetzen einfacher Lumpen.",
    },
    {
        "name": "Magier- oder Priesterroben",
        "price": 200,
        "weight": Decimal("2.00"),
        "default_quality": "fine",
        "description": "Unterwaesche, Sandalen, Robe und Guertel. Gute Qualitaet.",
    },
    {
        "name": "Prunkvolle Abendgarderobe",
        "price": 5000,
        "weight": Decimal("4.25"),
        "default_quality": "legendary",
        "description": (
            "Unterwaesche aus Seide, verzierte Schuhe, Seidenstruempfe, aufwendige "
            "gepuderte Peruecke, Seidenhandschuhe und ein prunkvolles Ensemble fuer Ball "
            "oder Hof. Legendaere Qualitaet."
        ),
    },
    {
        "name": "Reisekleidung",
        "price": 220,
        "weight": Decimal("3.50"),
        "default_quality": "common",
        "description": (
            "Unterwaesche, Hemd, Hose oder Rock, Struempfe, Kapuzenmantel, "
            "Lederstiefel und Guertel. Normale Qualitaet."
        ),
    },
    {
        "name": "Winterreisekleidung",
        "price": 600,
        "weight": Decimal("4.75"),
        "default_quality": "fine",
        "description": (
            "Unterwaesche, Struempfe, Fellweste, warmes Hemd, gefuetterte Hose, "
            "gefuetterte Stiefel, Fellmantel, Guertel, Fellmuetze und Fellfaeustlinge. "
            "Gute Qualitaet."
        ),
    },
]


def add_clothing_items(apps, schema_editor):
    Item = apps.get_model("charsheet", "Item")
    ArmorStats = apps.get_model("charsheet", "ArmorStats")
    ShieldStats = apps.get_model("charsheet", "ShieldStats")
    WeaponStats = apps.get_model("charsheet", "WeaponStats")

    for payload in CLOTHING_ITEMS:
        item, _created = Item.objects.update_or_create(
            name=payload["name"],
            defaults={
                "price": payload["price"],
                "item_type": "clothing",
                "description": payload["description"],
                "stackable": False,
                "is_consumable": False,
                "default_quality": payload["default_quality"],
                "weight": payload["weight"],
                "size_class": "M",
            },
        )
        ArmorStats.objects.filter(item=item).delete()
        ShieldStats.objects.filter(item=item).delete()
        WeaponStats.objects.filter(item=item).delete()


def remove_clothing_items(apps, schema_editor):
    Item = apps.get_model("charsheet", "Item")
    Item.objects.filter(name__in=[payload["name"] for payload in CLOTHING_ITEMS]).delete()


def normalize_weapon_bonus_operators(apps, schema_editor):
    WeaponStats = apps.get_model("charsheet", "WeaponStats")

    for stats in WeaponStats.objects.all():
        base_bonus = int(stats.damage_flat_bonus or 0)
        if base_bonus > 0:
            stats.damage_flat_operator = "+"
        elif base_bonus < 0:
            stats.damage_flat_operator = "-"
            stats.damage_flat_bonus = abs(base_bonus)
        else:
            stats.damage_flat_operator = ""

        h2_bonus = stats.h2_flat_bonus
        if h2_bonus is None:
            stats.h2_flat_operator = ""
        elif h2_bonus > 0:
            stats.h2_flat_operator = "+"
        elif h2_bonus < 0:
            stats.h2_flat_operator = "-"
            stats.h2_flat_bonus = abs(h2_bonus)
        else:
            stats.h2_flat_operator = ""

        stats.save(
            update_fields=[
                "damage_flat_bonus",
                "damage_flat_operator",
                "h2_flat_bonus",
                "h2_flat_operator",
            ]
        )


def sync_legacy_fullplate(apps, schema_editor):
    Item = apps.get_model("charsheet", "Item")
    ArmorStats = apps.get_model("charsheet", "ArmorStats")

    try:
        legacy_item = Item.objects.get(pk=1)
        reference_item = Item.objects.get(pk=158)
    except Item.DoesNotExist:
        return

    try:
        legacy_stats = ArmorStats.objects.get(item_id=legacy_item.pk)
        reference_stats = ArmorStats.objects.get(item_id=reference_item.pk)
    except ArmorStats.DoesNotExist:
        return

    legacy_item.price = reference_item.price
    legacy_item.default_quality = reference_item.default_quality
    legacy_item.weight = reference_item.weight or Decimal("35.00")
    legacy_item.size_class = reference_item.size_class
    legacy_item.save(update_fields=["price", "default_quality", "weight", "size_class"])

    legacy_stats.rs_total = reference_stats.rs_total
    legacy_stats.encumbrance = reference_stats.encumbrance
    legacy_stats.min_st = reference_stats.min_st
    legacy_stats.save(update_fields=["rs_total", "encumbrance", "min_st"])


def mark_existing_magic_items(apps, schema_editor):
    Item = apps.get_model("charsheet", "Item")
    Item.objects.filter(item_type="magic_item").update(is_magic=True)


def migrate_school_type_slugs(apps, schema_editor):
    SchoolType = apps.get_model("charsheet", "SchoolType")
    slug_map = {
        "school_magic": "arcane",
        "school_divine": "divine",
        "school_combat": "combat",
    }
    for old_slug, new_slug in slug_map.items():
        SchoolType.objects.filter(slug=old_slug).update(slug=new_slug)

    defaults_by_slug = {
        "arcane": "Magieschule",
        "divine": "Klerikale Schule",
        "combat": "Kampfschule",
    }
    for slug, name in defaults_by_slug.items():
        SchoolType.objects.get_or_create(slug=slug, defaults={"name": name})

class Migration(migrations.Migration):

    replaces = [('charsheet', '0080_modifier_scale_skill_alter_modifier_cap_source_and_more'), ('charsheet', '0081_traitsemanticeffect'), ('charsheet', '0082_trait_choice_definitions_and_semantic_effect_binding'), ('charsheet', '0084_alter_traitsemanticeffect_target_domain'), ('charsheet', '0083_traitexclusion_trait_excluded_traits_and_more'), ('charsheet', '0085_merge_0083_0084'), ('charsheet', '0086_trait_proficiency_group_choices'), ('charsheet', '0087_charactertraitchoice_selected_derived_stat_and_more'), ('charsheet', '0088_trait_points_by_level'), ('charsheet', '0089_alter_traitsemanticeffect_target_domain'), ('charsheet', '0090_charactertraitchoice_selected_resource_and_more'), ('charsheet', '0091_characterweaponmastery_characterweaponmasteryarcana'), ('charsheet', '0092_alter_schooltype_slug'), ('charsheet', '0093_item_clothing_and_garnitures'), ('charsheet', '0094_add_weapon_damage_operators'), ('charsheet', '0096_weaponstats_damage_bonus_attribute_and_more'), ('charsheet', '0097_character_current_arcane_power'), ('charsheet', '0098_fix_legacy_fullplate_stats'), ('charsheet', '0099_alter_item_item_type_magicitemstats'), ('charsheet', '0100_modifier_effect_description'), ('charsheet', '0101_item_is_magic'), ('charsheet', '0102_alter_character_current_arcane_power_and_more'), ('charsheet', '0103_characteritem_is_magic_and_summary'), ('charsheet', '0104_characteritem_description'), ('charsheet', '0105_rune_spec_and_allow_multiple'), ('charsheet', '0106_alter_schooltype_slug_aspect_characterspellsource_and_more'), ('charsheet', '0107_alter_spell_options_rename_level_spell_grade_and_more'), ('charsheet', '0108_remove_spell_attribute'), ('charsheet', '0109_spell_grade_adds_school_level'), ('charsheet', '0110_spell_panel_badge_label'), ('charsheet', '0111_school_panel_symbol'), ('charsheet', '0112_rename_spell_resistance_text')]

    dependencies = [
        ('charsheet', '0001_squashed_0079_alter_rune_image'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='scale_skill',
            field=models.ForeignKey(blank=True, help_text='Only used if scale_source or cap_source uses a skill-based value.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scale_modifiers', to='charsheet.skill'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='cap_source',
            field=models.CharField(blank=True, choices=[('school_level', 'School level'), ('fame_total', 'Fame total'), ('trait_level', 'Trait Level'), ('skill_level', 'Skill level'), ('skill_total', 'Skill total')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='scale_source',
            field=models.CharField(blank=True, choices=[('school_level', 'School level'), ('fame_total', 'Fame total'), ('trait_level', 'Trait Level'), ('skill_level', 'Skill level'), ('skill_total', 'Skill total')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='TraitChoiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Readable label that identifies this trait choice in rulebook terms.', max_length=120)),
                ('target_kind', models.CharField(choices=[('attribute', 'Attribute'), ('skill', 'Skill'), ('skill_category', 'Skill Category'), ('item', 'Item'), ('item_category', 'Item Category'), ('specialization', 'Specialization'), ('text', 'Free Text'), ('entity', 'Other Entity')], help_text='What kind of thing must be selected for this trait decision.', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Short rulebook prompt that explains what exactly must be chosen.')),
                ('min_choices', models.PositiveSmallIntegerField(default=1, help_text='Minimum number of stored selections required for this trait decision.', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_choices', models.PositiveSmallIntegerField(default=1, help_text='Maximum number of stored selections allowed for this trait decision.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True, help_text='If enabled, the trait stays incomplete until this decision reaches min_choices.')),
                ('allowed_skill_family', models.SlugField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trait_choice_definitions', to='charsheet.attribute')),
                ('allowed_skill_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trait_choice_definitions', to='charsheet.skillcategory')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_definitions', to='charsheet.trait')),
            ],
            options={
                'ordering': ['trait__trait_type', 'trait__name', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterTraitChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_item_category', models.CharField(blank=True, default='', max_length=30)),
                ('selected_text', models.CharField(blank=True, default='', max_length=255)),
                ('selected_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('character_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='charsheet.charactertrait')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_choices', to='charsheet.traitchoicedefinition')),
                ('selected_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_trait_choices', to='charsheet.attribute')),
                ('selected_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_trait_choice_targets', to='contenttypes.contenttype')),
                ('selected_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_trait_choices', to='charsheet.item')),
                ('selected_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_trait_choices', to='charsheet.skill')),
                ('selected_skill_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_trait_choices', to='charsheet.skillcategory')),
                ('selected_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_trait_choices', to='charsheet.specialization')),
            ],
            options={
                'ordering': ['character_trait__owner__name', 'character_trait__trait__name', 'definition__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('selected_attribute__isnull', False)), fields=('character_trait', 'definition', 'selected_attribute'), name='uniq_character_trait_choice_selected_attribute'), models.UniqueConstraint(condition=models.Q(('selected_skill__isnull', False)), fields=('character_trait', 'definition', 'selected_skill'), name='uniq_character_trait_choice_selected_skill'), models.UniqueConstraint(condition=models.Q(('selected_skill_category__isnull', False)), fields=('character_trait', 'definition', 'selected_skill_category'), name='uniq_character_trait_choice_selected_category'), models.UniqueConstraint(condition=models.Q(('selected_item__isnull', False)), fields=('character_trait', 'definition', 'selected_item'), name='uniq_character_trait_choice_selected_item'), models.UniqueConstraint(condition=models.Q(('selected_specialization__isnull', False)), fields=('character_trait', 'definition', 'selected_specialization'), name='uniq_character_trait_choice_selected_specialization'), models.UniqueConstraint(condition=models.Q(('selected_item_category', ''), _negated=True), fields=('character_trait', 'definition', 'selected_item_category'), name='uniq_character_trait_choice_selected_item_category'), models.UniqueConstraint(condition=models.Q(('selected_object_id__isnull', False)), fields=('character_trait', 'definition', 'selected_content_type', 'selected_object_id'), name='uniq_character_trait_choice_selected_entity')],
            },
        ),
        migrations.CreateModel(
            name='TraitSemanticEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('target_domain', models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('language', 'language'), ('trait', 'trait'), ('attribute', 'attribute'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity')], default='rule_flag', max_length=40)),
                ('target_key', models.CharField(blank=True, default='', max_length=120)),
                ('operator', models.CharField(choices=[('flat_add', 'flat_add'), ('flat_sub', 'flat_sub'), ('multiply', 'multiply'), ('override', 'override'), ('min_value', 'min_value'), ('max_value', 'max_value'), ('set_flag', 'set_flag'), ('unset_flag', 'unset_flag'), ('add_tag', 'add_tag'), ('remove_tag', 'remove_tag'), ('grant_capability', 'grant_capability'), ('remove_capability', 'remove_capability'), ('grant_immunity', 'grant_immunity'), ('grant_vulnerability', 'grant_vulnerability'), ('change_resource_cap', 'change_resource_cap'), ('change_starting_funds', 'change_starting_funds'), ('change_appearance_class', 'change_appearance_class'), ('change_social_status', 'change_social_status'), ('reroll_grant', 'reroll_grant'), ('reroll_forbid', 'reroll_forbid'), ('repeat_action_allowed', 'repeat_action_allowed'), ('action_cost_change', 'action_cost_change'), ('conditional_bonus', 'conditional_bonus'), ('conditional_penalty', 'conditional_penalty')], default='flat_add', max_length=40)),
                ('mode', models.CharField(default='flat', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('value_min', models.IntegerField(blank=True, null=True)),
                ('value_max', models.IntegerField(blank=True, null=True)),
                ('formula', models.CharField(blank=True, default='', max_length=200)),
                ('scaling', models.JSONField(blank=True, default=dict)),
                ('stack_behavior', models.CharField(choices=[('stack', 'stack'), ('highest', 'highest'), ('lowest', 'lowest'), ('override', 'override'), ('unique_by_source', 'unique_by_source')], default='stack', max_length=40)),
                ('condition_set', models.JSONField(blank=True, default=dict)),
                ('active_flag', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('rules_text', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('internal', 'internal'), ('story', 'story')], default='public', max_length=20)),
                ('hidden', models.BooleanField(default=False)),
                ('sheet_relevant', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_effects', to='charsheet.trait')),
                ('target_choice_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semantic_effects', to='charsheet.traitchoicedefinition')),
            ],
            options={
                'ordering': ['trait', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TraitExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_by', to='charsheet.trait')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='charsheet.trait')),
            ],
            options={
                'ordering': ['trait__trait_type', 'trait__name', 'excluded_trait__name'],
            },
        ),
        migrations.AddField(
            model_name='trait',
            name='excluded_traits',
            field=models.ManyToManyField(blank=True, related_name='excluded_by_traits', through='charsheet.TraitExclusion', to='charsheet.trait'),
        ),
        migrations.AddConstraint(
            model_name='traitexclusion',
            constraint=models.UniqueConstraint(fields=('trait', 'excluded_trait'), name='uniq_trait_exclusion_direction'),
        ),
        migrations.AddField(
            model_name='traitchoicedefinition',
            name='allowed_proficiency_group',
            field=models.CharField(blank=True, choices=[('skill_fine_motor', 'Feinmotorische Fertigkeiten'), ('skill_gross_motor', 'Grobmotorische Fertigkeiten'), ('skill_social', 'Soziale Fertigkeiten'), ('skill_knowledge', 'Wissensfertigkeiten'), ('skill_combat', 'Waffenfertigkeiten'), ('foreign_languages', 'Sprachen (außer Muttersprache)')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='charactertraitchoice',
            name='selected_proficiency_group',
            field=models.CharField(blank=True, choices=[('skill_fine_motor', 'Feinmotorische Fertigkeiten'), ('skill_gross_motor', 'Grobmotorische Fertigkeiten'), ('skill_social', 'Soziale Fertigkeiten'), ('skill_knowledge', 'Wissensfertigkeiten'), ('skill_combat', 'Waffenfertigkeiten'), ('foreign_languages', 'Sprachen (außer Muttersprache)')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='charactertraitchoice',
            name='selected_derived_stat',
            field=models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arcane Power'), ('potential', 'Potential'), ('wound_stage', 'Wound Stage'), ('wound_penalty_ignore', 'Ignore Wound Penalty'), ('wound_penalty_mod', 'Wound Penalty Modifier'), ('armor_penalty_ignore', 'Ignore Armor Penalty'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='traitchoicedefinition',
            name='allowed_derived_stat',
            field=models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arcane Power'), ('potential', 'Potential'), ('wound_stage', 'Wound Stage'), ('wound_penalty_ignore', 'Ignore Wound Penalty'), ('wound_penalty_mod', 'Wound Penalty Modifier'), ('armor_penalty_ignore', 'Ignore Armor Penalty'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trait',
            name='points_by_level',
            field=models.CharField(blank=True, default='', help_text="Optional comma-separated per-level costs such as '1,3' or '2,4,6'. Overrides points_per_level.", max_length=200),
        ),
        migrations.AlterField(
            model_name='traitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity')], default='rule_flag', max_length=40),
        ),
        migrations.AddField(
            model_name='charactertraitchoice',
            name='selected_resource',
            field=models.CharField(blank=True, choices=[('personal_fame_point', 'Persönliche Ruhmpunkte'), ('personal_fame_rank', 'Persönlicher Rang'), ('artefact_rank', 'Artefaktrang'), ('sacrifice_rank', 'Opferrang')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='traitchoicedefinition',
            name='allowed_resource',
            field=models.CharField(blank=True, choices=[('personal_fame_point', 'Persönliche Ruhmpunkte'), ('personal_fame_rank', 'Persönlicher Rang'), ('artefact_rank', 'Artefaktrang'), ('sacrifice_rank', 'Opferrang')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='traitchoicedefinition',
            name='target_kind',
            field=models.CharField(choices=[('attribute', 'Attribute'), ('skill', 'Skill'), ('skill_category', 'Skill Category'), ('derived_stat', 'Derived Stat'), ('resource', 'Resource'), ('proficiency_group', 'Proficiency Group'), ('item', 'Item'), ('item_category', 'Item Category'), ('specialization', 'Specialization'), ('text', 'Free Text'), ('entity', 'Other Entity')], help_text='What kind of thing must be selected for this trait decision.', max_length=20),
        ),
        migrations.CreateModel(
            name='CharacterWeaponMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_order', models.PositiveSmallIntegerField(help_text='The order in which this concrete weapon was chosen on school levels 1-10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('first_bonus_kind', models.CharField(choices=[('maneuver', 'Manoever zuerst'), ('damage', 'Schaden zuerst')], default='maneuver', help_text='Whether the first granted point on this weapon went to maneuver or damage.', max_length=20)),
                ('learned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_masteries', to='charsheet.character')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_weapon_masteries', to='charsheet.school')),
                ('weapon_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_weapon_masteries', to='charsheet.item')),
            ],
            options={
                'ordering': ['character', 'school__name', 'pick_order', 'weapon_item__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('character', 'school', 'pick_order'), name='uniq_character_weapon_mastery_pick_order'), models.UniqueConstraint(fields=('character', 'school', 'weapon_item'), name='uniq_character_weapon_mastery_weapon')],
            },
        ),
        migrations.CreateModel(
            name='CharacterWeaponMasteryArcana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rune', 'Rune'), ('bonus_capacity', 'Bonuskapazitaet')], max_length=30)),
                ('learned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_mastery_arcana_entries', to='charsheet.character')),
                ('rune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weapon_mastery_arcana_entries', to='charsheet.rune')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_weapon_mastery_arcana_entries', to='charsheet.school')),
            ],
            options={
                'ordering': ['character', 'school__name', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('rune__isnull', False)), fields=('character', 'school', 'rune'), name='uniq_character_weapon_mastery_arcana_rune')],
            },
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='slug',
            field=models.SlugField(choices=[('school_magic', 'Magieschule'), ('school_divine', 'Klerikaler Aspekt'), ('school_combat', 'Kampfschule')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('armor', 'Rüstung'), ('weapon', 'Waffe'), ('shield', 'Schild'), ('clothing', 'Kleidung'), ('consumable', 'verbrauchbar'), ('ammo', 'Monition'), ('misc', 'Misc')], max_length=20),
        ),
        migrations.RunPython(
            code=add_clothing_items,
            reverse_code=remove_clothing_items,
        ),
        migrations.AddField(
            model_name='weaponstats',
            name='damage_flat_operator',
            field=models.CharField(blank=True, choices=[('', 'Kein Operator'), ('+', '+'), ('-', '-'), ('/', '/')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='weaponstats',
            name='h2_flat_operator',
            field=models.CharField(blank=True, choices=[('', 'Kein Operator'), ('+', '+'), ('-', '-'), ('/', '/')], default='', max_length=1),
        ),
        migrations.RunPython(
            code=normalize_weapon_bonus_operators,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='weaponstats',
            name='damage_bonus_attribute',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='weaponstats',
            name='damage_bonus_mode',
            field=models.CharField(blank=True, default='flat', max_length=20),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE charsheet_character                         ADD COLUMN IF NOT EXISTS current_arcane_power integer NULL',
                    reverse_sql='ALTER TABLE charsheet_character                         DROP COLUMN IF EXISTS current_arcane_power',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='character',
                    name='current_arcane_power',
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RunPython(
            code=sync_legacy_fullplate,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('armor', 'Rüstung'), ('weapon', 'Waffe'), ('shield', 'Schild'), ('clothing', 'Kleidung'), ('magic_item', 'Magischer Gegenstand'), ('consumable', 'verbrauchbar'), ('ammo', 'Monition'), ('misc', 'Misc')], max_length=20),
        ),
        migrations.CreateModel(
            name='MagicItemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_summary', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charsheet.item')),
            ],
        ),
        migrations.AddField(
            model_name='modifier',
            name='effect_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='is_magic',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=mark_existing_magic_items,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='character',
            name='current_arcane_power',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactertraitchoice',
            name='selected_derived_stat',
            field=models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arkane Macht'), ('potential', 'Potenzial'), ('wound_stage', 'Wundstufe'), ('wound_penalty_ignore', 'Wundmalus ignorieren'), ('wound_penalty_mod', 'Wundmalus verändern'), ('armor_penalty_ignore', 'Belastung ignorieren'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='traitchoicedefinition',
            name='allowed_derived_stat',
            field=models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arkane Macht'), ('potential', 'Potenzial'), ('wound_stage', 'Wundstufe'), ('wound_penalty_ignore', 'Wundmalus ignorieren'), ('wound_penalty_mod', 'Wundmalus verändern'), ('armor_penalty_ignore', 'Belastung ignorieren'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='is_magic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='magic_effect_summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rune',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Erlaubt, diese Rune mehrfach auf denselben Gegenstand anzuwenden.'),
        ),
        migrations.AddField(
            model_name='rune',
            name='has_specialization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rune',
            name='specialization_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CharacterItemRuneSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(blank=True, default='', max_length=100)),
                ('slot', models.PositiveSmallIntegerField(default=1, help_text='Slot-Nummer für mehrfach angewandte Runen (allow_multiple). Beginnt bei 1.')),
                ('character_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_specs', to='charsheet.characteritem')),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_item_specs', to='charsheet.rune')),
            ],
            options={
                'ordering': ['rune__name', 'slot'],
                'unique_together': {('character_item', 'rune', 'slot')},
            },
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='slug',
            field=models.SlugField(choices=[('arcane', 'Magieschule'), ('divine', 'Klerikale Schule'), ('combat', 'Kampfschule')], max_length=100, unique=True),
        ),
        migrations.RunPython(
            code=migrate_school_type_slugs,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('opposite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposed_by', to='charsheet.aspect')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSpellSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('trait', 'Trait'), ('admin', 'Admin'), ('manual', 'Manual')], default='trait', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_bonus_sources', to='charsheet.character')),
                ('trait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_spell_sources', to='charsheet.trait')),
            ],
            options={
                'ordering': ['character', 'source_kind', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DivineEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('entity_kind', models.CharField(choices=[('god', 'God'), ('ancestor', 'Ancestor Spirit'), ('totem', 'Totem / Power Animal')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(help_text='The divine school through which this entity is worshipped.', on_delete=django.db.models.deletion.CASCADE, related_name='divine_entities', to='charsheet.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('is_base_spell', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('kp_cost', models.PositiveSmallIntegerField(default=0)),
                ('cast_time', models.CharField(blank=True, default='', max_length=100)),
                ('range_text', models.CharField(blank=True, default='', max_length=100)),
                ('duration_text', models.CharField(blank=True, default='', max_length=100)),
                ('resistance_text', models.CharField(blank=True, default='', max_length=100)),
                ('attribute', models.CharField(blank=True, default='', max_length=30)),
                ('aspect', models.ForeignKey(blank=True, help_text='Used for divine spells.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='charsheet.aspect')),
                ('school', models.ForeignKey(blank=True, help_text='Used for arcane spells.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='charsheet.school')),
            ],
            options={
                'ordering': ['school__name', 'aspect__name', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('arcane_free', 'Arcane Free Choice'), ('arcane_extra', 'Arcane Extra Spell'), ('arcane_bonus', 'Arcane Bonus Spell'), ('divine_granted', 'Divine Granted'), ('divine_extra', 'Divine Extra Spell'), ('divine_bonus', 'Divine Bonus Spell'), ('base', 'Base Spell'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('learned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='charsheet.character')),
                ('bonus_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_spells', to='charsheet.characterspellsource')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_entries', to='charsheet.spell')),
            ],
            options={
                'ordering': ['character', 'spell__name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterDivineEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divine_entity_binding', to='charsheet.character')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followers', to='charsheet.divineentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character',), name='uniq_character_divine_entity')],
            },
        ),
        migrations.CreateModel(
            name='CharacterAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_bonus_aspect', models.BooleanField(default=False, help_text='True if this aspect was purchased separately instead of granted by entity.')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_entries', to='charsheet.aspect')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_entries', to='charsheet.character')),
                ('source_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_character_aspects', to='charsheet.divineentity')),
            ],
            options={
                'ordering': ['character', 'aspect__name'],
                'constraints': [models.UniqueConstraint(fields=('character', 'aspect'), name='uniq_character_aspect')],
            },
        ),
        migrations.CreateModel(
            name='DivineEntityAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting_aspect', models.BooleanField(default=True, help_text='Marks one of the default aspects granted by the entity.')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divine_entities', to='charsheet.aspect')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='charsheet.divineentity')),
            ],
            options={
                'ordering': ['entity__name', 'aspect__name'],
                'constraints': [models.UniqueConstraint(fields=('entity', 'aspect'), name='uniq_divine_entity_aspect')],
            },
        ),
        migrations.AddConstraint(
            model_name='spell',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('school', 'slug'), name='uniq_spell_school_slug'),
        ),
        migrations.AddConstraint(
            model_name='spell',
            constraint=models.UniqueConstraint(condition=models.Q(('aspect__isnull', False)), fields=('aspect', 'slug'), name='uniq_spell_aspect_slug'),
        ),
        migrations.AddConstraint(
            model_name='characterspell',
            constraint=models.UniqueConstraint(fields=('character', 'spell'), name='uniq_character_spell'),
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['school__name', 'aspect__name', 'grade', 'name']},
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='level',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spells', to='charsheet.attribute'),
        ),
        migrations.RemoveField(
            model_name='spell',
            name='attribute',
        ),
        migrations.AddField(
            model_name='spell',
            name='grade_adds_school_level',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, berechnet sich der effektive Grad als Grad + aktuelle Schulstufe des Charakters. Z.B. Grad 2 bei Schulstufe 3 = effektiver Grad 5.'),
        ),
        migrations.AddField(
            model_name='spell',
            name='panel_badge_label',
            field=models.CharField(blank=True, default='Zauber', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='panel_symbol',
            field=models.CharField(blank=True, default='', help_text='Optional short symbol shown in spell and school panels, for example a rune or glyph.', max_length=8),
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='resistance_text',
            new_name='resistance_value',
        ),
        migrations.AlterField(
            model_name='spell',
            name='resistance_value',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Widerstandswert'),
        ),
        migrations.AddField(
            model_name='spell',
            name='mw',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='MW'),
        ),
    ]
