# Generated by Django 5.2.11 on 2026-04-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0082_trait_choice_definitions_and_semantic_effect_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraitExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excluded_trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_by",
                        to="charsheet.trait",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="charsheet.trait",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "trait__trait_type",
                    "trait__name",
                    "excluded_trait__name",
                ],
            },
        ),
        migrations.AddField(
            model_name="trait",
            name="excluded_traits",
            field=models.ManyToManyField(
                blank=True,
                related_name="excluded_by_traits",
                through="charsheet.TraitExclusion",
                to="charsheet.trait",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitexclusion",
            constraint=models.UniqueConstraint(
                fields=("trait", "excluded_trait"),
                name="uniq_trait_exclusion_direction",
            ),
        ),
    ]
