# Generated by Django 5.2.11 on 2026-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0086_trait_proficiency_group_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactertraitchoice",
            name="selected_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arcane Power"),
                    ("potential", "Potential"),
                    ("wound_stage", "Wound Stage"),
                    ("wound_penalty_ignore", "Ignore Wound Penalty"),
                    ("wound_penalty_mod", "Wound Penalty Modifier"),
                    ("armor_penalty_ignore", "Ignore Armor Penalty"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="traitchoicedefinition",
            name="allowed_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arcane Power"),
                    ("potential", "Potential"),
                    ("wound_stage", "Wound Stage"),
                    ("wound_penalty_ignore", "Ignore Wound Penalty"),
                    ("wound_penalty_mod", "Wound Penalty Modifier"),
                    ("armor_penalty_ignore", "Ignore Armor Penalty"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="traitchoicedefinition",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("attribute", "Attribute"),
                    ("skill", "Skill"),
                    ("skill_category", "Skill Category"),
                    ("derived_stat", "Derived Stat"),
                    ("proficiency_group", "Proficiency Group"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("text", "Free Text"),
                    ("entity", "Other Entity"),
                ],
                help_text="What kind of thing must be selected for this trait decision.",
                max_length=20,
            ),
        ),
    ]
