# Generated by Django 5.2.11 on 2026-04-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0087_charactertraitchoice_selected_derived_stat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="points_by_level",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional comma-separated per-level costs such as '1,3' or '2,4,6'. Overrides points_per_level.",
                max_length=200,
            ),
        ),
    ]
