# Generated by Django 5.2.11 on 2026-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0089_alter_traitsemanticeffect_target_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactertraitchoice",
            name="selected_resource",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal_fame_point", "Persönliche Ruhmpunkte"),
                    ("personal_fame_rank", "Persönlicher Rang"),
                    ("artefact_rank", "Artefaktrang"),
                    ("sacrifice_rank", "Opferrang"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="traitchoicedefinition",
            name="allowed_resource",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal_fame_point", "Persönliche Ruhmpunkte"),
                    ("personal_fame_rank", "Persönlicher Rang"),
                    ("artefact_rank", "Artefaktrang"),
                    ("sacrifice_rank", "Opferrang"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="traitchoicedefinition",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("attribute", "Attribute"),
                    ("skill", "Skill"),
                    ("skill_category", "Skill Category"),
                    ("derived_stat", "Derived Stat"),
                    ("resource", "Resource"),
                    ("proficiency_group", "Proficiency Group"),
                    ("item", "Item"),
                    ("item_category", "Item Category"),
                    ("specialization", "Specialization"),
                    ("text", "Free Text"),
                    ("entity", "Other Entity"),
                ],
                help_text="What kind of thing must be selected for this trait decision.",
                max_length=20,
            ),
        ),
    ]
