# Generated by Django 5.2.11 on 2026-04-07 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0090_charactertraitchoice_selected_resource_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterWeaponMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pick_order",
                    models.PositiveSmallIntegerField(
                        help_text="The order in which this concrete weapon was chosen on school levels 1-10.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "first_bonus_kind",
                    models.CharField(
                        choices=[
                            ("maneuver", "Manoever zuerst"),
                            ("damage", "Schaden zuerst"),
                        ],
                        default="maneuver",
                        help_text="Whether the first granted point on this weapon went to maneuver or damage.",
                        max_length=20,
                    ),
                ),
                ("learned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapon_masteries",
                        to="charsheet.character",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_weapon_masteries",
                        to="charsheet.school",
                    ),
                ),
                (
                    "weapon_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_weapon_masteries",
                        to="charsheet.item",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "character",
                    "school__name",
                    "pick_order",
                    "weapon_item__name",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "school", "pick_order"),
                        name="uniq_character_weapon_mastery_pick_order",
                    ),
                    models.UniqueConstraint(
                        fields=("character", "school", "weapon_item"),
                        name="uniq_character_weapon_mastery_weapon",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterWeaponMasteryArcana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rune", "Rune"),
                            ("bonus_capacity", "Bonuskapazitaet"),
                        ],
                        max_length=30,
                    ),
                ),
                ("learned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapon_mastery_arcana_entries",
                        to="charsheet.character",
                    ),
                ),
                (
                    "rune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weapon_mastery_arcana_entries",
                        to="charsheet.rune",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_weapon_mastery_arcana_entries",
                        to="charsheet.school",
                    ),
                ),
            ],
            options={
                "ordering": ["character", "school__name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("rune__isnull", False)),
                        fields=("character", "school", "rune"),
                        name="uniq_character_weapon_mastery_arcana_rune",
                    )
                ],
            },
        ),
    ]
