# Generated by Django 5.2.11 on 2026-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0091_characterweaponmastery_characterweaponmasteryarcana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooltype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("school_magic", "Magieschule"),
                    ("school_divine", "Klerikaler Aspekt"),
                    ("school_combat", "Kampfschule"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
