# Generated by Django 5.2.11 on 2026-04-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0098_fix_legacy_fullplate_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("armor", "Rüstung"),
                    ("weapon", "Waffe"),
                    ("shield", "Schild"),
                    ("clothing", "Kleidung"),
                    ("magic_item", "Magischer Gegenstand"),
                    ("consumable", "verbrauchbar"),
                    ("ammo", "Monition"),
                    ("misc", "Misc"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MagicItemStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="charsheet.item"
                    ),
                ),
            ],
        ),
    ]
