# Generated by Django 5.2.11 on 2026-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0101_item_is_magic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="current_arcane_power",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="charactertraitchoice",
            name="selected_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arkane Macht"),
                    ("potential", "Potenzial"),
                    ("wound_stage", "Wundstufe"),
                    ("wound_penalty_ignore", "Wundmalus ignorieren"),
                    ("wound_penalty_mod", "Wundmalus verändern"),
                    ("armor_penalty_ignore", "Belastung ignorieren"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="traitchoicedefinition",
            name="allowed_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arkane Macht"),
                    ("potential", "Potenzial"),
                    ("wound_stage", "Wundstufe"),
                    ("wound_penalty_ignore", "Wundmalus ignorieren"),
                    ("wound_penalty_mod", "Wundmalus verändern"),
                    ("armor_penalty_ignore", "Belastung ignorieren"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
