# Generated by Django 5.2.11 on 2026-04-13 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0104_characteritem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="rune",
            name="allow_multiple",
            field=models.BooleanField(
                default=False,
                help_text="Erlaubt, diese Rune mehrfach auf denselben Gegenstand anzuwenden.",
            ),
        ),
        migrations.AddField(
            model_name="rune",
            name="has_specialization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rune",
            name="specialization_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="CharacterItemRuneSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Slot-Nummer für mehrfach angewandte Runen (allow_multiple). Beginnt bei 1.",
                    ),
                ),
                (
                    "character_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rune_specs",
                        to="charsheet.characteritem",
                    ),
                ),
                (
                    "rune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_item_specs",
                        to="charsheet.rune",
                    ),
                ),
            ],
            options={
                "ordering": ["rune__name", "slot"],
                "unique_together": {("character_item", "rune", "slot")},
            },
        ),
    ]
