# Generated by Django 5.2.11 on 2026-04-17 13:09

import django.db.models.deletion
from django.db import migrations, models


def migrate_school_type_slugs(apps, schema_editor):
    SchoolType = apps.get_model("charsheet", "SchoolType")
    slug_map = {
        "school_magic": "arcane",
        "school_divine": "divine",
        "school_combat": "combat",
    }
    for old_slug, new_slug in slug_map.items():
        SchoolType.objects.filter(slug=old_slug).update(slug=new_slug)

    defaults_by_slug = {
        "arcane": "Magieschule",
        "divine": "Klerikale Schule",
        "combat": "Kampfschule",
    }
    for slug, name in defaults_by_slug.items():
        SchoolType.objects.get_or_create(slug=slug, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0105_rune_spec_and_allow_multiple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooltype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("arcane", "Magieschule"),
                    ("divine", "Klerikale Schule"),
                    ("combat", "Kampfschule"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.RunPython(migrate_school_type_slugs, migrations.RunPython.noop),
        migrations.CreateModel(
            name="Aspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "opposite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opposed_by",
                        to="charsheet.aspect",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterSpellSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("trait", "Trait"),
                            ("admin", "Admin"),
                            ("manual", "Manual"),
                        ],
                        default="trait",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("capacity", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_bonus_sources",
                        to="charsheet.character",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="character_spell_sources",
                        to="charsheet.trait",
                    ),
                ),
            ],
            options={
                "ordering": ["character", "source_kind", "label", "id"],
            },
        ),
        migrations.CreateModel(
            name="DivineEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "entity_kind",
                    models.CharField(
                        choices=[
                            ("god", "God"),
                            ("ancestor", "Ancestor Spirit"),
                            ("totem", "Totem / Power Animal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "school",
                    models.ForeignKey(
                        help_text="The divine school through which this entity is worshipped.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divine_entities",
                        to="charsheet.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("level", models.PositiveSmallIntegerField()),
                ("is_base_spell", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                ("kp_cost", models.PositiveSmallIntegerField(default=0)),
                ("cast_time", models.CharField(blank=True, default="", max_length=100)),
                (
                    "range_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "duration_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "resistance_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("attribute", models.CharField(blank=True, default="", max_length=30)),
                (
                    "aspect",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used for divine spells.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spells",
                        to="charsheet.aspect",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used for arcane spells.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spells",
                        to="charsheet.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school__name", "aspect__name", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("arcane_free", "Arcane Free Choice"),
                            ("arcane_extra", "Arcane Extra Spell"),
                            ("arcane_bonus", "Arcane Bonus Spell"),
                            ("divine_granted", "Divine Granted"),
                            ("divine_extra", "Divine Extra Spell"),
                            ("divine_bonus", "Divine Bonus Spell"),
                            ("base", "Base Spell"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("learned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_spells",
                        to="charsheet.character",
                    ),
                ),
                (
                    "bonus_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_spells",
                        to="charsheet.characterspellsource",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_entries",
                        to="charsheet.spell",
                    ),
                ),
            ],
            options={
                "ordering": ["character", "spell__name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterDivineEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divine_entity_binding",
                        to="charsheet.character",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="followers",
                        to="charsheet.divineentity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character",), name="uniq_character_divine_entity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "is_bonus_aspect",
                    models.BooleanField(
                        default=False,
                        help_text="True if this aspect was purchased separately instead of granted by entity.",
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_entries",
                        to="charsheet.aspect",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspect_entries",
                        to="charsheet.character",
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_character_aspects",
                        to="charsheet.divineentity",
                    ),
                ),
            ],
            options={
                "ordering": ["character", "aspect__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "aspect"), name="uniq_character_aspect"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DivineEntityAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_starting_aspect",
                    models.BooleanField(
                        default=True,
                        help_text="Marks one of the default aspects granted by the entity.",
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divine_entities",
                        to="charsheet.aspect",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="charsheet.divineentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity__name", "aspect__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "aspect"), name="uniq_divine_entity_aspect"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="spell",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", False)),
                fields=("school", "slug"),
                name="uniq_spell_school_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="spell",
            constraint=models.UniqueConstraint(
                condition=models.Q(("aspect__isnull", False)),
                fields=("aspect", "slug"),
                name="uniq_spell_aspect_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterspell",
            constraint=models.UniqueConstraint(
                fields=("character", "spell"), name="uniq_character_spell"
            ),
        ),
    ]
