# Generated by Django 5.2.11 on 2026-04-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0106_alter_schooltype_slug_aspect_characterspellsource_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spell",
            options={"ordering": ["school__name", "aspect__name", "grade", "name"]},
        ),
        migrations.RenameField(
            model_name="spell",
            old_name="level",
            new_name="grade",
        ),
        migrations.AddField(
            model_name="spell",
            name="spell_attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spells",
                to="charsheet.attribute",
            ),
        ),
    ]
