# Generated by Django 5.2.11 on 2026-04-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0107_alter_spell_options_rename_level_spell_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spell",
            name="attribute",
        ),
    ]
