# Generated by Django 5.2.11 on 2026-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0108_remove_spell_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="grade_adds_school_level",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiv, berechnet sich der effektive Grad als Grad + aktuelle Schulstufe des Charakters. Z.B. Grad 2 bei Schulstufe 3 = effektiver Grad 5.",
            ),
        ),
    ]
