# Generated by Django 5.2.11 on 2026-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0080_squashed_0112"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="range_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Reichweite"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="range_per_grade",
            field=models.BooleanField(default=False, verbose_name="pro Stufe"),
        ),
        migrations.AddField(
            model_name="spell",
            name="range_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Meter"),
                    ("km", "Kilometer"),
                    ("Berührung", "Berührung"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit",
            ),
        ),
    ]
