# Generated by Django 5.2.11 on 2026-04-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0113_range_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="range_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Meter"),
                    ("km", "Kilometer"),
                    ("Berührung", "Berührung"),
                    ("selbst", "Selbst"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit",
            ),
        ),
    ]
