# Generated by Django 5.2.11 on 2026-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0114_alter_spell_range_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="cast_time_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Zeitaufwand"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="cast_time_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aktion", "Aktion"),
                    ("Minute", "Minute"),
                    ("Stunde", "Stunde"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit",
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="duration_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Wirkungsdauer"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="duration_per_grade",
            field=models.BooleanField(default=False, verbose_name="pro Stufe"),
        ),
        migrations.AddField(
            model_name="spell",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sofort", "Sofort"),
                    ("Runde", "Runde"),
                    ("permanent", "Permanent"),
                    ("Stunde", "Stunde"),
                    ("Minute", "Minute"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit",
            ),
        ),
    ]
