# Generated by Django 5.2.11 on 2026-04-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0116_alter_spell_duration_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="duration2_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Wirkungsdauer 2"
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="duration2_per_grade",
            field=models.BooleanField(default=False, verbose_name="pro Stufe"),
        ),
        migrations.AddField(
            model_name="spell",
            name="duration2_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sofort", "Sofort"),
                    ("Runde", "Runde"),
                    ("Szene", "Szene"),
                    ("permanent", "Permanent"),
                    ("Stunde", "Stunde"),
                    ("Minute", "Minute"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit 2",
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="ep_cost",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="EP-Kosten"
            ),
        ),
    ]
