# Generated by Django 5.2.11 on 2026-04-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0117_spell_duration2_ep_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="duration2_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sofort", "Sofort"),
                    ("Runde", "Runde"),
                    ("Szene", "Szene"),
                    ("Konzentration", "Konzentration"),
                    ("permanent", "Permanent"),
                    ("Stunde", "Stunde"),
                    ("Minute", "Minute"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit 2",
            ),
        ),
        migrations.AlterField(
            model_name="spell",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sofort", "Sofort"),
                    ("Runde", "Runde"),
                    ("Szene", "Szene"),
                    ("Konzentration", "Konzentration"),
                    ("permanent", "Permanent"),
                    ("Stunde", "Stunde"),
                    ("Minute", "Minute"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit",
            ),
        ),
    ]
