# Generated by Django 5.2.11 on 2026-04-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0118_alter_spell_duration2_unit_alter_spell_duration_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="max_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Maximale lernbare Stufe. Überschreibt den automatisch berechneten Wert aus den Techniken.",
                null=True,
                verbose_name="Max. Stufe",
            ),
        ),
    ]
