# Generated by Django 5.2.11 on 2026-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0119_school_max_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="kp_cost",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
