# Generated by Django 5.2.11 on 2026-04-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0125_spell_structured_extra_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spell",
            name="extra_cost",
        ),
    ]
