# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0131_alter_charactertraitchoice_selected_derived_stat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteritem",
            name="armor_encumbrance_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_min_st_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_rs_arm_left_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_rs_arm_right_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_rs_head_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_rs_leg_left_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_rs_leg_right_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_rs_torso_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="armor_rs_total_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="name_override",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="price_override",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="shield_encumbrance_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="shield_min_st_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="shield_rs_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="size_class_override",
            field=models.CharField(blank=True, choices=[("FF", "FF"), ("F", "F"), ("Winz", "Winz"), ("K", "K"), ("M", "M"), ("G", "G"), ("R", "R"), ("Gi", "Gi"), ("Kol", "Kol")], default="", max_length=5),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_damage_dice_amount_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_damage_dice_faces_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_damage_flat_bonus_override",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_damage_flat_operator_override",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_damage_source_override",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="character_item_weapon_overrides", to="charsheet.damagesource"),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_damage_type_override",
            field=models.CharField(blank=True, choices=[("B", "B"), ("T", "T")], default="", max_length=1),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_h2_dice_amount_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_h2_dice_faces_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_h2_flat_bonus_override",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_h2_flat_operator_override",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_min_st_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_wield_mode_override",
            field=models.CharField(blank=True, choices=[("1h", "EinhÃ¤ndig"), ("2h", "ZweihÃ¤ndig"), ("vh", "Ein- und ZweihÃ¤ndig")], default="", max_length=2),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weight_override",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
