# Generated by Django 5.2.11 on 2026-04-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0132_characteritem_value_overrides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteritem",
            name="size_class_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S"),
                    ("F", "F"),
                    ("W", "W"),
                    ("K", "K"),
                    ("M", "M"),
                    ("G", "G"),
                    ("R", "R"),
                    ("Gi", "Gi"),
                    ("Kol", "Kol"),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="characteritem",
            name="weapon_wield_mode_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1h", "Einhändig"),
                    ("2h", "Zweihändig"),
                    ("vh", "Ein- und Zweihändig"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
