# Generated by Django 5.2.11 on 2026-04-30 11:23

import django.db.models.deletion
from django.db import migrations, models


WEAPON_TYPE_UNSPECIFIED = ""


def classify_weapon_type(name: str) -> str:
    normalized = (name or "").strip().lower()
    if not normalized:
        return WEAPON_TYPE_UNSPECIFIED
    if "langschwert" in normalized or "breitschwert" in normalized or "bastardschwert" in normalized:
        return "longsword"
    if "zweihänder" in normalized or "zweihandkhopesh" in normalized or "zweihandkrummschwert" in normalized or "claymore" in normalized:
        return "two_handed_sword"
    if "kurzschwert" in normalized:
        return "shortsword"
    if "khopesh" in normalized or "krummschwert" in normalized or "säbel" in normalized:
        return "curved_sword"
    if "rapier" in normalized or "degen" in normalized or "florett" in normalized:
        return "rapier"
    if any(token in normalized for token in ("dolch", "messer", "stilett", "main gauche", "khatar")):
        return "dagger"
    if "zweihandstreitaxt" in normalized or "trollzweihandaxt" in normalized:
        return "two_handed_axe"
    if "axt" in normalized or "beil" in normalized:
        return "axe"
    if "zweihandkriegshammer" in normalized or "zweihandtrollkriegshammer" in normalized:
        return "two_handed_hammer"
    if "kriegshammer" in normalized or "hammer" in normalized:
        return "hammer"
    if "zweihandflegel" in normalized or "geißel" in normalized or "geissel" in normalized:
        return "flail"
    if "streitkolben" in normalized or "keule" in normalized or "knüppel" in normalized or "knueppel" in normalized or "totschläger" in normalized or "totschlaeger" in normalized or "morgenstern" in normalized:
        return "mace"
    if "turnierlanze" in normalized or "lanze" in normalized:
        return "lance"
    if "dreizack" in normalized or "speer" in normalized or "wurfspieß" in normalized or "wurfspiess" in normalized:
        return "spear"
    if any(token in normalized for token in ("hellebarde", "glefe", "pike", "berdyche", "kriegsgabel", "gaffel", "haken", "stangenaxt")):
        return "polearm"
    if "kampfstab" in normalized:
        return "staff"
    if "kette" in normalized or "mornabat" in normalized:
        return "chain"
    if "peitsche" in normalized or "lasso" in normalized:
        return "whip"
    if any(token in normalized for token in ("faust", "tritt", "cestus", "handschuh", "panzerschuh")):
        return "fist"
    if "armbrust" in normalized:
        return "crossbow"
    if "bogen" in normalized:
        return "bow"
    if "blasrohr" in normalized:
        return "blowgun"
    if any(token in normalized for token in ("netz", "fussangeln", "fangeisen", "spikes")):
        return "trap"
    return "special"


def populate_weapon_types(apps, schema_editor):
    WeaponStats = apps.get_model("charsheet", "WeaponStats")
    CharacterWeaponMastery = apps.get_model("charsheet", "CharacterWeaponMastery")

    for stats in WeaponStats.objects.select_related("item").all():
        weapon_type = classify_weapon_type(stats.item.name)
        if stats.weapon_type != weapon_type:
            stats.weapon_type = weapon_type
            stats.save(update_fields=["weapon_type"])

    for mastery in CharacterWeaponMastery.objects.select_related("weapon_item__weaponstats").all():
        weapon_type = WEAPON_TYPE_UNSPECIFIED
        if mastery.weapon_item_id:
            weapon_stats = getattr(mastery.weapon_item, "weaponstats", None)
            weapon_type = getattr(weapon_stats, "weapon_type", WEAPON_TYPE_UNSPECIFIED) or WEAPON_TYPE_UNSPECIFIED
            if not weapon_type:
                weapon_type = classify_weapon_type(mastery.weapon_item.name)
        mastery.weapon_type = weapon_type
        mastery.save(update_fields=["weapon_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0133_alter_characteritem_size_class_override_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterweaponmastery",
            options={
                "ordering": [
                    "character",
                    "school__name",
                    "pick_order",
                    "weapon_type",
                    "id",
                ]
            },
        ),
        migrations.RemoveConstraint(
            model_name="characterweaponmastery",
            name="uniq_character_weapon_mastery_weapon",
        ),
        migrations.AddField(
            model_name="characterweaponmastery",
            name="weapon_type",
            field=models.CharField(
                choices=[
                    ("", "Nicht festgelegt"),
                    ("longsword", "Langschwert"),
                    ("two_handed_sword", "Zweihandschwert"),
                    ("shortsword", "Kurzschwert"),
                    ("curved_sword", "Krummschwert"),
                    ("rapier", "Degen / Rapier"),
                    ("dagger", "Dolch"),
                    ("axe", "Axt"),
                    ("two_handed_axe", "Zweihandaxt"),
                    ("hammer", "Hammer"),
                    ("two_handed_hammer", "Zweihandhammer"),
                    ("mace", "Kolben / Keule"),
                    ("flail", "Flegel / Geissel"),
                    ("spear", "Speer"),
                    ("lance", "Lanze"),
                    ("polearm", "Stangenwaffe"),
                    ("staff", "Stab"),
                    ("chain", "Kettenwaffe"),
                    ("whip", "Peitsche"),
                    ("fist", "Faustwaffe / Unbewaffnet"),
                    ("bow", "Bogen"),
                    ("crossbow", "Armbrust"),
                    ("blowgun", "Blasrohr"),
                    ("trap", "Netz / Falle"),
                    ("special", "Sonderwaffe"),
                ],
                default="",
                help_text="Der regeltechnische Waffentyp, auf den diese Meisterschaft wirkt.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="weaponstats",
            name="weapon_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nicht festgelegt"),
                    ("longsword", "Langschwert"),
                    ("two_handed_sword", "Zweihandschwert"),
                    ("shortsword", "Kurzschwert"),
                    ("curved_sword", "Krummschwert"),
                    ("rapier", "Degen / Rapier"),
                    ("dagger", "Dolch"),
                    ("axe", "Axt"),
                    ("two_handed_axe", "Zweihandaxt"),
                    ("hammer", "Hammer"),
                    ("two_handed_hammer", "Zweihandhammer"),
                    ("mace", "Kolben / Keule"),
                    ("flail", "Flegel / Geissel"),
                    ("spear", "Speer"),
                    ("lance", "Lanze"),
                    ("polearm", "Stangenwaffe"),
                    ("staff", "Stab"),
                    ("chain", "Kettenwaffe"),
                    ("whip", "Peitsche"),
                    ("fist", "Faustwaffe / Unbewaffnet"),
                    ("bow", "Bogen"),
                    ("crossbow", "Armbrust"),
                    ("blowgun", "Blasrohr"),
                    ("trap", "Netz / Falle"),
                    ("special", "Sonderwaffe"),
                ],
                default="",
                help_text="Regeltechnischer Waffentyp fuer Waffenmeister und aehnliche Effekte.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="characterweaponmastery",
            name="weapon_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_weapon_masteries",
                to="charsheet.item",
            ),
        ),
        migrations.RunPython(populate_weapon_types, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="characterweaponmastery",
            constraint=models.UniqueConstraint(
                fields=("character", "school", "weapon_type"),
                name="uniq_character_weapon_mastery_weapon_type",
            ),
        ),
    ]
