# Generated by Django 5.2.11 on 2026-04-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0134_alter_characterweaponmastery_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterweaponmastery",
            name="weapon_type",
            field=models.CharField(
                choices=[
                    ("", "Nicht festgelegt"),
                    ("longsword", "Langschwert"),
                    ("two_handed_sword", "Zweihandschwert"),
                    ("shortsword", "Kurzschwert"),
                    ("curved_sword", "Krummschwert"),
                    ("short_curved", "Kurzkrummschwet"),
                    ("rapier", "Degen / Rapier"),
                    ("dagger", "Dolch"),
                    ("axe", "Axt"),
                    ("two_handed_axe", "Zweihandaxt"),
                    ("hammer", "Hammer"),
                    ("two_handed_hammer", "Zweihandhammer"),
                    ("mace", "Kolben / Keule"),
                    ("flail", "Flegel / Geissel"),
                    ("spear", "Speer"),
                    ("lance", "Lanze"),
                    ("polearm", "Stangenwaffe"),
                    ("staff", "Stab"),
                    ("chain", "Kettenwaffe"),
                    ("whip", "Peitsche"),
                    ("fist", "Faustwaffe / Unbewaffnet"),
                    ("bow", "Bogen"),
                    ("crossbow", "Armbrust"),
                    ("blowgun", "Blasrohr"),
                    ("trap", "Netz / Falle"),
                    ("special", "Sonderwaffe"),
                ],
                default="",
                help_text="Der regeltechnische Waffentyp, auf den diese Meisterschaft wirkt.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="weaponstats",
            name="weapon_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nicht festgelegt"),
                    ("longsword", "Langschwert"),
                    ("two_handed_sword", "Zweihandschwert"),
                    ("shortsword", "Kurzschwert"),
                    ("curved_sword", "Krummschwert"),
                    ("short_curved", "Kurzkrummschwet"),
                    ("rapier", "Degen / Rapier"),
                    ("dagger", "Dolch"),
                    ("axe", "Axt"),
                    ("two_handed_axe", "Zweihandaxt"),
                    ("hammer", "Hammer"),
                    ("two_handed_hammer", "Zweihandhammer"),
                    ("mace", "Kolben / Keule"),
                    ("flail", "Flegel / Geissel"),
                    ("spear", "Speer"),
                    ("lance", "Lanze"),
                    ("polearm", "Stangenwaffe"),
                    ("staff", "Stab"),
                    ("chain", "Kettenwaffe"),
                    ("whip", "Peitsche"),
                    ("fist", "Faustwaffe / Unbewaffnet"),
                    ("bow", "Bogen"),
                    ("crossbow", "Armbrust"),
                    ("blowgun", "Blasrohr"),
                    ("trap", "Netz / Falle"),
                    ("special", "Sonderwaffe"),
                ],
                default="",
                help_text="Regeltechnischer Waffentyp fuer Waffenmeister und aehnliche Effekte.",
                max_length=30,
            ),
        ),
    ]
