# Generated by Django 5.2.11 on 2026-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0135_alter_characterweaponmastery_weapon_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteritem",
            name="weapon_type_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nicht festgelegt"),
                    ("longsword", "Langschwert"),
                    ("two_handed_sword", "Zweihandschwert"),
                    ("shortsword", "Kurzschwert"),
                    ("curved_sword", "Krummschwert"),
                    ("short_curved", "Kurzkrummschwet"),
                    ("rapier", "Degen / Rapier"),
                    ("dagger", "Dolch"),
                    ("axe", "Axt"),
                    ("two_handed_axe", "Zweihandaxt"),
                    ("hammer", "Hammer"),
                    ("two_handed_hammer", "Zweihandhammer"),
                    ("mace", "Kolben / Keule"),
                    ("flail", "Flegel / Geissel"),
                    ("spear", "Speer"),
                    ("lance", "Lanze"),
                    ("polearm", "Stangenwaffe"),
                    ("staff", "Stab"),
                    ("chain", "Kettenwaffe"),
                    ("whip", "Peitsche"),
                    ("fist", "Faustwaffe / Unbewaffnet"),
                    ("bow", "Bogen"),
                    ("crossbow", "Armbrust"),
                    ("blowgun", "Blasrohr"),
                    ("trap", "Netz / Falle"),
                    ("special", "Sonderwaffe"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="charactertraitchoice",
            name="selected_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arkane Macht"),
                    ("potential", "Potenzial"),
                    ("wound_stage", "Wundstufe"),
                    ("wound_penalty_ignore", "Wundmalus ignorieren"),
                    ("wound_penalty_mod", "Wundmalus verändern"),
                    ("armor_penalty_ignore", "Belastung ignorieren"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                    ("melee_maneuvers", "Manöver mit dieser Waffe"),
                    ("weapon_damage", "Schaden mit dieser Waffe"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="traitchoicedefinition",
            name="allowed_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arkane Macht"),
                    ("potential", "Potenzial"),
                    ("wound_stage", "Wundstufe"),
                    ("wound_penalty_ignore", "Wundmalus ignorieren"),
                    ("wound_penalty_mod", "Wundmalus verändern"),
                    ("armor_penalty_ignore", "Belastung ignorieren"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                    ("melee_maneuvers", "Manöver mit dieser Waffe"),
                    ("weapon_damage", "Schaden mit dieser Waffe"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
