# Generated by Django 5.2.11 on 2026-05-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0137_weapontype_fk_migration",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterweaponmastery",
            options={
                "ordering": [
                    "character",
                    "school__name",
                    "pick_order",
                    "weapon_type__name",
                    "id",
                ]
            },
        ),
    ]
