# Generated by Django 5.2.11 on 2026-05-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0143_characteritem_image_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactertraitchoice",
            name="selected_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arkane Macht"),
                    ("potential", "Potenzial"),
                    ("wound_stage", "Wundstufe"),
                    ("wound_penalty_ignore", "Wundmalus ignorieren"),
                    ("wound_penalty_mod", "Wundmalus verändern"),
                    ("armor_penalty_ignore", "Belastung ignorieren"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                    ("melee_maneuvers", "Manöver mit dieser Waffe"),
                    ("weapon_damage", "Schaden mit dieser Waffe"),
                    (
                        "weapon_damage_dice",
                        "Zusaetzliche Schadenswuerfel mit dieser Waffe",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="traitchoicedefinition",
            name="allowed_derived_stat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiative", "Initiative"),
                    ("arcane_power", "Arkane Macht"),
                    ("potential", "Potenzial"),
                    ("wound_stage", "Wundstufe"),
                    ("wound_penalty_ignore", "Wundmalus ignorieren"),
                    ("wound_penalty_mod", "Wundmalus verändern"),
                    ("armor_penalty_ignore", "Belastung ignorieren"),
                    ("vw", "VW"),
                    ("gw", "GW"),
                    ("sr", "SR"),
                    ("rs", "RS"),
                    ("melee_maneuvers", "Manöver mit dieser Waffe"),
                    ("weapon_damage", "Schaden mit dieser Waffe"),
                    (
                        "weapon_damage_dice",
                        "Zusaetzliche Schadenswuerfel mit dieser Waffe",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
