# Generated by Django 5.2.11 on 2026-05-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0146_characteritem_stored"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="not_buyable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="not_sellable",
            field=models.BooleanField(default=False),
        ),
    ]
