# Generated by Django 5.2.11 on 2026-05-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0153_usersettings_sidebar_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="char_picture",
            field=models.ImageField(blank=True, null=True, upload_to="characters/"),
        ),
    ]
