# Generated by Django 5.2.11 on 2026-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0154_character_char_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="appearance",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
