# Generated by Django 5.2.11 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0155_alter_character_appearance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="cast_time_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aktion", "Aktion"),
                    ("Runde", "Runde"),
                    ("Minute", "Minute"),
                    ("Stunde", "Stunde"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit",
            ),
        ),
        migrations.AlterField(
            model_name="spell",
            name="cast_time2_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aktion", "Aktion"),
                    ("Runde", "Runde"),
                    ("Minute", "Minute"),
                    ("Stunde", "Stunde"),
                ],
                default="",
                max_length=20,
                verbose_name="Einheit 2",
            ),
        ),
    ]
