# Generated by Django 5.2.11 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0156_alter_spell_cast_time_units_add_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="symbol_image",
            field=models.ImageField(
                blank=True,
                help_text="Optionales Symbolbild fuer diese Schule. Wird im Charsheet bevorzugt vor dem Textsymbol angezeigt.",
                null=True,
                upload_to="schools/",
            ),
        ),
    ]
