# Generated by Django 5.2.11 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0157_school_symbol_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="grade_adds_level",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiv, wird der Grad in Anzeigen als Grad + aktuelle Stufe dargestellt.",
                verbose_name="Grad + Stufe",
            ),
        ),
    ]
