# Generated by Django 5.2.11 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0158_spell_grade_adds_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="kp_cost_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="KP-Label",
            ),
        ),
    ]
