# Generated by Django 6.0.5 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0159_spell_kp_cost_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='divineentity',
            name='allies_and_enemies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='divine_function',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='doctrines',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='vow',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='worshippers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
