# Generated by Django 6.0.5 on 2026-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0160_divineentity_allies_and_enemies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='aspect_image',
            field=models.ImageField(blank=True, help_text='Optionales Symbolbild für diesen Aspekt.', null=True, upload_to='aspects/'),
        ),
    ]
