# Generated by Django 6.0.5 on 2026-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0161_aspect_aspect_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='divineentity',
            name='granted_abilities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
