# Generated by Django 6.0.5 on 2026-05-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0164_techniquesemanticeffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquesemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity')], default='skill', max_length=40),
        ),
        migrations.AlterField(
            model_name='traitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity')], default='rule_flag', max_length=40),
        ),
    ]
