# Generated by Django 6.0.5 on 2026-05-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0166_skill_rank_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquesemanticeffect',
            name='target_skills',
            field=models.ManyToManyField(blank=True, help_text='Optional concrete skill targets. Use this instead of target_key for multi-skill effects.', related_name='technique_semantic_effects', to='charsheet.skill'),
        ),
        migrations.AddField(
            model_name='traitsemanticeffect',
            name='target_skills',
            field=models.ManyToManyField(blank=True, help_text='Optional concrete skill targets. Use this instead of target_key for multi-skill effects.', related_name='trait_semantic_effects', to='charsheet.skill'),
        ),
    ]
