# Generated by Django 6.0.5 on 2026-06-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0167_semantic_effect_target_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='divineentity',
            name='card_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='g_ability',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='god_image',
            field=models.ImageField(blank=True, help_text='Optionales Karten-/Gottheitenbild fuer diese goettliche Entitaet.', null=True, upload_to='divine_entities/'),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='pantheon',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
