# Generated by Django 6.0.5 on 2026-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0168_divineentity_card_name_divineentity_g_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divineentity',
            name='vow_short',
            field=models.TextField(blank=True, default=''),
        ),
    ]
