# Generated by Django 6.0.5 on 2026-06-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0169_divineentity_vow_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divineentity',
            old_name='vow_short',
            new_name='fluff',
        ),
    ]
