# Generated by Django 6.0.5 on 2026-06-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0171_creature_charactercreature_charactercreatureitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureSpecialSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='creature_skills/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureSpecialSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_override', models.IntegerField()),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_skill_overrides', to='charsheet.charactercreature')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charsheet.creaturespecialskill')),
            ],
            options={
                'ordering': ['skill__name'],
                'constraints': [models.UniqueConstraint(fields=('creature', 'skill'), name='uniq_character_creature_special_skill')],
            },
        ),
        migrations.CreateModel(
            name='CreatureSpecialSkillValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_skills', to='charsheet.creature')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charsheet.creaturespecialskill')),
            ],
            options={
                'ordering': ['skill__name'],
                'constraints': [models.UniqueConstraint(fields=('creature', 'skill'), name='uniq_creature_special_skill')],
            },
        ),
    ]
