# Generated by Django 6.0.5 on 2026-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0173_alter_charactertraitchoice_selected_derived_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertraitchoice',
            name='selected_derived_stat',
            field=models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arkane Macht'), ('potential', 'Potenzial'), ('wound_stage', 'Wundstufe'), ('wound_penalty_mod', 'Wundmalus verändern'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS'), ('armor_encumbrance', 'Belastung dieser Rüstung'), ('shield_encumbrance', 'Belastung dieses Schilds'), ('melee_maneuvers', 'Manöver mit dieser Waffe'), ('weapon_damage', 'Schaden mit dieser Waffe'), ('weapon_damage_dice', 'Zusaetzliche Schadenswuerfel mit dieser Waffe')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='traitchoicedefinition',
            name='allowed_derived_stat',
            field=models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arkane Macht'), ('potential', 'Potenzial'), ('wound_stage', 'Wundstufe'), ('wound_penalty_mod', 'Wundmalus verändern'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS'), ('armor_encumbrance', 'Belastung dieser Rüstung'), ('shield_encumbrance', 'Belastung dieses Schilds'), ('melee_maneuvers', 'Manöver mit dieser Waffe'), ('weapon_damage', 'Schaden mit dieser Waffe'), ('weapon_damage_dice', 'Zusaetzliche Schadenswuerfel mit dieser Waffe')], default='', max_length=50),
        ),
    ]
