# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0174_alter_charactertraitchoice_selected_derived_stat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="ep_cost_label",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="EP-Label"),
        ),
    ]
