# Generated by Django 6.0.5 on 2026-06-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0177_spell_duration2_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraspect',
            name='source_binding',
            field=models.ForeignKey(blank=True, help_text='Character-specific divine or spirit binding that chose this aspect.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_aspects', to='charsheet.characterdivineentity'),
        ),
        migrations.AddField(
            model_name='characteraspect',
            name='source_school',
            field=models.ForeignKey(blank=True, help_text='School whose level drives this aspect, if it tracks a school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_character_aspects', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='characteraspect',
            name='tracks_school_level',
            field=models.BooleanField(default=False, help_text='If enabled, the aspect level is synchronized to source_school.'),
        ),
        migrations.AddField(
            model_name='characterdivineentity',
            name='core_aspects',
            field=models.ManyToManyField(blank=True, help_text='Character-specific core aspects, used by flexible spirit bindings such as shamanism.', related_name='character_divine_bindings', to='charsheet.aspect'),
        ),
        migrations.AddField(
            model_name='characterdivineentity',
            name='custom_description',
            field=models.TextField(blank=True, default='', help_text='Character-specific description, taboo, form, or tradition notes.'),
        ),
        migrations.AddField(
            model_name='characterdivineentity',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text="Personal name of this character's spirit or manifestation.", max_length=160),
        ),
        migrations.AddField(
            model_name='characterdivineentity',
            name='tradition_name',
            field=models.CharField(blank=True, default='', help_text='Optional cult, tribe, lineage, or local tradition name.', max_length=160),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='allows_custom_description',
            field=models.BooleanField(default=False, help_text='If enabled, character bindings may describe the personal manifestation.'),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='allows_custom_name',
            field=models.BooleanField(default=False, help_text='If enabled, character bindings may define a personal name for this entity.'),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='aspect_selection_mode',
            field=models.CharField(choices=[('fixed', 'Fixed aspects'), ('choose_from_entity', 'Choose from entity aspects'), ('free', 'Free aspect choice')], default='fixed', help_text="Controls whether character bindings use the entity's fixed aspects or may choose individual core aspects.", max_length=24),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='starting_aspect_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many core aspects this entity grants or lets the character choose.'),
        ),
        migrations.AlterField(
            model_name='divineentity',
            name='entity_kind',
            field=models.CharField(choices=[('god', 'God'), ('ancestor', 'Ancestor Spirit'), ('totem', 'Totem / Power Animal'), ('spirit', 'Spirit')], max_length=20),
        ),
    ]
