# Generated by Django 6.0.5 on 2026-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0178_characteraspect_source_binding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdivineentity',
            name='custom_god_image',
            field=models.ImageField(blank=True, help_text='Character-specific card image for this divine entity or spirit.', null=True, upload_to='character_divine_entities/'),
        ),
        migrations.AddField(
            model_name='divineentity',
            name='allows_custom_god_image',
            field=models.BooleanField(default=False, help_text='If enabled, character bindings may define a personal card image.'),
        ),
    ]
