# Generated by Codex on 2026-06-07

from django.db import migrations, models


def migrate_spirit_to_power_animal(apps, schema_editor):
    DivineEntity = apps.get_model("charsheet", "DivineEntity")
    DivineEntity.objects.filter(entity_kind="spirit").update(entity_kind="power_animal")


def migrate_power_animal_to_spirit(apps, schema_editor):
    DivineEntity = apps.get_model("charsheet", "DivineEntity")
    DivineEntity.objects.filter(entity_kind="power_animal").update(entity_kind="spirit")


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0180_characterdivineentity_card_text_overrides"),
    ]

    operations = [
        migrations.RunPython(migrate_spirit_to_power_animal, migrate_power_animal_to_spirit),
        migrations.AlterField(
            model_name="divineentity",
            name="entity_kind",
            field=models.CharField(
                choices=[
                    ("god", "God"),
                    ("totem", "Totem"),
                    ("power_animal", "Power Animal"),
                    ("ancestor", "Ancestor Spirit"),
                ],
                max_length=20,
            ),
        ),
    ]
