# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0181_divineentity_power_animal_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterdivineentity",
            name="custom_type_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Character-specific type label shown on the personal divine card.",
                max_length=80,
            ),
        ),
    ]
