# Generated by Django 6.0.5 on 2026-06-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0182_characterdivineentity_custom_type_label'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'charsheet_divineentity'
                            AND column_name = 'is_customizable'
                        ) THEN
                            NULL;
                        ELSE
                            ALTER TABLE charsheet_divineentity
                            ADD COLUMN is_customizable boolean NOT NULL DEFAULT false;
                        END IF;
                    END $$;

                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'charsheet_divineentity'
                            AND column_name = 'allows_custom_description'
                        ) THEN
                            UPDATE charsheet_divineentity
                            SET is_customizable = true
                            WHERE allows_custom_description = true
                               OR allows_custom_god_image = true
                               OR allows_custom_name = true;
                        END IF;
                    END $$;

                    ALTER TABLE charsheet_characterdivineentity
                    DROP COLUMN IF EXISTS custom_type_label;

                    ALTER TABLE charsheet_divineentity
                    DROP COLUMN IF EXISTS allows_custom_description;

                    ALTER TABLE charsheet_divineentity
                    DROP COLUMN IF EXISTS allows_custom_god_image;

                    ALTER TABLE charsheet_divineentity
                    DROP COLUMN IF EXISTS allows_custom_name;

                    ALTER TABLE charsheet_divineentity
                    DROP COLUMN IF EXISTS entity_kind;

                    CREATE TABLE IF NOT EXISTS charsheet_druidcult (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(120) NOT NULL UNIQUE,
                        slug varchar(120) NOT NULL UNIQUE,
                        description text NOT NULL,
                        school_id bigint NULL,
                        CONSTRAINT charsheet_druidcult_school_id_fk
                            FOREIGN KEY (school_id)
                            REFERENCES charsheet_school(id)
                            DEFERRABLE INITIALLY DEFERRED
                    );

                    CREATE TABLE IF NOT EXISTS charsheet_shamancult (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(120) NOT NULL UNIQUE,
                        slug varchar(120) NOT NULL UNIQUE,
                        cult_kind varchar(20) NOT NULL,
                        description text NOT NULL,
                        school_id bigint NULL,
                        CONSTRAINT charsheet_shamancult_school_id_fk
                            FOREIGN KEY (school_id)
                            REFERENCES charsheet_school(id)
                            DEFERRABLE INITIALLY DEFERRED
                    );

                    CREATE TABLE IF NOT EXISTS charsheet_characterdruidcult (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        character_id bigint NOT NULL UNIQUE,
                        cult_id bigint NOT NULL,
                        CONSTRAINT uniq_character_druid_cult
                            UNIQUE (character_id),
                        CONSTRAINT charsheet_characterdruidcult_character_id_fk
                            FOREIGN KEY (character_id)
                            REFERENCES charsheet_character(id)
                            DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT charsheet_characterdruidcult_cult_id_fk
                            FOREIGN KEY (cult_id)
                            REFERENCES charsheet_druidcult(id)
                            DEFERRABLE INITIALLY DEFERRED
                    );

                    CREATE TABLE IF NOT EXISTS charsheet_charactershamancult (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        character_id bigint NOT NULL UNIQUE,
                        cult_id bigint NOT NULL,
                        CONSTRAINT uniq_character_shaman_cult
                            UNIQUE (character_id),
                        CONSTRAINT charsheet_charactershamancult_character_id_fk
                            FOREIGN KEY (character_id)
                            REFERENCES charsheet_character(id)
                            DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT charsheet_charactershamancult_cult_id_fk
                            FOREIGN KEY (cult_id)
                            REFERENCES charsheet_shamancult(id)
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='characterdivineentity',
                    name='custom_type_label',
                ),
                migrations.RemoveField(
                    model_name='divineentity',
                    name='allows_custom_description',
                ),
                migrations.RemoveField(
                    model_name='divineentity',
                    name='allows_custom_god_image',
                ),
                migrations.RemoveField(
                    model_name='divineentity',
                    name='allows_custom_name',
                ),
                migrations.RemoveField(
                    model_name='divineentity',
                    name='entity_kind',
                ),
                migrations.AddField(
                    model_name='divineentity',
                    name='is_customizable',
                    field=models.BooleanField(default=False, help_text='If enabled, character bindings may customize the divine card on the sheet.'),
                ),
                migrations.CreateModel(
                    name='DruidCult',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=120, unique=True)),
                        ('slug', models.SlugField(max_length=120, unique=True)),
                        ('description', models.TextField(blank=True, default='')),
                        ('school', models.ForeignKey(blank=True, help_text='Optional druidic school this circle belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='druid_cults', to='charsheet.school')),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='ShamanCult',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=120, unique=True)),
                        ('slug', models.SlugField(max_length=120, unique=True)),
                        ('cult_kind', models.CharField(choices=[('totem', 'Totem'), ('spirit', 'Spirit')], max_length=20)),
                        ('description', models.TextField(blank=True, default='')),
                        ('school', models.ForeignKey(blank=True, help_text='Optional shamanic school this cult belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shaman_cults', to='charsheet.school')),
                    ],
                    options={
                        'ordering': ['cult_kind', 'name'],
                    },
                ),
                migrations.CreateModel(
                    name='CharacterDruidCult',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='druid_cult_binding', to='charsheet.character')),
                        ('cult', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='charsheet.druidcult')),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('character',), name='uniq_character_druid_cult')],
                    },
                ),
                migrations.CreateModel(
                    name='CharacterShamanCult',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shaman_cult_binding', to='charsheet.character')),
                        ('cult', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='charsheet.shamancult')),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('character',), name='uniq_character_shaman_cult')],
                    },
                ),
            ],
        ),
    ]
