# Generated by Django 6.0.5 on 2026-06-07

import django.db.models.deletion
from django.db import migrations, models


def reset_divine_customizable(apps, schema_editor):
    DivineEntity = apps.get_model("charsheet", "DivineEntity")
    DivineEntity.objects.update(is_customizable=False)


def migrate_shaman_patron_kind(apps, schema_editor):
    ShamanPatron = apps.get_model("charsheet", "ShamanPatron")
    ShamanPatron.objects.filter(patron_kind="spirit").update(patron_kind="ancestor_spirit")


def restore_shaman_cult_kind(apps, schema_editor):
    ShamanPatron = apps.get_model("charsheet", "ShamanPatron")
    ShamanPatron.objects.filter(patron_kind="ancestor_spirit").update(patron_kind="spirit")


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0183_remove_characterdivineentity_custom_type_label_and_more'),
    ]

    operations = [
        migrations.RunPython(reset_divine_customizable, migrations.RunPython.noop),
        migrations.AddField(
            model_name='druidcult',
            name='card_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='druidcult',
            name='fluff',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='druidcult',
            name='g_ability',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='druidcult',
            name='god_image',
            field=models.ImageField(blank=True, help_text='Optionales Kartenbild fuer diesen Druidenzirkel.', null=True, upload_to='druid_cults/'),
        ),
        migrations.AddField(
            model_name='druidcult',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='If enabled, character bindings may customize the druid circle card on the sheet.'),
        ),
        migrations.AddField(
            model_name='druidcult',
            name='symbol_image',
            field=models.ImageField(blank=True, help_text='Optionales Symbolbild fuer diesen Druidenzirkel.', null=True, upload_to='druid_cults/'),
        ),
        migrations.AddField(
            model_name='druidcult',
            name='aspect_selection_mode',
            field=models.CharField(choices=[('fixed', 'Fixed aspects'), ('choose_from_entity', 'Choose from entity aspects'), ('free', 'Free aspect choice')], default='fixed', help_text="Controls whether character bindings use the circle's fixed aspects or may choose individual core aspects.", max_length=24),
        ),
        migrations.AddField(
            model_name='druidcult',
            name='starting_aspect_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many core aspects this circle grants or lets the character choose.'),
        ),
        migrations.AddField(
            model_name='characterdruidcult',
            name='core_aspects',
            field=models.ManyToManyField(blank=True, help_text='Character-specific core aspects chosen from this druid circle.', related_name='character_druid_cult_bindings', to='charsheet.aspect'),
        ),
        migrations.CreateModel(
            name='DruidCultAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting_aspect', models.BooleanField(default=True, help_text='Marks one of the default aspects granted by the druid circle.')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druid_cults', to='charsheet.aspect')),
                ('cult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='charsheet.druidcult')),
            ],
            options={
                'ordering': ['cult__name', 'aspect__name'],
                'constraints': [models.UniqueConstraint(fields=('cult', 'aspect'), name='uniq_druid_cult_aspect')],
            },
        ),
        migrations.RemoveConstraint(
            model_name='charactershamancult',
            name='uniq_character_shaman_cult',
        ),
        migrations.RenameModel(
            old_name='ShamanCult',
            new_name='ShamanPatron',
        ),
        migrations.RenameModel(
            old_name='CharacterShamanCult',
            new_name='CharacterShamanPatron',
        ),
        migrations.RenameField(
            model_name='shamanpatron',
            old_name='cult_kind',
            new_name='patron_kind',
        ),
        migrations.RenameField(
            model_name='charactershamanpatron',
            old_name='cult',
            new_name='patron',
        ),
        migrations.RunPython(migrate_shaman_patron_kind, restore_shaman_cult_kind),
        migrations.AlterField(
            model_name='shamanpatron',
            name='patron_kind',
            field=models.CharField(choices=[('totem', 'Totem'), ('ancestor_spirit', 'Ancestor Spirit')], max_length=24),
        ),
        migrations.AlterModelOptions(
            name='shamanpatron',
            options={'ordering': ['patron_kind', 'name']},
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='card_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='fluff',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='g_ability',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='god_image',
            field=models.ImageField(blank=True, help_text='Optionales Kartenbild fuer dieses Totem oder diesen Ahnengeist.', null=True, upload_to='shaman_patrons/'),
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='If enabled, character bindings may customize the shaman patron card on the sheet.'),
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='symbol_image',
            field=models.ImageField(blank=True, help_text='Optionales Symbolbild fuer dieses Totem oder diesen Ahnengeist.', null=True, upload_to='shaman_patrons/'),
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='aspect_selection_mode',
            field=models.CharField(choices=[('fixed', 'Fixed aspects'), ('choose_from_entity', 'Choose from entity aspects'), ('free', 'Free aspect choice')], default='fixed', help_text="Controls whether character bindings use the patron's fixed aspects or may choose individual core aspects.", max_length=24),
        ),
        migrations.AddField(
            model_name='shamanpatron',
            name='starting_aspect_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many core aspects this patron grants or lets the character choose.'),
        ),
        migrations.AlterField(
            model_name='shamanpatron',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Optional shamanic school this patron belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shaman_patrons', to='charsheet.school'),
        ),
        migrations.AlterField(
            model_name='charactershamanpatron',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shaman_patron_binding', to='charsheet.character'),
        ),
        migrations.AlterField(
            model_name='charactershamanpatron',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='charsheet.shamanpatron'),
        ),
        migrations.AddField(
            model_name='charactershamanpatron',
            name='core_aspects',
            field=models.ManyToManyField(blank=True, help_text='Character-specific core aspects chosen from this shaman patron.', related_name='character_shaman_patron_bindings', to='charsheet.aspect'),
        ),
        migrations.CreateModel(
            name='ShamanPatronAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting_aspect', models.BooleanField(default=True, help_text='Marks one of the default aspects granted by the shaman patron.')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaman_patrons', to='charsheet.aspect')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='charsheet.shamanpatron')),
            ],
            options={
                'ordering': ['patron__name', 'aspect__name'],
                'constraints': [models.UniqueConstraint(fields=('patron', 'aspect'), name='uniq_shaman_patron_aspect')],
            },
        ),
        migrations.AddConstraint(
            model_name='charactershamanpatron',
            constraint=models.UniqueConstraint(fields=('character',), name='uniq_character_shaman_patron'),
        ),
    ]
