# Generated by Codex on 2026-06-11

from django.db import migrations, models


def copy_base_damage_type(apps, schema_editor):
    WeaponStats = apps.get_model("charsheet", "WeaponStats")
    for stats in WeaponStats.objects.all().only("id", "damage_type", "h2_damage_type"):
        if not stats.h2_damage_type:
            stats.h2_damage_type = stats.damage_type or "T"
            stats.save(update_fields=["h2_damage_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0190_repair_weaponstats_profile_and_range_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="weaponstats",
            name="h2_damage_type",
            field=models.CharField(choices=[("B", "B"), ("T", "T")], default="T", max_length=1),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="weapon_h2_damage_type_override",
            field=models.CharField(blank=True, choices=[("B", "B"), ("T", "T")], default="", max_length=1),
        ),
        migrations.RunPython(copy_base_damage_type, migrations.RunPython.noop),
    ]
