# Generated by Codex on 2026-06-21

from django.db import migrations, models


def migrate_signed_damage_bonus(apps, schema_editor):
    CreatureAttack = apps.get_model("charsheet", "CreatureAttack")
    for attack in CreatureAttack.objects.all().iterator():
        bonus = int(attack.damage_flat_bonus or 0)
        if bonus > 0:
            attack.damage_flat_operator = "+"
        elif bonus < 0:
            attack.damage_flat_operator = "-"
            attack.damage_flat_bonus = abs(bonus)
        else:
            attack.damage_flat_operator = ""
        attack.save(update_fields=["damage_flat_operator", "damage_flat_bonus"])


def restore_signed_damage_bonus(apps, schema_editor):
    CreatureAttack = apps.get_model("charsheet", "CreatureAttack")
    for attack in CreatureAttack.objects.all().iterator():
        if attack.damage_flat_operator == "-":
            attack.damage_flat_bonus = -abs(int(attack.damage_flat_bonus or 0))
        attack.damage_flat_operator = ""
        attack.save(update_fields=["damage_flat_operator", "damage_flat_bonus"])


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0192_remove_usersettings_sidebar_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatureattack",
            name="damage_flat_operator",
            field=models.CharField(
                blank=True,
                choices=[("", "Kein Operator"), ("+", "+"), ("-", "-"), ("/", "/")],
                default="",
                max_length=1,
            ),
        ),
        migrations.RunPython(migrate_signed_damage_bonus, restore_signed_damage_bonus),
    ]
