# Generated by Django 6.0.5 on 2026-06-21 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0194_creaturecommand_creaturecommandreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('creature_type', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='creature_cards/')),
                ('description', models.TextField(blank=True, default='')),
                ('source_reference', models.CharField(blank=True, default='', max_length=200)),
                ('initiative', models.IntegerField(default=0)),
                ('vw', models.IntegerField(default=0)),
                ('sr', models.IntegerField(default=0)),
                ('gw', models.IntegerField(default=0)),
                ('fear_resistance_bonus', models.IntegerField(default=0)),
                ('rs', models.PositiveIntegerField(default=0)),
                ('wound_step', models.PositiveIntegerField(default=1)),
                ('size_class', models.CharField(choices=[('S', 'S'), ('F', 'F'), ('W', 'W'), ('K', 'K'), ('M', 'M'), ('G', 'G'), ('R', 'R'), ('Gi', 'Gi'), ('Kol', 'Kol')], default='M', max_length=5)),
                ('size_modifier', models.IntegerField(default=0)),
                ('combat_speed', models.PositiveIntegerField(default=0)),
                ('march_speed', models.PositiveIntegerField(default=0)),
                ('sprint_speed', models.PositiveIntegerField(default=0)),
                ('swimming_speed', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('combat_fly_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('march_fly_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('sprint_fly_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('strength_mod', models.IntegerField(default=0)),
                ('constitution_mod', models.IntegerField(default=0)),
                ('dexterity_mod', models.IntegerField(default=0)),
                ('intelligence_mod', models.IntegerField(default=0)),
                ('perception_mod', models.IntegerField(default=0)),
                ('willpower_mod', models.IntegerField(default=0)),
                ('charisma_mod', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('current_damage', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
                ('creature_type', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_creature_cards/')),
                ('description', models.TextField(blank=True, default='')),
                ('source_reference', models.CharField(blank=True, default='', max_length=200)),
                ('initiative', models.IntegerField(default=0)),
                ('vw', models.IntegerField(default=0)),
                ('sr', models.IntegerField(default=0)),
                ('gw', models.IntegerField(default=0)),
                ('fear_resistance_bonus', models.IntegerField(default=0)),
                ('rs', models.PositiveIntegerField(default=0)),
                ('wound_step', models.PositiveIntegerField(default=1)),
                ('size_class', models.CharField(choices=[('S', 'S'), ('F', 'F'), ('W', 'W'), ('K', 'K'), ('M', 'M'), ('G', 'G'), ('R', 'R'), ('Gi', 'Gi'), ('Kol', 'Kol')], default='M', max_length=5)),
                ('size_modifier', models.IntegerField(default=0)),
                ('combat_speed', models.PositiveIntegerField(default=0)),
                ('march_speed', models.PositiveIntegerField(default=0)),
                ('sprint_speed', models.PositiveIntegerField(default=0)),
                ('swimming_speed', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('combat_fly_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('march_fly_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('sprint_fly_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('strength_mod', models.IntegerField(default=0)),
                ('constitution_mod', models.IntegerField(default=0)),
                ('dexterity_mod', models.IntegerField(default=0)),
                ('intelligence_mod', models.IntegerField(default=0)),
                ('perception_mod', models.IntegerField(default=0)),
                ('willpower_mod', models.IntegerField(default=0)),
                ('charisma_mod', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creature_cards', to='charsheet.character')),
            ],
            options={
                'ordering': ['character', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureCardAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attack_value', models.IntegerField(default=0)),
                ('damage', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='charsheet.charactercreaturecard')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureCardCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='charsheet.charactercreaturecard')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureCardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='charsheet.charactercreaturecard')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureCardTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='charsheet.charactercreaturecard')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreatureCardBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('item', 'Item'), ('technique', 'Technique')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('item_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creature_card_bindings', to='charsheet.item')),
                ('technique_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creature_card_bindings', to='charsheet.technique')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='charsheet.creaturecardtemplate')),
            ],
            options={
                'ordering': ['template__name', 'trigger_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='charactercreaturecard',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_cards', to='charsheet.creaturecardbinding'),
        ),
        migrations.AddField(
            model_name='charactercreaturecard',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_cards', to='charsheet.creaturecardtemplate'),
        ),
        migrations.CreateModel(
            name='CreatureCardTemplateAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attack_value', models.IntegerField(default=0)),
                ('damage', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='charsheet.creaturecardtemplate')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreatureCardTemplateCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='charsheet.creaturecardtemplate')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreatureCardTemplateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='charsheet.creaturecardtemplate')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreatureCardTemplateTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='charsheet.creaturecardtemplate')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='creaturecardbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('item_trigger__isnull', False)), fields=('template', 'item_trigger'), name='uniq_creature_card_item_binding'),
        ),
        migrations.AddConstraint(
            model_name='creaturecardbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('technique_trigger__isnull', False)), fields=('template', 'technique_trigger'), name='uniq_creature_card_technique_binding'),
        ),
        migrations.AddConstraint(
            model_name='charactercreaturecard',
            constraint=models.UniqueConstraint(fields=('character', 'binding'), name='uniq_character_creature_card_binding'),
        ),
    ]
