# Generated by Django 6.0.5 on 2026-06-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0195_creaturecardtemplate_charactercreaturecard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creaturecardtemplateattack',
            name='template',
        ),
        migrations.RemoveField(
            model_name='creaturecardtemplatecommand',
            name='template',
        ),
        migrations.RemoveField(
            model_name='creaturecardtemplatetrait',
            name='template',
        ),
        migrations.RemoveField(
            model_name='creaturecardtemplateskill',
            name='template',
        ),
        migrations.RemoveField(
            model_name='charactercreaturecard',
            name='template',
        ),
        migrations.AlterModelOptions(
            name='creaturecardbinding',
            options={'ordering': ['creature__name', 'trigger_type', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='creaturecardbinding',
            name='uniq_creature_card_item_binding',
        ),
        migrations.RemoveConstraint(
            model_name='creaturecardbinding',
            name='uniq_creature_card_technique_binding',
        ),
        migrations.AddField(
            model_name='charactercreaturecard',
            name='creature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_cards', to='charsheet.creature'),
        ),
        migrations.AddField(
            model_name='creaturecardbinding',
            name='creature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_bindings', to='charsheet.creature'),
        ),
        migrations.AddConstraint(
            model_name='creaturecardbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('item_trigger__isnull', False)), fields=('creature', 'item_trigger'), name='uniq_creature_card_item_binding'),
        ),
        migrations.AddConstraint(
            model_name='creaturecardbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('technique_trigger__isnull', False)), fields=('creature', 'technique_trigger'), name='uniq_creature_card_technique_binding'),
        ),
        migrations.DeleteModel(
            name='CreatureCardTemplateAttack',
        ),
        migrations.DeleteModel(
            name='CreatureCardTemplateCommand',
        ),
        migrations.DeleteModel(
            name='CreatureCardTemplateTrait',
        ),
        migrations.DeleteModel(
            name='CreatureCardTemplateSkill',
        ),
        migrations.RemoveField(
            model_name='creaturecardbinding',
            name='template',
        ),
        migrations.DeleteModel(
            name='CreatureCardTemplate',
        ),
    ]
