# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


ATTRIBUTE_FIELD_CODES = {
    "strength_mod": "ST",
    "constitution_mod": "KON",
    "dexterity_mod": "GE",
    "intelligence_mod": "INT",
    "perception_mod": "WA",
    "willpower_mod": "WILL",
    "charisma_mod": "CHA",
}


REPAIR_CREATURE_TABLE_SQL = """
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS slug varchar(100);
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS card_name varchar(100) NOT NULL DEFAULT '';
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS image varchar(100) NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS size_class varchar(5) NOT NULL DEFAULT 'M';
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS size_modifier integer NOT NULL DEFAULT 0;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS initiative_override integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS vw_override integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS sr_override integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS gw_override integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS fear_resistance_bonus integer NOT NULL DEFAULT 0;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS natural_rs integer NOT NULL DEFAULT 0;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS wound_step_override integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS combat_speed integer NOT NULL DEFAULT 0;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS march_speed integer NOT NULL DEFAULT 0;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS sprint_speed integer NOT NULL DEFAULT 0;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS swimming_speed double precision NOT NULL DEFAULT 0;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS combat_fly_speed integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS march_fly_speed integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS sprint_fly_speed integer NULL;
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS climate_and_occurrence text NOT NULL DEFAULT '';
ALTER TABLE charsheet_creature ADD COLUMN IF NOT EXISTS organization varchar(100) NOT NULL DEFAULT '';

UPDATE charsheet_creature
SET slug = CONCAT(
    LOWER(REGEXP_REPLACE(TRIM(name), '[^[:alnum:]]+', '-', 'g')),
    '-',
    id
)
WHERE slug IS NULL OR slug = '';

ALTER TABLE charsheet_creature ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS charsheet_creature_name_repair_uniq ON charsheet_creature (name);
CREATE UNIQUE INDEX IF NOT EXISTS charsheet_creature_slug_repair_uniq ON charsheet_creature (slug);
"""


DROP_OLD_CREATURE_ATTRIBUTE_COLUMNS_SQL = """
ALTER TABLE charsheet_creature DROP COLUMN IF EXISTS charisma_mod;
ALTER TABLE charsheet_creature DROP COLUMN IF EXISTS constitution_mod;
ALTER TABLE charsheet_creature DROP COLUMN IF EXISTS dexterity_mod;
ALTER TABLE charsheet_creature DROP COLUMN IF EXISTS intelligence_mod;
ALTER TABLE charsheet_creature DROP COLUMN IF EXISTS perception_mod;
ALTER TABLE charsheet_creature DROP COLUMN IF EXISTS strength_mod;
ALTER TABLE charsheet_creature DROP COLUMN IF EXISTS willpower_mod;
"""


def migrate_creature_attribute_fields(apps, schema_editor):
    connection = schema_editor.connection
    qn = schema_editor.quote_name
    creature_table = qn("charsheet_creature")
    attribute_table = qn("charsheet_attribute")
    creature_attribute_table = qn("charsheet_creatureattribute")

    with connection.cursor() as cursor:
        creature_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "charsheet_creature")
        }
        attribute_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "charsheet_attribute")
        }
        creature_select_fields = ["id"] + [
            field_name for field_name in ATTRIBUTE_FIELD_CODES if field_name in creature_columns
        ]
        cursor.execute(
            f"SELECT {', '.join(qn(field_name) for field_name in creature_select_fields)} "
            f"FROM {creature_table}"
        )
        creature_rows = cursor.fetchall()

        code_column = "short_name" if "short_name" in attribute_columns else "slug"
        cursor.execute(
            f"SELECT {qn('id')}, {qn(code_column)} "
            f"FROM {attribute_table} "
            f"WHERE {qn(code_column)} <> %s",
            ["spz."],
        )
        attribute_ids_by_code = {code: attribute_id for attribute_id, code in cursor.fetchall()}

        creature_field_indexes = {
            field_name: index
            for index, field_name in enumerate(creature_select_fields)
        }
        for creature_row in creature_rows:
            creature_id = creature_row[creature_field_indexes["id"]]
            for field_name, code in ATTRIBUTE_FIELD_CODES.items():
                attribute_id = attribute_ids_by_code.get(code)
                if attribute_id is None:
                    continue
                value = (
                    creature_row[creature_field_indexes[field_name]]
                    if field_name in creature_field_indexes
                    else 0
                )
                cursor.execute(
                    f"INSERT INTO {creature_attribute_table} "
                    f"({qn('creature_id')}, {qn('attribute_id')}, {qn('modifier')}) "
                    f"VALUES (%s, %s, %s) "
                    f"ON CONFLICT ({qn('creature_id')}, {qn('attribute_id')}) "
                    f"DO UPDATE SET {qn('modifier')} = EXCLUDED.{qn('modifier')}",
                    [creature_id, attribute_id, value],
                )


def restore_creature_attribute_fields(apps, schema_editor):
    connection = schema_editor.connection
    qn = schema_editor.quote_name
    creature_table = qn("charsheet_creature")
    attribute_table = qn("charsheet_attribute")
    creature_attribute_table = qn("charsheet_creatureattribute")

    with connection.cursor() as cursor:
        creature_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "charsheet_creature")
        }
        attribute_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "charsheet_attribute")
        }
        code_column = "short_name" if "short_name" in attribute_columns else "slug"
        field_by_code = {code: field_name for field_name, code in ATTRIBUTE_FIELD_CODES.items()}
        cursor.execute(
            f"SELECT ca.{qn('creature_id')}, a.{qn(code_column)}, ca.{qn('modifier')} "
            f"FROM {creature_attribute_table} ca "
            f"JOIN {attribute_table} a ON a.{qn('id')} = ca.{qn('attribute_id')}"
        )
        for creature_id, code, modifier in cursor.fetchall():
            field_name = field_by_code.get(code)
            if field_name and field_name in creature_columns:
                cursor.execute(
                    f"UPDATE {creature_table} SET {qn(field_name)} = %s WHERE {qn('id')} = %s",
                    [modifier, creature_id],
                )


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0202_alter_item_item_type"),
    ]

    operations = [
        migrations.RunSQL(REPAIR_CREATURE_TABLE_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name="CreatureAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modifier", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "attribute",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="charsheet.attribute"),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="charsheet.creature",
                    ),
                ),
            ],
            options={
                "ordering": ["creature", "attribute"],
            },
        ),
        migrations.AddConstraint(
            model_name="creatureattribute",
            constraint=models.UniqueConstraint(
                fields=("creature", "attribute"),
                name="uniq_creature_attribute",
            ),
        ),
        migrations.RunPython(migrate_creature_attribute_fields, restore_creature_attribute_fields),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    DROP_OLD_CREATURE_ATTRIBUTE_COLUMNS_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="creature", name="charisma_mod"),
                migrations.RemoveField(model_name="creature", name="constitution_mod"),
                migrations.RemoveField(model_name="creature", name="dexterity_mod"),
                migrations.RemoveField(model_name="creature", name="intelligence_mod"),
                migrations.RemoveField(model_name="creature", name="perception_mod"),
                migrations.RemoveField(model_name="creature", name="strength_mod"),
                migrations.RemoveField(model_name="creature", name="willpower_mod"),
            ],
        ),
    ]
