# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charsheet", "0208_creature_trait_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="creaturetraitdefinition",
            name="trait_type",
            field=models.CharField(
                choices=[("advantage", "Advantage"), ("disadvantage", "Disadvantage")],
                default="advantage",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
