# Generated by Codex on 2026-06-27

from decimal import Decimal

from django.db import migrations, models


COMMANDS = (
    ("Apportieren", "apportieren", "1", 14, ""),
    ("Bei Fuss", "bei-fuss", "0.5", 14, "Komm"),
    ("Beschuetze dieses Wesen", "beschuetze-dieses-wesen", "1", 22, "Bei Fuss & Fass"),
    ("Bewache", "bewache", "1", 22, "Sitz & Fass/Gib Laut"),
    ("Bring Objekt", "bring-objekt", "2", 18, "Apportieren"),
    ("Fass", "fass", "3", 18, ""),
    ("Finde", "finde", "2", 17, "Such die Spur"),
    ("Gehorche dieser Person", "gehorche-dieser-person", "1", 14, ""),
    ("Gehorche nicht dieser Person", "gehorche-nicht-dieser-person", "1", 14, ""),
    ("Gib Laut", "gib-laut", "0.5", 13, ""),
    ("Komm", "komm", "0.5", 13, ""),
    ("Lass ab", "lass-ab", "0.5", 13, ""),
    ("Lauf dorthin", "lauf-dorthin", "0.5", 13, ""),
    ("Mach Maennchen", "mach-maennchen", "1", 14, ""),
    ("Platz", "platz", "0.5", 13, ""),
    ("Sitz", "sitz", "0.5", 13, ""),
    ("Spring", "spring", "0.5", 13, ""),
    ("Such die Spur", "such-die-spur", "2", 16, ""),
    ("Tanzen", "tanzen", "2", 18, "Mach Maennchen"),
    ("Taschendiebstahl", "taschendiebstahl", "2", 22, "Bring Objekt"),
    ("Tot stellen", "tot-stellen", "1", 15, "Platz"),
    ("Wirf Reiter ab", "wirf-reiter-ab", "1", 14, ""),
)


def populate_creature_commands(apps, schema_editor):
    CreatureCommand = apps.get_model("charsheet", "CreatureCommand")
    CharacterCreatureCardCommand = apps.get_model("charsheet", "CharacterCreatureCardCommand")
    for name, slug, ep_cost, difficulty, prerequisites in COMMANDS:
        CreatureCommand.objects.update_or_create(
            name=name,
            defaults={
                "slug": slug,
                "ep_cost": Decimal(ep_cost),
                "difficulty": difficulty,
                "prerequisites": prerequisites,
            },
        )
        CharacterCreatureCardCommand.objects.filter(name=name).update(
            ep_cost=Decimal(ep_cost),
            difficulty=difficulty,
            prerequisites=prerequisites,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("charsheet", "0209_creature_trait_definition_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="creaturecommand",
            name="difficulty",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creaturecommand",
            name="ep_cost",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="creaturecommand",
            name="prerequisites",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="charactercreaturecardcommand",
            name="difficulty",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactercreaturecardcommand",
            name="ep_cost",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="charactercreaturecardcommand",
            name="prerequisites",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.RunPython(populate_creature_commands, noop_reverse),
    ]
