# Generated by Codex on 2026-06-27

import django.db.models.deletion
from django.db import migrations, models


COMMAND_PREREQUISITES = (
    ("Bei Fuss", (("Komm",),)),
    ("Beschuetze dieses Wesen", (("Bei Fuss",), ("Fass",))),
    ("Bewache", (("Sitz",), ("Fass", "Gib Laut"))),
    ("Bring Objekt", (("Apportieren",),)),
    ("Finde", (("Such die Spur",),)),
    ("Tanzen", (("Mach Maennchen",),)),
    ("Taschendiebstahl", (("Bring Objekt",),)),
    ("Tot stellen", (("Platz",),)),
)


def populate_prerequisites(apps, schema_editor):
    CreatureCommand = apps.get_model("charsheet", "CreatureCommand")
    CreatureCommandPrerequisite = apps.get_model("charsheet", "CreatureCommandPrerequisite")
    CharacterCreatureCardCommand = apps.get_model("charsheet", "CharacterCreatureCardCommand")
    CharacterCreatureCardCommandPrerequisite = apps.get_model(
        "charsheet",
        "CharacterCreatureCardCommandPrerequisite",
    )

    commands_by_name = {command.name: command for command in CreatureCommand.objects.all()}
    CreatureCommandPrerequisite.objects.filter(command__name__in=[name for name, _groups in COMMAND_PREREQUISITES]).delete()
    for command_name, prerequisite_groups in COMMAND_PREREQUISITES:
        command = commands_by_name.get(command_name)
        if command is None:
            continue
        for group_index, prerequisite_group in enumerate(prerequisite_groups):
            for order, prerequisite_name in enumerate(prerequisite_group):
                prerequisite = commands_by_name.get(prerequisite_name)
                if prerequisite is None:
                    continue
                CreatureCommandPrerequisite.objects.create(
                    command=command,
                    prerequisite=prerequisite,
                    alternative_group=group_index,
                    order=order,
                )

    prerequisite_data = dict(COMMAND_PREREQUISITES)
    for card_command in CharacterCreatureCardCommand.objects.filter(name__in=prerequisite_data).select_related("card"):
        CharacterCreatureCardCommandPrerequisite.objects.filter(command=card_command).delete()
        card_commands_by_name = {
            command.name: command
            for command in CharacterCreatureCardCommand.objects.filter(card=card_command.card)
        }
        for group_index, prerequisite_group in enumerate(prerequisite_data[card_command.name]):
            for order, prerequisite_name in enumerate(prerequisite_group):
                prerequisite = card_commands_by_name.get(prerequisite_name)
                if prerequisite is None:
                    continue
                CharacterCreatureCardCommandPrerequisite.objects.create(
                    command=card_command,
                    prerequisite=prerequisite,
                    alternative_group=group_index,
                    order=order,
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("charsheet", "0210_creature_command_rule_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creaturecommand",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="charactercreaturecardcommand",
            name="prerequisites",
        ),
        migrations.CreateModel(
            name="CreatureCommandPrerequisite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alternative_group", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_links",
                        to="charsheet.creaturecommand",
                    ),
                ),
                (
                    "prerequisite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_by_links",
                        to="charsheet.creaturecommand",
                    ),
                ),
            ],
            options={
                "ordering": ["alternative_group", "order", "prerequisite__name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterCreatureCardCommandPrerequisite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alternative_group", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_links",
                        to="charsheet.charactercreaturecardcommand",
                    ),
                ),
                (
                    "prerequisite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_by_links",
                        to="charsheet.charactercreaturecardcommand",
                    ),
                ),
            ],
            options={
                "ordering": ["alternative_group", "order", "prerequisite__name"],
            },
        ),
        migrations.AddField(
            model_name="creaturecommand",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocks",
                through="charsheet.CreatureCommandPrerequisite",
                to="charsheet.creaturecommand",
            ),
        ),
        migrations.AddField(
            model_name="charactercreaturecardcommand",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocks",
                through="charsheet.CharacterCreatureCardCommandPrerequisite",
                to="charsheet.charactercreaturecardcommand",
            ),
        ),
        migrations.AddConstraint(
            model_name="creaturecommandprerequisite",
            constraint=models.UniqueConstraint(
                fields=("command", "prerequisite", "alternative_group"),
                name="uniq_creature_command_prerequisite_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactercreaturecardcommandprerequisite",
            constraint=models.UniqueConstraint(
                fields=("command", "prerequisite", "alternative_group"),
                name="uniq_card_command_prerequisite_group",
            ),
        ),
        migrations.RunPython(populate_prerequisites, noop_reverse),
    ]
