# Generated by Django 6.0.5 on 2026-06-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0213_quality_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creaturespecialskill',
            name='picture',
        ),
    ]
