# Generated by Django 6.0.5 on 2026-06-27 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0214_remove_creaturespecialskill_picture'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturetraitdefinition',
            name='points_by_level',
            field=models.CharField(blank=True, default='', help_text="Optional comma-separated per-level costs such as '1,3' or '2,4,6'. Overrides points_per_level.", max_length=200),
        ),
        migrations.AddField(
            model_name='creaturetraitdefinition',
            name='points_per_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CreatureTraitChoiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_kind', models.CharField(choices=[('attribute', 'Attribute'), ('skill', 'Skill'), ('skill_category', 'Skill Category'), ('derived_stat', 'Derived Stat'), ('resource', 'Resource'), ('proficiency_group', 'Proficiency Group'), ('item', 'Item'), ('item_category', 'Item Category'), ('specialization', 'Specialization'), ('text', 'Free Text'), ('entity', 'Other Entity')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('min_choices', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_choices', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True)),
                ('allowed_skill_family', models.SlugField(blank=True, default='')),
                ('allowed_derived_stat', models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arkane Macht'), ('potential', 'Potenzial'), ('wound_stage', 'Wundstufe'), ('wound_penalty_mod', 'Wundmalus verändern'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS'), ('armor_encumbrance', 'Belastung dieser Rüstung'), ('shield_encumbrance', 'Belastung dieses Schilds'), ('melee_maneuvers', 'Manöver mit dieser Waffe'), ('weapon_damage', 'Schaden mit dieser Waffe'), ('weapon_damage_dice', 'Zusaetzliche Schadenswuerfel mit dieser Waffe')], default='', max_length=50)),
                ('allowed_resource', models.CharField(blank=True, choices=[('personal_fame_point', 'Persönliche Ruhmpunkte'), ('personal_fame_rank', 'Persönlicher Rang'), ('artefact_rank', 'Artefaktrang'), ('sacrifice_rank', 'Opferrang')], default='', max_length=50)),
                ('allowed_proficiency_group', models.CharField(blank=True, choices=[('skill_fine_motor', 'Feinmotorische Fertigkeiten'), ('skill_gross_motor', 'Grobmotorische Fertigkeiten'), ('skill_social', 'Soziale Fertigkeiten'), ('skill_knowledge', 'Wissensfertigkeiten'), ('skill_combat', 'Waffenfertigkeiten'), ('foreign_languages', 'Sprachen (außer Muttersprache)')], default='', max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creature_trait_choice_definitions', to='charsheet.attribute')),
                ('allowed_skill_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creature_trait_choice_definitions', to='charsheet.skillcategory')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_definitions', to='charsheet.creaturetraitdefinition')),
            ],
            options={
                'ordering': ['trait__trait_type', 'trait__name', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreatureTraitSemanticEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('target_domain', models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity')], default='rule_flag', max_length=40)),
                ('target_key', models.CharField(blank=True, default='', max_length=120)),
                ('operator', models.CharField(choices=[('flat_add', 'flat_add'), ('flat_sub', 'flat_sub'), ('multiply', 'multiply'), ('override', 'override'), ('min_value', 'min_value'), ('max_value', 'max_value'), ('set_flag', 'set_flag'), ('unset_flag', 'unset_flag'), ('add_tag', 'add_tag'), ('remove_tag', 'remove_tag'), ('grant_capability', 'grant_capability'), ('remove_capability', 'remove_capability'), ('grant_immunity', 'grant_immunity'), ('grant_vulnerability', 'grant_vulnerability'), ('change_resource_cap', 'change_resource_cap'), ('change_starting_funds', 'change_starting_funds'), ('change_appearance_class', 'change_appearance_class'), ('change_social_status', 'change_social_status'), ('reroll_grant', 'reroll_grant'), ('reroll_forbid', 'reroll_forbid'), ('repeat_action_allowed', 'repeat_action_allowed'), ('action_cost_change', 'action_cost_change'), ('conditional_bonus', 'conditional_bonus'), ('conditional_penalty', 'conditional_penalty')], default='flat_add', max_length=40)),
                ('mode', models.CharField(default='flat', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('value_min', models.IntegerField(blank=True, null=True)),
                ('value_max', models.IntegerField(blank=True, null=True)),
                ('formula', models.CharField(blank=True, default='', max_length=200)),
                ('scaling', models.JSONField(blank=True, default=dict)),
                ('stack_behavior', models.CharField(choices=[('stack', 'stack'), ('highest', 'highest'), ('lowest', 'lowest'), ('override', 'override'), ('unique_by_source', 'unique_by_source')], default='stack', max_length=40)),
                ('condition_set', models.JSONField(blank=True, default=dict)),
                ('active_flag', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('rules_text', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('internal', 'internal'), ('story', 'story')], default='public', max_length=20)),
                ('hidden', models.BooleanField(default=False)),
                ('sheet_relevant', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('target_choice_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semantic_effects', to='charsheet.creaturetraitchoicedefinition')),
                ('target_skills', models.ManyToManyField(blank=True, help_text='Optional concrete skill targets. Use this instead of target_key for multi-skill effects.', related_name='creature_trait_semantic_effects', to='charsheet.skill')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_effects', to='charsheet.creaturetraitdefinition')),
            ],
            options={
                'ordering': ['trait', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreatureTraitChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_derived_stat', models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arkane Macht'), ('potential', 'Potenzial'), ('wound_stage', 'Wundstufe'), ('wound_penalty_mod', 'Wundmalus verändern'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS'), ('armor_encumbrance', 'Belastung dieser Rüstung'), ('shield_encumbrance', 'Belastung dieses Schilds'), ('melee_maneuvers', 'Manöver mit dieser Waffe'), ('weapon_damage', 'Schaden mit dieser Waffe'), ('weapon_damage_dice', 'Zusaetzliche Schadenswuerfel mit dieser Waffe')], default='', max_length=50)),
                ('selected_resource', models.CharField(blank=True, choices=[('personal_fame_point', 'Persönliche Ruhmpunkte'), ('personal_fame_rank', 'Persönlicher Rang'), ('artefact_rank', 'Artefaktrang'), ('sacrifice_rank', 'Opferrang')], default='', max_length=50)),
                ('selected_proficiency_group', models.CharField(blank=True, choices=[('skill_fine_motor', 'Feinmotorische Fertigkeiten'), ('skill_gross_motor', 'Grobmotorische Fertigkeiten'), ('skill_social', 'Soziale Fertigkeiten'), ('skill_knowledge', 'Wissensfertigkeiten'), ('skill_combat', 'Waffenfertigkeiten'), ('foreign_languages', 'Sprachen (außer Muttersprache)')], default='', max_length=50)),
                ('selected_item_category', models.CharField(blank=True, default='', max_length=30)),
                ('selected_text', models.CharField(blank=True, default='', max_length=255)),
                ('selected_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('creature_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='charsheet.creaturetrait')),
                ('selected_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.attribute')),
                ('selected_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('selected_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.item')),
                ('selected_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.skill')),
                ('selected_skill_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.skillcategory')),
                ('selected_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.specialization')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creature_choices', to='charsheet.creaturetraitchoicedefinition')),
            ],
            options={
                'ordering': ['creature_trait__creature__name', 'creature_trait__trait__name', 'definition__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('selected_attribute__isnull', False)), fields=('creature_trait', 'definition', 'selected_attribute'), name='uniq_creature_trait_choice_attribute'), models.UniqueConstraint(condition=models.Q(('selected_skill__isnull', False)), fields=('creature_trait', 'definition', 'selected_skill'), name='uniq_creature_trait_choice_skill'), models.UniqueConstraint(condition=models.Q(('selected_skill_category__isnull', False)), fields=('creature_trait', 'definition', 'selected_skill_category'), name='uniq_creature_trait_choice_category'), models.UniqueConstraint(condition=models.Q(('selected_item__isnull', False)), fields=('creature_trait', 'definition', 'selected_item'), name='uniq_creature_trait_choice_item'), models.UniqueConstraint(condition=models.Q(('selected_specialization__isnull', False)), fields=('creature_trait', 'definition', 'selected_specialization'), name='uniq_creature_trait_choice_specialization'), models.UniqueConstraint(condition=models.Q(('selected_item_category', ''), _negated=True), fields=('creature_trait', 'definition', 'selected_item_category'), name='uniq_creature_trait_choice_item_category'), models.UniqueConstraint(condition=models.Q(('selected_object_id__isnull', False)), fields=('creature_trait', 'definition', 'selected_content_type', 'selected_object_id'), name='uniq_creature_trait_choice_entity')],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureTraitChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_derived_stat', models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('arcane_power', 'Arkane Macht'), ('potential', 'Potenzial'), ('wound_stage', 'Wundstufe'), ('wound_penalty_mod', 'Wundmalus verändern'), ('vw', 'VW'), ('gw', 'GW'), ('sr', 'SR'), ('rs', 'RS'), ('armor_encumbrance', 'Belastung dieser Rüstung'), ('shield_encumbrance', 'Belastung dieses Schilds'), ('melee_maneuvers', 'Manöver mit dieser Waffe'), ('weapon_damage', 'Schaden mit dieser Waffe'), ('weapon_damage_dice', 'Zusaetzliche Schadenswuerfel mit dieser Waffe')], default='', max_length=50)),
                ('selected_resource', models.CharField(blank=True, choices=[('personal_fame_point', 'Persönliche Ruhmpunkte'), ('personal_fame_rank', 'Persönlicher Rang'), ('artefact_rank', 'Artefaktrang'), ('sacrifice_rank', 'Opferrang')], default='', max_length=50)),
                ('selected_proficiency_group', models.CharField(blank=True, choices=[('skill_fine_motor', 'Feinmotorische Fertigkeiten'), ('skill_gross_motor', 'Grobmotorische Fertigkeiten'), ('skill_social', 'Soziale Fertigkeiten'), ('skill_knowledge', 'Wissensfertigkeiten'), ('skill_combat', 'Waffenfertigkeiten'), ('foreign_languages', 'Sprachen (außer Muttersprache)')], default='', max_length=50)),
                ('selected_item_category', models.CharField(blank=True, default='', max_length=30)),
                ('selected_text', models.CharField(blank=True, default='', max_length=255)),
                ('selected_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('character_creature_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='charsheet.charactercreaturetrait')),
                ('selected_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.attribute')),
                ('selected_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('selected_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.item')),
                ('selected_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.skill')),
                ('selected_skill_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.skillcategory')),
                ('selected_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='charsheet.specialization')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_creature_choices', to='charsheet.creaturetraitchoicedefinition')),
            ],
            options={
                'ordering': ['character_creature_trait__creature__owner__name', 'character_creature_trait__trait__name', 'definition__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('selected_attribute__isnull', False)), fields=('character_creature_trait', 'definition', 'selected_attribute'), name='uniq_character_creature_trait_choice_attribute'), models.UniqueConstraint(condition=models.Q(('selected_skill__isnull', False)), fields=('character_creature_trait', 'definition', 'selected_skill'), name='uniq_character_creature_trait_choice_skill'), models.UniqueConstraint(condition=models.Q(('selected_skill_category__isnull', False)), fields=('character_creature_trait', 'definition', 'selected_skill_category'), name='uniq_character_creature_trait_choice_category'), models.UniqueConstraint(condition=models.Q(('selected_item__isnull', False)), fields=('character_creature_trait', 'definition', 'selected_item'), name='uniq_character_creature_trait_choice_item'), models.UniqueConstraint(condition=models.Q(('selected_specialization__isnull', False)), fields=('character_creature_trait', 'definition', 'selected_specialization'), name='uniq_character_creature_trait_choice_specialization'), models.UniqueConstraint(condition=models.Q(('selected_item_category', ''), _negated=True), fields=('character_creature_trait', 'definition', 'selected_item_category'), name='uniq_character_creature_trait_choice_item_category'), models.UniqueConstraint(condition=models.Q(('selected_object_id__isnull', False)), fields=('character_creature_trait', 'definition', 'selected_content_type', 'selected_object_id'), name='uniq_character_creature_trait_choice_entity')],
            },
        ),
    ]
