# Generated by Django 6.0.5 on 2026-06-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0216_creature_card_source_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercreature',
            name='defense_extra_label_override',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Zusatz-Label-Override'),
        ),
        migrations.AddField(
            model_name='charactercreaturecard',
            name='defense_extra_label',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Zusatz-Label'),
        ),
        migrations.AddField(
            model_name='creature',
            name='defense_extra_label',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Zusatz-Label'),
        ),
        migrations.AlterField(
            model_name='charactercreature',
            name='fear_resistance_bonus_override',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zusatzwert-Override'),
        ),
        migrations.AlterField(
            model_name='charactercreaturecard',
            name='fear_resistance_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zusatzwert'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='fear_resistance_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zusatzwert'),
        ),
    ]
