# Generated by Django 6.0.5 on 2026-06-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0217_charactercreature_defense_extra_label_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercreature',
            name='defense_extra_label_override',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='GW extra label override'),
        ),
        migrations.AlterField(
            model_name='charactercreature',
            name='fear_resistance_bonus_override',
            field=models.IntegerField(blank=True, null=True, verbose_name='GW extra value override'),
        ),
        migrations.AlterField(
            model_name='charactercreaturecard',
            name='defense_extra_label',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='GW extra label'),
        ),
        migrations.AlterField(
            model_name='charactercreaturecard',
            name='fear_resistance_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='GW extra value'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='defense_extra_label',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='GW extra label'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='fear_resistance_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='GW extra value'),
        ),
    ]
