# Generated by Django 6.0.5 on 2026-06-28 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def initialize_creature_card_training_data(apps, schema_editor):
    CharacterCreatureCard = apps.get_model("charsheet", "CharacterCreatureCard")
    CharacterCreatureCardCommand = apps.get_model("charsheet", "CharacterCreatureCardCommand")
    CreatureCommand = apps.get_model("charsheet", "CreatureCommand")
    budgets = {
        "wretched": (0, 3),
        "very_poor": (0, 2),
        "poor": (0, 1),
        "common": (0, 0),
        "fine": (1, 0),
        "excellent": (2, 0),
        "legendary": (3, 0),
    }
    for card in CharacterCreatureCard.objects.select_related("quality").iterator():
        quality_code = getattr(card.quality, "code", None) or "common"
        advantage_points, disadvantage_points = budgets.get(quality_code, budgets["common"])
        card.max_base_advantage_points = advantage_points
        card.max_base_disadvantage_points = disadvantage_points
        card.save(update_fields=["max_base_advantage_points", "max_base_disadvantage_points"])

    commands_by_slug = {
        command.slug: command.pk
        for command in CreatureCommand.objects.exclude(slug="").iterator()
    }
    for card_command in CharacterCreatureCardCommand.objects.filter(command__isnull=True).exclude(slug="").iterator():
        command_id = commands_by_slug.get(card_command.slug)
        if command_id:
            card_command.command_id = command_id
            card_command.save(update_fields=["command"])


def clear_creature_card_training_data(apps, schema_editor):
    CharacterCreatureCardCommand = apps.get_model("charsheet", "CharacterCreatureCardCommand")
    CharacterCreatureCardCommand.objects.update(command=None)


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0218_alter_charactercreature_defense_extra_label_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCreatureCardAttributeIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('GE', 'Geschicklichkeit'), ('WA', 'Wahrnehmung'), ('INT', 'Intelligenz'), ('WILL', 'Willenskraft'), ('ST', 'Stärke'), ('KON', 'Konstitution'), ('CHA', 'Charisma'), ('spz.', 'Spezial')], max_length=10)),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['attribute', 'id'],
            },
        ),
        migrations.AddField(
            model_name='charactercreaturecard',
            name='max_base_advantage_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreaturecard',
            name='max_base_disadvantage_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreaturecardcommand',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creature_card_commands', to='charsheet.creaturecommand'),
        ),
        migrations.AddField(
            model_name='charactercreaturecardtrait',
            name='point_cost_override',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charactercreaturecardtrait',
            name='point_source',
            field=models.CharField(blank=True, choices=[('', 'Keine Budgetwirkung'), ('base_disadvantage', 'Basis-Schwäche'), ('additional_disadvantage', 'Zusatzschwäche')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='charactercreaturecardtrait',
            name='training_trait_type',
            field=models.CharField(blank=True, choices=[('', 'Keine Ausbildung'), ('advantage', 'Vorzug'), ('disadvantage', 'Schwäche')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='charactercreaturecardtrait',
            name='trait_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creature_card_traits', to='charsheet.creaturetraitdefinition'),
        ),
        migrations.AddField(
            model_name='charactercreaturecardattributeincrease',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_increases', to='charsheet.charactercreaturecard'),
        ),
        migrations.RunPython(initialize_creature_card_training_data, clear_creature_card_training_data),
        migrations.AddConstraint(
            model_name='charactercreaturecardcommand',
            constraint=models.UniqueConstraint(condition=models.Q(('command__isnull', False)), fields=('card', 'command'), name='uniq_card_known_creature_command'),
        ),
        migrations.AddConstraint(
            model_name='charactercreaturecardattributeincrease',
            constraint=models.UniqueConstraint(fields=('card', 'attribute'), name='uniq_card_attribute_increase'),
        ),
    ]
