# Generated by Django 6.0.5 on 2026-06-30 19:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_creature_cards_to_character_creatures(apps, schema_editor):
    CreatureCardBinding = apps.get_model("charsheet", "CreatureCardBinding")
    CreatureSourceBinding = apps.get_model("charsheet", "CreatureSourceBinding")
    CharacterCreatureCard = apps.get_model("charsheet", "CharacterCreatureCard")
    CharacterCreatureCardSkill = apps.get_model("charsheet", "CharacterCreatureCardSkill")
    CharacterCreatureCardTrait = apps.get_model("charsheet", "CharacterCreatureCardTrait")
    CharacterCreatureCardCommand = apps.get_model("charsheet", "CharacterCreatureCardCommand")
    CharacterCreatureCardCommandPrerequisite = apps.get_model("charsheet", "CharacterCreatureCardCommandPrerequisite")
    CharacterCreatureCardAttributeIncrease = apps.get_model("charsheet", "CharacterCreatureCardAttributeIncrease")
    CharacterCreature = apps.get_model("charsheet", "CharacterCreature")
    CharacterCreatureSkill = apps.get_model("charsheet", "CharacterCreatureSkill")
    CharacterCreatureSpecialSkill = apps.get_model("charsheet", "CharacterCreatureSpecialSkill")
    CharacterCreatureTrait = apps.get_model("charsheet", "CharacterCreatureTrait")
    CharacterCreatureCommand = apps.get_model("charsheet", "CharacterCreatureCommand")
    CharacterCreatureCommandPrerequisite = apps.get_model("charsheet", "CharacterCreatureCommandPrerequisite")
    CharacterCreatureAttributeIncrease = apps.get_model("charsheet", "CharacterCreatureAttributeIncrease")
    Skill = apps.get_model("charsheet", "Skill")
    CreatureSpecialSkill = apps.get_model("charsheet", "CreatureSpecialSkill")

    binding_by_old_id = {}
    for old_binding in CreatureCardBinding.objects.all().iterator():
        new_binding, _created = CreatureSourceBinding.objects.get_or_create(
            creature_id=old_binding.creature_id,
            trigger_type=old_binding.trigger_type,
            item_trigger_id=old_binding.item_trigger_id,
            technique_trigger_id=old_binding.technique_trigger_id,
            defaults={
                "quality_id": old_binding.quality_id,
                "active": old_binding.active,
                "note": old_binding.note,
            },
        )
        update_fields = []
        for field_name in ("quality_id", "active", "note"):
            value = getattr(old_binding, field_name)
            if getattr(new_binding, field_name) != value:
                setattr(new_binding, field_name, value)
                update_fields.append(field_name)
        if update_fields:
            new_binding.save(update_fields=update_fields)
        binding_by_old_id[old_binding.pk] = new_binding

    card_to_creature = {}
    override_fields = {
        "initiative": "initiative_override",
        "vw": "vw_override",
        "sr": "sr_override",
        "gw": "gw_override",
        "defense_extra_label": "defense_extra_label_override",
        "fear_resistance_bonus": "fear_resistance_bonus_override",
        "rs": "natural_rs_override",
        "wound_step": "wound_step_override",
        "size_class": "size_class_override",
        "size_modifier": "size_modifier_override",
        "combat_speed": "combat_speed_override",
        "march_speed": "march_speed_override",
        "sprint_speed": "sprint_speed_override",
        "swimming_speed": "swimming_speed_override",
        "combat_fly_speed": "combat_fly_speed_override",
        "march_fly_speed": "march_fly_speed_override",
        "sprint_fly_speed": "sprint_fly_speed_override",
    }
    attribute_override_fields = {
        "strength_mod": "strength_mod_override",
        "constitution_mod": "constitution_mod_override",
        "dexterity_mod": "dexterity_mod_override",
        "intelligence_mod": "intelligence_mod_override",
        "perception_mod": "perception_mod_override",
        "willpower_mod": "willpower_mod_override",
        "charisma_mod": "charisma_mod_override",
    }
    for card in CharacterCreatureCard.objects.select_related("creature", "binding").iterator():
        if not card.creature_id:
            continue
        binding = binding_by_old_id.get(card.binding_id)
        if binding is None:
            continue
        base_name = getattr(card.creature, "card_name", "") or getattr(card.creature, "name", "")
        defaults = {
            "creature_id": card.creature_id,
            "quality_id": card.quality_id,
            "active": card.active,
            "current_damage": card.current_damage,
            "notes": card.notes,
            "max_base_advantage_points": card.max_base_advantage_points,
            "max_base_disadvantage_points": card.max_base_disadvantage_points,
        }
        if card.name and card.name != base_name:
            defaults["name_override"] = card.name
        if card.image:
            defaults["image_override"] = card.image
        defaults.update({target: getattr(card, source) for source, target in override_fields.items()})
        for source, target in attribute_override_fields.items():
            value = getattr(card, source)
            defaults[target] = None if value is None else int(value)
        creature, _created = CharacterCreature.objects.get_or_create(
            owner_id=card.character_id,
            source_binding_id=binding.pk,
            source_character_item_id=card.source_character_item_id,
            source_character_technique_id=card.source_character_technique_id,
            defaults=defaults,
        )
        update_fields = []
        for field_name, value in defaults.items():
            if getattr(creature, field_name) != value:
                setattr(creature, field_name, value)
                update_fields.append(field_name)
        if update_fields:
            creature.save(update_fields=update_fields)
        card_to_creature[card.pk] = creature

    skipped_skills_by_creature = {}
    for card_skill in CharacterCreatureCardSkill.objects.all().iterator():
        creature = card_to_creature.get(card_skill.card_id)
        if creature is None:
            continue
        skill = Skill.objects.filter(name__iexact=card_skill.name).first()
        if skill is not None:
            CharacterCreatureSkill.objects.update_or_create(
                creature_id=creature.pk,
                skill_id=skill.pk,
                defaults={"level_override": card_skill.value, "notes": card_skill.notes},
            )
            continue
        special_skill = CreatureSpecialSkill.objects.filter(name__iexact=card_skill.name).first()
        if special_skill is not None:
            CharacterCreatureSpecialSkill.objects.update_or_create(
                creature_id=creature.pk,
                skill_id=special_skill.pk,
                defaults={"value_override": card_skill.value, "notes": card_skill.notes},
            )
            continue
        skipped_skills_by_creature.setdefault(creature.pk, []).append(card_skill.name)

    for creature_id, names in skipped_skills_by_creature.items():
        creature = CharacterCreature.objects.get(pk=creature_id)
        note = "Nicht migrierte Legacy-Card-Skills: " + ", ".join(sorted(set(names)))
        creature.notes = f"{creature.notes}\n{note}".strip() if creature.notes else note
        creature.save(update_fields=["notes"])

    for card_trait in CharacterCreatureCardTrait.objects.filter(trait_definition__isnull=False).iterator():
        creature = card_to_creature.get(card_trait.card_id)
        if creature is None:
            continue
        CharacterCreatureTrait.objects.update_or_create(
            creature_id=creature.pk,
            trait_id=card_trait.trait_definition_id,
            defaults={
                "trait_level": card_trait.level or 1,
                "active": True,
                "training_trait_type": card_trait.training_trait_type,
                "point_source": card_trait.point_source,
                "point_cost_override": card_trait.point_cost_override,
                "order": card_trait.order,
            },
        )

    command_by_old_id = {}
    for card_command in CharacterCreatureCardCommand.objects.filter(command__isnull=False).iterator():
        creature = card_to_creature.get(card_command.card_id)
        if creature is None:
            continue
        command, _created = CharacterCreatureCommand.objects.update_or_create(
            creature_id=creature.pk,
            command_id=card_command.command_id,
            defaults={"order": card_command.order},
        )
        command_by_old_id[card_command.pk] = command

    for old_prerequisite in CharacterCreatureCardCommandPrerequisite.objects.all().iterator():
        command = command_by_old_id.get(old_prerequisite.command_id)
        prerequisite = command_by_old_id.get(old_prerequisite.prerequisite_id)
        if command is None or prerequisite is None:
            continue
        CharacterCreatureCommandPrerequisite.objects.update_or_create(
            command_id=command.pk,
            prerequisite_id=prerequisite.pk,
            alternative_group=old_prerequisite.alternative_group,
            defaults={"order": old_prerequisite.order},
        )

    for card_increase in CharacterCreatureCardAttributeIncrease.objects.all().iterator():
        creature = card_to_creature.get(card_increase.card_id)
        if creature is None:
            continue
        CharacterCreatureAttributeIncrease.objects.update_or_create(
            creature_id=creature.pk,
            attribute=card_increase.attribute,
            defaults={"amount": card_increase.amount, "notes": card_increase.notes},
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('charsheet', '0219_charactercreaturecardattributeincrease_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactercreaturetrait',
            options={'ordering': ['creature', 'order', 'trait']},
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='max_base_advantage_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='max_base_disadvantage_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='quality',
            field=models.ForeignKey(db_column='quality', default='common', on_delete=django.db.models.deletion.PROTECT, related_name='character_creatures', to='charsheet.quality'),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='source_character_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='charsheet.characteritem'),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='source_character_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='charsheet.charactertechnique'),
        ),
        migrations.AddField(
            model_name='charactercreaturetrait',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreaturetrait',
            name='point_cost_override',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charactercreaturetrait',
            name='point_source',
            field=models.CharField(blank=True, choices=[('', 'Keine Budgetwirkung'), ('base_disadvantage', 'Basis-Schwäche'), ('additional_disadvantage', 'Zusatzschwäche')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='charactercreaturetrait',
            name='training_trait_type',
            field=models.CharField(blank=True, choices=[('', 'Keine Ausbildung'), ('advantage', 'Vorzug'), ('disadvantage', 'Schwäche')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='CharacterCreatureAttributeIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('GE', 'Geschicklichkeit'), ('WA', 'Wahrnehmung'), ('INT', 'Intelligenz'), ('WILL', 'Willenskraft'), ('ST', 'Stärke'), ('KON', 'Konstitution'), ('CHA', 'Charisma'), ('spz.', 'Spezial')], max_length=10)),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_increases', to='charsheet.charactercreature')),
            ],
            options={
                'ordering': ['attribute', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_creature_commands', to='charsheet.creaturecommand')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='charsheet.charactercreature')),
            ],
            options={
                'ordering': ['order', 'command__name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureCommandPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_group', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='charsheet.charactercreaturecommand')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_links', to='charsheet.charactercreaturecommand')),
            ],
            options={
                'ordering': ['alternative_group', 'order', 'prerequisite__command__name'],
            },
        ),
        migrations.CreateModel(
            name='CreatureSourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('item', 'Item'), ('technique', 'Technique')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('creature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='charsheet.creature')),
                ('item_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creature_source_bindings', to='charsheet.item')),
                ('quality', models.ForeignKey(db_column='quality', default='common', help_text="Quality used when this binding is triggered by a technique. Item-triggered creatures use the owned item's quality.", on_delete=django.db.models.deletion.PROTECT, related_name='creature_source_bindings', to='charsheet.quality')),
                ('technique_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creature_source_bindings', to='charsheet.technique')),
            ],
            options={
                'ordering': ['creature__name', 'trigger_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='source_binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_creatures', to='charsheet.creaturesourcebinding'),
        ),
        migrations.RunPython(migrate_creature_cards_to_character_creatures, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='charactercreature',
            constraint=models.UniqueConstraint(condition=models.Q(('source_binding__isnull', False), ('source_character_item__isnull', True), ('source_character_technique__isnull', True)), fields=('owner', 'source_binding'), name='uniq_character_creature_source_binding_legacy'),
        ),
        migrations.AddConstraint(
            model_name='charactercreature',
            constraint=models.UniqueConstraint(condition=models.Q(('source_character_item__isnull', False)), fields=('owner', 'source_binding', 'source_character_item'), name='uniq_character_creature_item_source'),
        ),
        migrations.AddConstraint(
            model_name='charactercreature',
            constraint=models.UniqueConstraint(condition=models.Q(('source_character_technique__isnull', False)), fields=('owner', 'source_binding', 'source_character_technique'), name='uniq_character_creature_technique_source'),
        ),
        migrations.AddConstraint(
            model_name='charactercreatureattributeincrease',
            constraint=models.UniqueConstraint(fields=('creature', 'attribute'), name='uniq_character_creature_attribute_increase'),
        ),
        migrations.AddConstraint(
            model_name='charactercreaturecommand',
            constraint=models.UniqueConstraint(fields=('creature', 'command'), name='uniq_character_creature_command'),
        ),
        migrations.AddConstraint(
            model_name='charactercreaturecommandprerequisite',
            constraint=models.UniqueConstraint(fields=('command', 'prerequisite', 'alternative_group'), name='uniq_character_creature_command_prerequisite_group'),
        ),
        migrations.AddConstraint(
            model_name='creaturesourcebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('item_trigger__isnull', False)), fields=('creature', 'item_trigger'), name='uniq_creature_source_item_binding'),
        ),
        migrations.AddConstraint(
            model_name='creaturesourcebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('technique_trigger__isnull', False)), fields=('creature', 'technique_trigger'), name='uniq_creature_source_technique_binding'),
        ),
    ]
