# Generated by Django 6.0.5 on 2026-07-06 17:32

import django.core.validators
from django.db import migrations, models


def backfill_swimming_speed_block(apps, schema_editor):
    Creature = apps.get_model('charsheet', 'Creature')
    Creature.objects.filter(
        swimming_speed__isnull=False,
        combat_swimming_speed__isnull=True,
        march_swimming_speed__isnull=True,
        sprint_swimming_speed__isnull=True,
    ).update(
        combat_swimming_speed=models.F('swimming_speed'),
        march_swimming_speed=models.F('swimming_speed'),
        sprint_swimming_speed=models.F('swimming_speed'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0222_creature_movement_speeds_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='combat_swimming_speed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kampf-Schwimmen'),
        ),
        migrations.AddField(
            model_name='creature',
            name='march_swimming_speed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marsch-Schwimmen'),
        ),
        migrations.AddField(
            model_name='creature',
            name='sprint_swimming_speed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sprint-Schwimmen'),
        ),
        migrations.RunPython(backfill_swimming_speed_block, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='creature',
            name='combat_speed',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='march_speed',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='sprint_speed',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='swimming_speed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Schwimmgeschwindigkeit'),
        ),
    ]
