# Generated by Django 6.0.5 on 2026-07-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0229_creature_wound_thresholds_override_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE charsheet_creaturetraitsemanticeffect "
                        "ADD COLUMN IF NOT EXISTS condition_text text NOT NULL DEFAULT ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='creaturetraitsemanticeffect',
                    name='condition_text',
                    field=models.TextField(blank=True, default='', help_text="Optionaler Text fuer situative Effekte, z. B. 'nur bei Dunkelheit'."),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='mode',
            field=models.CharField(default='flat', help_text="Flat oder skaliert; wird ueber 'pro Trait-Level anwenden' gesetzt.", max_length=20, verbose_name='Berechnungsmodus'),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='operator',
            field=models.CharField(choices=[('flat_add', 'flat_add'), ('flat_sub', 'flat_sub'), ('multiply', 'multiply'), ('override', 'override'), ('min_value', 'min_value'), ('max_value', 'max_value'), ('set_flag', 'set_flag'), ('unset_flag', 'unset_flag'), ('add_tag', 'add_tag'), ('remove_tag', 'remove_tag'), ('grant_capability', 'grant_capability'), ('remove_capability', 'remove_capability'), ('grant_immunity', 'grant_immunity'), ('grant_vulnerability', 'grant_vulnerability'), ('change_resource_cap', 'change_resource_cap'), ('change_starting_funds', 'change_starting_funds'), ('change_appearance_class', 'change_appearance_class'), ('change_social_status', 'change_social_status'), ('reroll_grant', 'reroll_grant'), ('reroll_forbid', 'reroll_forbid'), ('repeat_action_allowed', 'repeat_action_allowed'), ('action_cost_change', 'action_cost_change'), ('conditional_bonus', 'conditional_bonus'), ('conditional_penalty', 'conditional_penalty')], default='flat_add', help_text='Wird normalerweise ueber die einfache Rechenart-Auswahl gepflegt.', max_length=40, verbose_name='Rechenart'),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_special_skill', 'creature_special_skill')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich'),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='target_key',
            field=models.CharField(blank=True, default='', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=120, verbose_name='Technischer Zielwert'),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='target_skills',
            field=models.ManyToManyField(blank=True, help_text='Optional concrete skill targets. Use this instead of target_key for multi-skill effects.', related_name='%(class)s_targeted_skills', to='charsheet.skill'),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='value',
            field=models.CharField(blank=True, default='', help_text='Wird normalerweise ueber das einfache Zahlenfeld gepflegt.', max_length=200, verbose_name='Zahl'),
        ),
        migrations.CreateModel(
            name='CreatureSpecialSkillSemanticEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('target_domain', models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_special_skill', 'creature_special_skill')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich')),
                ('target_key', models.CharField(blank=True, default='', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=120, verbose_name='Technischer Zielwert')),
                ('operator', models.CharField(choices=[('flat_add', 'flat_add'), ('flat_sub', 'flat_sub'), ('multiply', 'multiply'), ('override', 'override'), ('min_value', 'min_value'), ('max_value', 'max_value'), ('set_flag', 'set_flag'), ('unset_flag', 'unset_flag'), ('add_tag', 'add_tag'), ('remove_tag', 'remove_tag'), ('grant_capability', 'grant_capability'), ('remove_capability', 'remove_capability'), ('grant_immunity', 'grant_immunity'), ('grant_vulnerability', 'grant_vulnerability'), ('change_resource_cap', 'change_resource_cap'), ('change_starting_funds', 'change_starting_funds'), ('change_appearance_class', 'change_appearance_class'), ('change_social_status', 'change_social_status'), ('reroll_grant', 'reroll_grant'), ('reroll_forbid', 'reroll_forbid'), ('repeat_action_allowed', 'repeat_action_allowed'), ('action_cost_change', 'action_cost_change'), ('conditional_bonus', 'conditional_bonus'), ('conditional_penalty', 'conditional_penalty')], default='flat_add', help_text='Wird normalerweise ueber die einfache Rechenart-Auswahl gepflegt.', max_length=40, verbose_name='Rechenart')),
                ('mode', models.CharField(default='flat', help_text="Flat oder skaliert; wird ueber 'pro Trait-Level anwenden' gesetzt.", max_length=20, verbose_name='Berechnungsmodus')),
                ('value', models.CharField(blank=True, default='', help_text='Wird normalerweise ueber das einfache Zahlenfeld gepflegt.', max_length=200, verbose_name='Zahl')),
                ('value_min', models.IntegerField(blank=True, null=True)),
                ('value_max', models.IntegerField(blank=True, null=True)),
                ('formula', models.CharField(blank=True, default='', max_length=200)),
                ('scaling', models.JSONField(blank=True, default=dict)),
                ('stack_behavior', models.CharField(choices=[('stack', 'stack'), ('highest', 'highest'), ('lowest', 'lowest'), ('override', 'override'), ('unique_by_source', 'unique_by_source')], default='stack', max_length=40)),
                ('condition_set', models.JSONField(blank=True, default=dict)),
                ('active_flag', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('condition_text', models.TextField(blank=True, default='', help_text="Optionaler Text fuer situative Effekte, z. B. 'nur bei Dunkelheit'.")),
                ('notes', models.TextField(blank=True, default='')),
                ('rules_text', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('internal', 'internal'), ('story', 'story')], default='public', max_length=20)),
                ('hidden', models.BooleanField(default=False)),
                ('sheet_relevant', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('special_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_effects', to='charsheet.creaturespecialskill')),
                ('target_skills', models.ManyToManyField(blank=True, help_text='Optional concrete skill targets. Use this instead of target_key for multi-skill effects.', related_name='%(class)s_targeted_skills', to='charsheet.skill')),
            ],
            options={
                'ordering': ['special_skill', 'sort_order', 'id'],
            },
        ),
    ]
