# Generated by Codex on 2026-07-14

from django.db import migrations, models


def copy_single_skill_category_to_multi(apps, schema_editor):
    CreatureTraitChoiceDefinition = apps.get_model("charsheet", "CreatureTraitChoiceDefinition")
    for definition in CreatureTraitChoiceDefinition.objects.exclude(allowed_skill_category_id__isnull=True):
        definition.allowed_skill_categories.add(definition.allowed_skill_category_id)


def remove_copied_skill_categories(apps, schema_editor):
    CreatureTraitChoiceDefinition = apps.get_model("charsheet", "CreatureTraitChoiceDefinition")
    for definition in CreatureTraitChoiceDefinition.objects.exclude(allowed_skill_category_id__isnull=True):
        definition.allowed_skill_categories.remove(definition.allowed_skill_category_id)


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0230_creaturetraitsemanticeffect_condition_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creaturetraitchoicedefinition",
            name="allowed_skill_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional filter restricting skill choices to one or more skill categories.",
                related_name="creature_trait_multi_choice_definitions",
                to="charsheet.skillcategory",
            ),
        ),
        migrations.AddField(
            model_name="creaturetraitchoicedefinition",
            name="allowed_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional concrete skills allowed for this choice definition.",
                related_name="creature_trait_choice_definitions",
                to="charsheet.skill",
            ),
        ),
        migrations.RunPython(copy_single_skill_category_to_multi, remove_copied_skill_categories),
    ]
