# Generated by Codex on 2026-07-14

from django.db import migrations, models


OPERATOR_CHOICES = [
    ("flat_add", "flat_add"),
    ("flat_sub", "flat_sub"),
    ("multiply", "multiply"),
    ("floor_divide", "floor_divide"),
    ("override", "override"),
    ("min_value", "min_value"),
    ("max_value", "max_value"),
    ("set_flag", "set_flag"),
    ("unset_flag", "unset_flag"),
    ("add_tag", "add_tag"),
    ("remove_tag", "remove_tag"),
    ("grant_capability", "grant_capability"),
    ("remove_capability", "remove_capability"),
    ("grant_immunity", "grant_immunity"),
    ("grant_vulnerability", "grant_vulnerability"),
    ("change_resource_cap", "change_resource_cap"),
    ("change_starting_funds", "change_starting_funds"),
    ("change_appearance_class", "change_appearance_class"),
    ("change_social_status", "change_social_status"),
    ("reroll_grant", "reroll_grant"),
    ("reroll_forbid", "reroll_forbid"),
    ("repeat_action_allowed", "repeat_action_allowed"),
    ("action_cost_change", "action_cost_change"),
    ("conditional_bonus", "conditional_bonus"),
    ("conditional_penalty", "conditional_penalty"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0231_creature_trait_choice_definition_multi_skill_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traitsemanticeffect",
            name="operator",
            field=models.CharField(choices=OPERATOR_CHOICES, default="flat_add", max_length=40),
        ),
        migrations.AlterField(
            model_name="techniquesemanticeffect",
            name="operator",
            field=models.CharField(choices=OPERATOR_CHOICES, default="flat_add", max_length=40),
        ),
        migrations.AlterField(
            model_name="creaturetraitsemanticeffect",
            name="operator",
            field=models.CharField(
                choices=OPERATOR_CHOICES,
                default="flat_add",
                help_text="Wird normalerweise ueber die einfache Rechenart-Auswahl gepflegt.",
                max_length=40,
                verbose_name="Rechenart",
            ),
        ),
        migrations.AlterField(
            model_name="creaturespecialskillsemanticeffect",
            name="operator",
            field=models.CharField(
                choices=OPERATOR_CHOICES,
                default="flat_add",
                help_text="Wird normalerweise ueber die einfache Rechenart-Auswahl gepflegt.",
                max_length=40,
                verbose_name="Rechenart",
            ),
        ),
    ]
