# Generated by Django 6.0.5 on 2026-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0233_creature_trait_choice_special_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturetraitchoicedefinition',
            name='allow_all_creature_special_skills',
            field=models.BooleanField(default=False, help_text='Offer every creature-only skill in addition to the normal skill choices.'),
        ),
    ]
