# Generated by Django 6.0.5 on 2026-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0238_creature_trait_choice_multi_derived_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creaturespecialskillsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich'),
        ),
        migrations.AlterField(
            model_name='creaturetraitchoicedefinition',
            name='target_kind',
            field=models.CharField(choices=[('attribute', 'Attribute'), ('skill', 'Skill'), ('skill_category', 'Skill Category'), ('derived_stat', 'Derived Stat'), ('resource', 'Resource'), ('proficiency_group', 'Proficiency Group'), ('item', 'Item'), ('item_category', 'Item Category'), ('creature_attack', 'Creature Attack'), ('specialization', 'Specialization'), ('text', 'Free Text'), ('entity', 'Other Entity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich'),
        ),
    ]
