# Generated by Django 6.0.5 on 2026-07-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0239_alter_creaturespecialskillsemanticeffect_target_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturetraitdefinition',
            name='hide_from_creature_training',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, wird diese Faehigkeit nicht als neue Ausbildungsoption im Kreaturentraining angeboten.', verbose_name='Nicht im Kreaturentraining anbieten'),
        ),
    ]
