# Generated by Django 6.0.5 on 2026-07-14 19:02

import django.db.models.deletion
from django.db import migrations, models


def create_default_attack_types(apps, schema_editor):
    CreatureAttackType = apps.get_model("charsheet", "CreatureAttackType")
    CreatureAttack = apps.get_model("charsheet", "CreatureAttack")
    defaults = [
        ("natural", "Natuerliche Angriffsart"),
        ("weapon", "Waffenangriff"),
        ("special", "Spezialangriff"),
    ]
    created_types = {}
    for slug, name in defaults:
        attack_type, _created = CreatureAttackType.objects.get_or_create(
            slug=slug,
            defaults={"name": name},
        )
        created_types[slug] = attack_type
    CreatureAttack.objects.filter(attack_type__isnull=True).update(attack_type_id=created_types["natural"].pk)


def remove_default_attack_types(apps, schema_editor):
    CreatureAttackType = apps.get_model("charsheet", "CreatureAttackType")
    CreatureAttack = apps.get_model("charsheet", "CreatureAttack")
    CreatureAttack.objects.filter(attack_type__slug__in=["natural", "weapon", "special"]).update(attack_type=None)
    CreatureAttackType.objects.filter(slug__in=["natural", "weapon", "special"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0241_alter_creaturespecialskillsemanticeffect_target_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureAttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='creaturespecialskillsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack'), ('creature_attack_damage', 'creature_attack_damage'), ('creature_attack_type_damage', 'creature_attack_type_damage')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich'),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack'), ('creature_attack_damage', 'creature_attack_damage'), ('creature_attack_type_damage', 'creature_attack_type_damage')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich'),
        ),
        migrations.AddField(
            model_name='creatureattack',
            name='attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attacks', to='charsheet.creatureattacktype', verbose_name='Angriffsart'),
        ),
        migrations.RunPython(create_default_attack_types, remove_default_attack_types),
    ]
