# Generated by Django 6.0.5 on 2026-07-14 19:12

from django.db import migrations, models


def copy_single_attribute_to_multi(apps, schema_editor):
    CreatureTraitChoiceDefinition = apps.get_model("charsheet", "CreatureTraitChoiceDefinition")
    for definition in CreatureTraitChoiceDefinition.objects.exclude(allowed_attribute_id__isnull=True):
        definition.allowed_attributes.add(definition.allowed_attribute_id)


def remove_copied_attributes(apps, schema_editor):
    CreatureTraitChoiceDefinition = apps.get_model("charsheet", "CreatureTraitChoiceDefinition")
    for definition in CreatureTraitChoiceDefinition.objects.exclude(allowed_attribute_id__isnull=True):
        definition.allowed_attributes.remove(definition.allowed_attribute_id)


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0242_creatureattacktype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturetraitchoicedefinition',
            name='allowed_attributes',
            field=models.ManyToManyField(blank=True, help_text='Optional filter restricting attribute choices to one or more attributes.', related_name='creature_trait_multi_choice_definitions', to='charsheet.attribute'),
        ),
        migrations.RunPython(copy_single_attribute_to_multi, remove_copied_attributes),
    ]
