# Generated by Django 5.2.11 on 2026-07-20 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0243_creaturetraitchoicedefinition_allowed_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='original_owner_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originally_owned_items', to='charsheet.character'),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='ownership_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='provenance_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ItemTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_provenance_id', models.UUIDField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt'), ('expired', 'Abgelaufen'), ('recalled', 'Zurückgerufen')], default='pending', max_length=16)),
                ('item_snapshot', models.JSONField(default=dict)),
                ('sender_snapshot', models.JSONField(default=dict)),
                ('recipient_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='charsheet.characteritem')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_item_transfers', to='charsheet.character')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_item_transfers', to='charsheet.character')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemOwnershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_provenance_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('created', 'Übergabe erstellt'), ('accepted', 'Übergabe angenommen'), ('declined', 'Übergabe abgelehnt'), ('expired', 'Automatisch zurückgegeben'), ('recalled', 'Übergabe zurückgerufen'), ('enforced', 'Zwangsvollstreckung'), ('permission_granted', 'Recht erteilt'), ('permission_revoked', 'Recht widerrufen'), ('permission_invalidated', 'Recht durch Besitzerwechsel beendet'), ('destroyed', 'Item endgültig entfernt')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_ownership_actions', to='charsheet.character')),
                ('original_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_origin_history', to='charsheet.character')),
                ('from_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_ownership_departures', to='charsheet.character')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_events', to='charsheet.characteritem')),
                ('to_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_ownership_arrivals', to='charsheet.character')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='charsheet.itemtransfer')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransferNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_provenance_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='charsheet.itemtransfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_transfer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('consume_final', 'Letzte Einheit verbrauchen'), ('sell', 'Verkaufen'), ('destroy', 'Zerstören')], max_length=20)),
                ('ownership_version', models.PositiveIntegerField(blank=True, null=True)),
                ('irrevocable', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_item_permissions', to='charsheet.character')),
                ('grantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_item_permissions', to='charsheet.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='charsheet.characteritem')),
            ],
            options={
                'ordering': ['item', 'permission', '-granted_at'],
                'indexes': [models.Index(fields=['item', 'permission'], name='item_permission_lookup')],
            },
        ),
        migrations.AddIndex(
            model_name='itemtransfer',
            index=models.Index(fields=['recipient', 'status'], name='transfer_recipient_status'),
        ),
        migrations.AddIndex(
            model_name='itemtransfer',
            index=models.Index(fields=['sender', 'status'], name='transfer_sender_status'),
        ),
        migrations.AddConstraint(
            model_name='itemtransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('item__isnull', False), ('status', 'pending')), fields=('item',), name='uniq_pending_transfer_per_item'),
        ),
    ]
