# Generated by Django 6.0.5 on 2026-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0250_character_split_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturesourcebinding',
            name='selection_mode',
            field=models.CharField(choices=[('fixed', 'Feste Kreatur'), ('character_choice', 'Charakter wählt oder erstellt eine Kreatur')], default='fixed', help_text='Nur der Auswahlmodus überlässt dem Charakter die Wahl einer DB-Vorlage oder einer freien Tierform.', max_length=24),
        ),
    ]
