# Generated by Django 6.0.5 on 2026-07-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0251_creaturesourcebinding_selection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercreature',
            name='source_selection_completed',
            field=models.BooleanField(default=False, help_text='Nur für frei wählbare Technik-Bindungen: Die Vorlagen- oder Freikartenwahl wurde abgeschlossen.'),
        ),
    ]
