# Generated by Django 6.0.5 on 2026-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0252_charactercreature_source_selection_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturesourcebinding',
            name='choice_label',
            field=models.CharField(blank=True, default='Tiergestalt', help_text='Wording auf der Auswahlkarte, z. B. Tiergestalt oder Tiergefährte.', max_length=100, verbose_name='Bezeichnung der Kreaturenwahl'),
        ),
    ]
