# Generated by Django 6.0.5 on 2026-07-23 09:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def make_existing_group_names_unique(apps, schema_editor):
    GameGroup = apps.get_model("charsheet", "GameGroup")
    used = set()
    for group in GameGroup.objects.order_by("id"):
        base = " ".join(str(group.name or "").split()) or "Spielgruppe"
        candidate = base[:150]
        suffix = 2
        while candidate.casefold() in used:
            marker = f" ({suffix})"
            candidate = f"{base[:150 - len(marker)]}{marker}"
            suffix += 1
        used.add(candidate.casefold())
        if group.name != candidate:
            GameGroup.objects.filter(pk=group.pk).update(name=candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0254_game_groups_and_group_inventory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(make_existing_group_names_unique, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="gamegroup",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="uniq_game_group_name_ci",
            ),
        ),
    ]
