# Generated by Django 6.0.5 on 2026-07-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0255_gamegroup_uniq_game_group_name_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransfer',
            name='recipient_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_item_transfers', to='charsheet.gamegroup'),
        ),
        migrations.AddField(
            model_name='itemtransfer',
            name='transfer_kind',
            field=models.CharField(choices=[('ownership', 'Gegenstandsübergabe'), ('gm_edit', 'SL-Bearbeitung')], default='ownership', max_length=16),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_item_transfers', to='charsheet.character'),
        ),
        migrations.AddIndex(
            model_name='itemtransfer',
            index=models.Index(fields=['recipient_group', 'status'], name='transfer_group_status'),
        ),
        migrations.AddConstraint(
            model_name='itemtransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient_group__isnull', True), ('transfer_kind', 'ownership')), models.Q(('recipient__isnull', True), ('recipient_group__isnull', False), ('transfer_kind', 'gm_edit')), _connector='OR'), name='transfer_recipient_matches_kind'),
        ),
    ]
