# Generated by Django 6.0.5 on 2026-07-24 16:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0273_game_group_creature_current_kp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('activation_type', models.CharField(choices=[('action', 'Aktion'), ('spontaneous', 'Spontan')], default='action', max_length=20)),
                ('purchase_cost', models.PositiveSmallIntegerField(default=8, help_text='CP bei der Charaktererschaffung und EP beim späteren Lernen.', validators=[django.core.validators.MinValueValidator(1)])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='charsheet.school')),
            ],
            options={
                'ordering': ['school__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('kp', 'KP'), ('lp', 'LP'), ('ep', 'EP'), ('fame', 'Ruhmpunkt'), ('custom', 'Frei definiert')], max_length=20)),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('custom_label', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('alternative_group', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='charsheet.lesson')),
            ],
            options={
                'ordering': ['lesson__school__name', 'lesson__name', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonRequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('operator', models.CharField(choices=[('and', 'UND'), ('or', 'ODER')], default='and', max_length=8)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_groups', to='charsheet.lesson')),
            ],
            options={
                'ordering': ['lesson__school__name', 'lesson__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LessonRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('school', 'Schule'), ('skill', 'Fertigkeit'), ('technique', 'Technik'), ('lesson', 'Lektion')], max_length=20)),
                ('minimum_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='charsheet.lesson')),
                ('required_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='required_by_requirements', to='charsheet.lesson')),
                ('required_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='charsheet.school')),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='charsheet.skill')),
                ('required_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='charsheet.technique')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='charsheet.lessonrequirementgroup')),
            ],
            options={
                'ordering': ['lesson__school__name', 'lesson__name', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_type', models.CharField(choices=[('creation', 'Charaktererschaffung'), ('experience', 'Mit EP gelernt'), ('manual', 'Manuell vergeben')], default='manual', max_length=20)),
                ('paid_ep', models.PositiveIntegerField(default=0)),
                ('learned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_lessons', to='charsheet.character')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_entries', to='charsheet.lesson')),
            ],
            options={
                'ordering': ['character', 'lesson__school__name', 'lesson__name'],
                'constraints': [models.UniqueConstraint(fields=('character', 'lesson'), name='uniq_character_lesson')],
            },
        ),
        migrations.AddConstraint(
            model_name='lessonrequirementgroup',
            constraint=models.UniqueConstraint(fields=('lesson', 'number'), name='uniq_lesson_requirement_group_number'),
        ),
    ]
