# Generated by Codex on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0274_lesson_lessoncost_lessonrequirementgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="fluff_quote",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optionales Fluff-Zitat, das in Tooltips und auf dem Charakterbogen angezeigt wird.",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="fluff_quote_speaker",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionale Person oder Quelle des Fluff-Zitats.",
                max_length=200,
            ),
        ),
    ]
