# Generated by Codex on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0275_lesson_fluff_quote_and_speaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="technique",
            field=models.ForeignKey(
                blank=True,
                help_text="Technik dieser Kampfschule, die zum Erlernen der Lektion vorausgesetzt wird.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="charsheet.technique",
            ),
        ),
    ]
