# Generated by Codex on 2026-07-26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0278_lesson_source_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamegrouptable",
            name="window_width",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(320),
                    django.core.validators.MaxValueValidator(6000),
                ],
            ),
        ),
    ]
