# Generated by Codex on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0280_game_group_table_column_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamegrouptable",
            name="detached_x",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="gamegrouptable",
            name="detached_y",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="gamegrouptable",
            name="is_detached",
            field=models.BooleanField(default=False),
        ),
    ]
