# Generated by Codex on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0281_game_group_table_detached_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamegrouptable",
            name="is_stacked",
            field=models.BooleanField(default=False),
        ),
    ]
