# Generated by Django 6.0.5 on 2026-07-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0283_game_group_table_creator_and_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorstats',
            name='auto_generate_components',
            field=models.BooleanField(default=False, help_text='Benannte Komponenten beim Speichern automatisch erzeugen und synchronisieren.'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='component_type',
            field=models.CharField(blank=True, choices=[('helmet', 'Helm'), ('torso', 'Torso'), ('arm_left', 'Arm links'), ('arm_right', 'Arm rechts'), ('hand_left', 'Hand links'), ('hand_right', 'Hand rechts'), ('leg_left', 'Bein links'), ('leg_right', 'Bein rechts'), ('foot_left', 'Fuß links'), ('foot_right', 'Fuß rechts')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_arm_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_arm_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_eyes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_foot_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_foot_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_hand_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_hand_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_leg_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_leg_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_neck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_organs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_soft_tissue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='covers_torso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='is_set',
            field=models.BooleanField(default=False, help_text='Setvorlage, aus der physische Rüstungsteile erzeugt werden.'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='parent_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='charsheet.armorstats'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='zone_rs_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Optionale RS-Abweichungen einzelner abgedeckter Zonen.'),
        ),
        migrations.AddField(
            model_name='charactercreatureitem',
            name='armor_zone_rs_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='armor_zone_rs_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='weight_override',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddConstraint(
            model_name='armorstats',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_set__isnull', False)), fields=('parent_set', 'component_type'), name='uniq_armor_component_per_set'),
        ),
    ]
