# Generated by Django 6.0.5 on 2026-07-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0285_migrate_armor_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armorstats',
            name='rs_arm_left',
        ),
        migrations.RemoveField(
            model_name='armorstats',
            name='rs_arm_right',
        ),
        migrations.RemoveField(
            model_name='armorstats',
            name='rs_head',
        ),
        migrations.RemoveField(
            model_name='armorstats',
            name='rs_leg_left',
        ),
        migrations.RemoveField(
            model_name='armorstats',
            name='rs_leg_right',
        ),
        migrations.RemoveField(
            model_name='armorstats',
            name='rs_torso',
        ),
        migrations.RemoveField(
            model_name='charactercreatureitem',
            name='armor_rs_arm_left_override',
        ),
        migrations.RemoveField(
            model_name='charactercreatureitem',
            name='armor_rs_arm_right_override',
        ),
        migrations.RemoveField(
            model_name='charactercreatureitem',
            name='armor_rs_head_override',
        ),
        migrations.RemoveField(
            model_name='charactercreatureitem',
            name='armor_rs_leg_left_override',
        ),
        migrations.RemoveField(
            model_name='charactercreatureitem',
            name='armor_rs_leg_right_override',
        ),
        migrations.RemoveField(
            model_name='charactercreatureitem',
            name='armor_rs_torso_override',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='armor_rs_arm_left_override',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='armor_rs_arm_right_override',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='armor_rs_head_override',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='armor_rs_leg_left_override',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='armor_rs_leg_right_override',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='armor_rs_torso_override',
        ),
    ]
