# Generated by Django 6.0.5 on 2026-07-28 12:33

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


ZONE_FIELDS = (
    "head", "face", "eyes", "neck", "torso", "organs", "soft_tissue",
    "arm_left", "hand_left", "leg_left", "foot_left",
    "arm_right", "hand_right", "leg_right", "foot_right",
)

COMPONENTS = (
    ("helmet", "Helm", Decimal("0.10"), Decimal("0.20"), ("head", "face", "eyes", "neck")),
    ("torso", "Torso", Decimal("0.36"), Decimal("0.30"), ("torso", "organs", "soft_tissue")),
    ("arm_left", "Arm links", Decimal("0.075"), Decimal("0.075"), ("arm_left",)),
    ("arm_right", "Arm rechts", Decimal("0.075"), Decimal("0.075"), ("arm_right",)),
    ("hand_left", "Handschuh links", Decimal("0.03"), Decimal("0.05"), ("hand_left",)),
    ("hand_right", "Handschuh rechts", Decimal("0.03"), Decimal("0.05"), ("hand_right",)),
    ("leg_left", "Bein links", Decimal("0.125"), Decimal("0.075"), ("leg_left",)),
    ("leg_right", "Bein rechts", Decimal("0.125"), Decimal("0.075"), ("leg_right",)),
    ("foot_left", "Schuh links", Decimal("0.04"), Decimal("0.05"), ("foot_left",)),
    ("foot_right", "Schuh rechts", Decimal("0.04"), Decimal("0.05"), ("foot_right",)),
)


def migrate_generation_switch(apps, schema_editor):
    ArmorStats = apps.get_model("charsheet", "ArmorStats")
    for armor in ArmorStats.objects.all().iterator():
        armor.suppress_component_generation = not bool(armor.is_set)
        armor.save(update_fields=["suppress_component_generation"])


def restore_generation_switches(apps, schema_editor):
    ArmorStats = apps.get_model("charsheet", "ArmorStats")
    for armor in ArmorStats.objects.all().iterator():
        armor.is_set = not bool(armor.suppress_component_generation)
        armor.auto_generate_components = armor.is_set
        armor.save(update_fields=["is_set", "auto_generate_components"])


def _unique_component_name(Item, parent_item, label):
    base_name = f"{parent_item.name} – {label}"
    same_catalog = Item.objects.filter(name=base_name)
    if parent_item.catalog_group_id:
        same_catalog = same_catalog.filter(catalog_group_id=parent_item.catalog_group_id)
    else:
        same_catalog = same_catalog.filter(catalog_group__isnull=True)
    if not same_catalog.exists():
        return base_name
    return f"{base_name} (Set {parent_item.pk})"


def create_missing_components(apps, schema_editor):
    """Backfill components skipped by the former magic-item restriction."""
    ArmorStats = apps.get_model("charsheet", "ArmorStats")
    Item = apps.get_model("charsheet", "Item")

    roots = (
        ArmorStats.objects.select_related("item")
        .filter(suppress_component_generation=False, parent_set__isnull=True)
        .order_by("pk")
    )
    for armor in roots:
        selected = []
        for component_type, label, weight_share, price_share, zones in COMPONENTS:
            covered_zones = tuple(
                zone for zone in zones if getattr(armor, f"covers_{zone}", False)
            )
            if covered_zones:
                selected.append((component_type, label, weight_share, price_share, covered_zones))
        if not selected:
            continue

        total_weight_share = sum((row[2] for row in selected), Decimal("0"))
        total_price_share = sum((row[3] for row in selected), Decimal("0"))
        weights = [
            (Decimal(armor.item.weight) * row[2] / total_weight_share).quantize(
                Decimal("0.001"), rounding=ROUND_HALF_UP
            )
            for row in selected
        ]
        prices = [
            int(
                (Decimal(armor.item.price) * row[3] / total_price_share).quantize(
                    Decimal("1"), rounding=ROUND_HALF_UP
                )
            )
            for row in selected
        ]
        weights[-1] += Decimal(armor.item.weight) - sum(weights, Decimal("0"))
        prices[-1] += int(armor.item.price) - sum(prices)

        for index, (component_type, label, _weight_share, _price_share, covered_zones) in enumerate(selected):
            if ArmorStats.objects.filter(parent_set=armor, component_type=component_type).exists():
                continue
            component_item = Item.objects.create(
                name=_unique_component_name(Item, armor.item, label),
                price=prices[index],
                item_type="armor",
                description=f"Physisches Rüstungsteil des Sets {armor.item.name}.",
                stackable=False,
                is_consumable=False,
                is_magic=False,
                not_buyable=armor.item.not_buyable,
                not_sellable=armor.item.not_sellable,
                default_quality_id=armor.item.default_quality_id,
                weight=weights[index],
                size_class=armor.item.size_class,
                catalog_group_id=armor.item.catalog_group_id,
            )
            component_item.runes.add(*armor.item.runes.all())
            ArmorStats.objects.create(
                item=component_item,
                rs_total=armor.rs_total,
                encumbrance=0,
                min_st=max(1, int(armor.min_st or 1)),
                suppress_component_generation=True,
                parent_set=armor,
                component_type=component_type,
                zone_rs_overrides={},
                **{
                    f"covers_{zone}": zone in covered_zones
                    for zone in ZONE_FIELDS
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0286_remove_armorstats_rs_arm_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorstats',
            name='suppress_component_generation',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden aus dieser Rüstung keine physischen Einzelteile erzeugt.'),
        ),
        migrations.RunPython(migrate_generation_switch, restore_generation_switches),
        migrations.RemoveField(
            model_name='armorstats',
            name='auto_generate_components',
        ),
        migrations.RemoveField(
            model_name='armorstats',
            name='is_set',
        ),
        migrations.RunPython(create_missing_components, migrations.RunPython.noop),
    ]
