# Generated by Django 6.0.5 on 2026-07-28 13:31

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


ZONE_FIELDS = (
    'head',
    'face',
    'eyes',
    'neck',
    'torso',
    'organs',
    'soft_tissue',
    'arm_left',
    'hand_left',
    'leg_left',
    'foot_left',
    'arm_right',
    'hand_right',
    'leg_right',
    'foot_right',
)

COMPONENT_SPECS = (
    ('helmet', 'Helm', ('head', 'face', 'eyes', 'neck'), Decimal('0.10'), Decimal('0.20')),
    ('torso', 'Torso', ('torso', 'organs', 'soft_tissue'), Decimal('0.36'), Decimal('0.30')),
    ('arm_left', 'Arm links', ('arm_left', 'hand_left'), Decimal('0'), Decimal('0')),
    ('arm_right', 'Arm rechts', ('arm_right', 'hand_right'), Decimal('0'), Decimal('0')),
    ('leg_left', 'Bein links', ('leg_left', 'foot_left'), Decimal('0'), Decimal('0')),
    ('leg_right', 'Bein rechts', ('leg_right', 'foot_right'), Decimal('0'), Decimal('0')),
)

ZONE_SHARES = {
    'arm_left': (Decimal('0.075'), Decimal('0.075')),
    'arm_right': (Decimal('0.075'), Decimal('0.075')),
    'hand_left': (Decimal('0.03'), Decimal('0.05')),
    'hand_right': (Decimal('0.03'), Decimal('0.05')),
    'leg_left': (Decimal('0.125'), Decimal('0.075')),
    'leg_right': (Decimal('0.125'), Decimal('0.075')),
    'foot_left': (Decimal('0.04'), Decimal('0.05')),
    'foot_right': (Decimal('0.04'), Decimal('0.05')),
}

SECONDARY_COMPONENTS = {
    'hand_left': 'arm_left',
    'hand_right': 'arm_right',
    'foot_left': 'leg_left',
    'foot_right': 'leg_right',
}


def _move_item_references(Item, source_item_id, target_item_id):
    """Preserve any inventory use of a legacy hand/foot catalog item."""
    for relation in Item._meta.related_objects:
        if relation.related_model._meta.label_lower == 'charsheet.armorstats':
            continue
        relation.related_model.objects.filter(
            **{relation.field.attname: source_item_id}
        ).update(**{relation.field.attname: target_item_id})


def merge_limb_components(apps, schema_editor):
    ArmorStats = apps.get_model('charsheet', 'ArmorStats')
    Item = apps.get_model('charsheet', 'Item')

    for parent in ArmorStats.objects.filter(parent_set__isnull=True).select_related('item'):
        components = {
            component.component_type: component
            for component in ArmorStats.objects.filter(parent_set_id=parent.pk).select_related('item')
        }

        for secondary_type, primary_type in SECONDARY_COMPONENTS.items():
            secondary = components.get(secondary_type)
            if secondary is None:
                continue
            primary = components.get(primary_type)
            if primary is None:
                secondary.component_type = primary_type
                secondary.save(update_fields=['component_type'])
                components[primary_type] = secondary
            else:
                _move_item_references(Item, secondary.item_id, primary.item_id)
                secondary.item.delete()
            components.pop(secondary_type, None)

        selected = []
        for component_type, label, zones, fixed_weight_share, fixed_price_share in COMPONENT_SPECS:
            covered_zones = tuple(
                zone for zone in zones if getattr(parent, f'covers_{zone}', False)
            )
            if not covered_zones:
                continue
            if component_type.startswith(('arm_', 'leg_')):
                weight_share = sum(
                    (ZONE_SHARES[zone][0] for zone in covered_zones),
                    Decimal('0'),
                )
                price_share = sum(
                    (ZONE_SHARES[zone][1] for zone in covered_zones),
                    Decimal('0'),
                )
            else:
                weight_share = fixed_weight_share
                price_share = fixed_price_share
            selected.append(
                (component_type, label, covered_zones, weight_share, price_share)
            )

        if not selected:
            continue

        total_weight_share = sum(
            (weight_share for _type, _label, _zones, weight_share, _price_share in selected),
            Decimal('0'),
        )
        total_price_share = sum(
            (price_share for _type, _label, _zones, _weight_share, price_share in selected),
            Decimal('0'),
        )
        weights = [
            (Decimal(parent.item.weight) * weight_share / total_weight_share).quantize(
                Decimal('0.001'),
                rounding=ROUND_HALF_UP,
            )
            for _type, _label, _zones, weight_share, _price_share in selected
        ]
        prices = [
            int(
                (Decimal(parent.item.price) * price_share).quantize(
                    Decimal('1'),
                    rounding=ROUND_HALF_UP,
                )
            )
            for _type, _label, _zones, _weight_share, price_share in selected
        ]
        weights[-1] += Decimal(parent.item.weight) - sum(weights, Decimal('0'))
        target_price = int(
            (Decimal(parent.item.price) * total_price_share).quantize(
                Decimal('1'),
                rounding=ROUND_HALF_UP,
            )
        )
        prices[-1] += target_price - sum(prices)

        for index, (component_type, label, covered_zones, _weight_share, _price_share) in enumerate(selected):
            component = components.get(component_type)
            if component is None:
                continue
            item = component.item
            item.name = f'{parent.item.name} – {label}'
            item.weight = weights[index]
            item.price = prices[index]
            item.save(update_fields=['name', 'weight', 'price'])

            coverage_updates = {
                f'covers_{zone}': zone in covered_zones
                for zone in ZONE_FIELDS
            }
            for field_name, value in coverage_updates.items():
                setattr(component, field_name, value)
            component.save(update_fields=list(coverage_updates))


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0288_reprice_armor_components'),
    ]

    operations = [
        migrations.RunPython(merge_limb_components, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='armorstats',
            name='component_type',
            field=models.CharField(blank=True, choices=[('helmet', 'Helm'), ('torso', 'Torso'), ('arm_left', 'Arm links'), ('arm_right', 'Arm rechts'), ('leg_left', 'Bein links'), ('leg_right', 'Bein rechts')], default='', max_length=20),
        ),
    ]
