# Generated by Django 6.0.5 on 2026-07-28 13:35

from django.db import migrations, models


def configure_bestiarius_prices(apps, schema_editor):
    ArmorStats = apps.get_model('charsheet', 'ArmorStats')

    for armor in ArmorStats.objects.filter(
        parent_set__isnull=True,
        item__name__iexact='Bestiarius',
    ):
        armor.component_price_helmet_override = 1600
        armor.component_price_torso_override = 180
        armor.zone_rs_overrides = {'head': 11, 'face': 11, 'torso': 5}
        armor.suppress_component_generation = False
        armor.save(
            update_fields=[
                'component_price_helmet_override',
                'component_price_torso_override',
                'zone_rs_overrides',
                'suppress_component_generation',
            ]
        )

        helmet = ArmorStats.objects.filter(
            parent_set_id=armor.pk,
            component_type='helmet',
        ).select_related('item').first()
        if helmet is not None:
            helmet.item.price = 1600
            helmet.item.save(update_fields=['price'])
            helmet.zone_rs_overrides = {'head': 11, 'face': 11}
            helmet.save(update_fields=['zone_rs_overrides'])

        torso = ArmorStats.objects.filter(
            parent_set_id=armor.pk,
            component_type='torso',
        ).select_related('item').first()
        if torso is not None:
            torso.item.price = 180
            torso.item.save(update_fields=['price'])
            torso.zone_rs_overrides = {'torso': 5}
            torso.save(update_fields=['zone_rs_overrides'])


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0289_merge_limb_armor_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorstats',
            name='component_price_arms_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Arme gesamt'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='component_price_feet_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Schuhe gesamt'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='component_price_hands_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hände gesamt'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='component_price_helmet_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Helm'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='component_price_legs_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Beine gesamt'),
        ),
        migrations.AddField(
            model_name='armorstats',
            name='component_price_torso_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Torso'),
        ),
        migrations.RunPython(configure_bestiarius_prices, migrations.RunPython.noop),
    ]
