# Generated by Django 6.0.5 on 2026-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0292_enable_bestiarius_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorstats',
            name='zone_rs_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Optionale RS-Abweichungen einzelner abgedeckter Zonen. Verfügbare Schlüssel: head (Kopf), face (Gesicht), eyes (Augen), neck (Hals), torso (Torso), organs (Organe), soft_tissue (Weichteile), arm_left (Arm links), hand_left (Hand links), leg_left (Bein links), foot_left (Fuß links), arm_right (Arm rechts), hand_right (Hand rechts), leg_right (Bein rechts), foot_right (Fuß rechts).'),
        ),
    ]
