# Generated by Django 6.0.5 on 2026-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0293_document_armor_zone_override_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorstats',
            name='zone_rs_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Optionale RS-Abweichungen einzelner abgedeckter Zonen.<br><strong>Verfügbare Schlüssel:</strong><br>head – Kopf<br>face – Gesicht<br>eyes – Augen<br>neck – Hals<br>torso – Torso<br>organs – Organe<br>soft_tissue – Weichteile<br>arm_left – Arm links<br>hand_left – Hand links<br>leg_left – Bein links<br>foot_left – Fuß links<br>arm_right – Arm rechts<br>hand_right – Hand rechts<br>leg_right – Bein rechts<br>foot_right – Fuß rechts'),
        ),
    ]
