# Generated by Django 6.0.5 on 2026-07-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0296_character_creatures_without_base_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kreaturentyp',
                'verbose_name_plural': 'Kreaturentypen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='creature',
            name='creature_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatures', to='charsheet.creaturetype', verbose_name='Kreaturentyp'),
        ),
    ]
