# Generated by Django 6.0.5 on 2026-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0297_creaturetype_creature_creature_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creaturetype',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Kreaturentyp', 'verbose_name_plural': 'Kreaturentypen'},
        ),
        migrations.AddField(
            model_name='creaturetype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sortierung'),
        ),
    ]
