# Generated by Django 6.0.5 on 2026-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0298_alter_creaturetype_options_creaturetype_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureattribute',
            name='base_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
