# Generated by Django 6.0.5 on 2026-07-30 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0299_alter_creatureattribute_base_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('can_write', models.BooleanField(default=False, verbose_name='Lesen und Schreiben')),
                ('is_mother_tongue', models.BooleanField(default=False, verbose_name='Muttersprache')),
            ],
            options={
                'ordering': ['language__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='creatureskill',
            options={'ordering': ['skill__name', 'id']},
        ),
        migrations.AddField(
            model_name='creatureskill',
            name='hide_from_creature_training',
            field=models.BooleanField(default=False, help_text='Blendet diese Zeile im Ausbildungsmenue aus. Reine Notes-Zeilen ohne Fertigkeit werden immer ausgeblendet.', verbose_name='Nicht im Kreaturentraining anzeigen'),
        ),
        migrations.AlterField(
            model_name='creatureskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='charsheet.skill'),
        ),
        migrations.AddConstraint(
            model_name='creatureskill',
            constraint=models.CheckConstraint(condition=models.Q(('skill__isnull', False), models.Q(('notes', ''), _negated=True), _connector='OR'), name='creature_skill_or_notes_required'),
        ),
        migrations.AddField(
            model_name='creaturelanguage',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='charsheet.creature'),
        ),
        migrations.AddField(
            model_name='creaturelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charsheet.language'),
        ),
        migrations.AddConstraint(
            model_name='creaturelanguage',
            constraint=models.UniqueConstraint(fields=('creature', 'language'), name='uniq_creature_language'),
        ),
    ]
