# Generated by Django 6.0.5 on 2026-07-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0300_creaturelanguage_alter_creatureskill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercreature',
            name='hidden_skill_notes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'skill__isnull': True}, related_name='hidden_on_character_creatures', to='charsheet.creatureskill', verbose_name='Ausgeblendete Skill-Notes'),
        ),
        migrations.AlterField(
            model_name='creatureskill',
            name='hide_from_creature_training',
            field=models.BooleanField(default=False, help_text='Blendet eine verknuepfte Fertigkeit als Wertefeld im Ausbildungsmenue aus. Reine Notes-Zeilen bleiben dort als Sichtbarkeitsschalter verfuegbar.', verbose_name='Nicht im Kreaturentraining anzeigen'),
        ),
    ]
