# Generated by Django 6.0.5 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0301_charactercreature_hidden_skill_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterCreatureLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_write",
                    models.BooleanField(default=False, verbose_name="Lesen und Schreiben"),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_overrides",
                        to="charsheet.charactercreature",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="charsheet.language",
                    ),
                ),
            ],
            options={
                "ordering": ["language__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creature", "language"),
                        name="uniq_character_creature_language",
                    )
                ],
            },
        ),
    ]
