# Generated by Django 6.0.5 on 2026-08-01 12:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0306_creature_daemonic_power_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCreatureVampireTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('add', 'Hinzufügen'), ('remove', 'Entfernen'), ('override', 'Überschreiben')], default='add', max_length=12)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('associated_weakness_bought_off', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['creature', 'trait__sort_order', 'trait__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterVampireTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('associated_weakness_bought_off', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['character', 'trait__sort_order', 'trait__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreatureVampireTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('associated_weakness_bought_off', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['creature', 'trait__sort_order', 'trait__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameGroupCreatureVampireTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('add', 'Hinzufügen'), ('remove', 'Entfernen'), ('override', 'Überschreiben')], default='add', max_length=12)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('associated_weakness_bought_off', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['creature', 'trait__sort_order', 'trait__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VampireTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('trait_type', models.CharField(choices=[('base', 'Grundvampirismus'), ('power', 'Kraft'), ('weakness', 'Schwäche')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('rules_text', models.TextField(blank=True, default='')),
                ('point_value', models.PositiveSmallIntegerField(default=0)),
                ('blood_cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rankable', models.BooleanField(default=False)),
                ('max_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handler', models.CharField(blank=True, choices=[('', 'Kein automatischer Ablauf'), ('manual_activation', 'Aktivierung und Blutkosten'), ('blood_theft', 'Blutraub'), ('blood_sacrament', 'Blutsakrament'), ('attribute_boost', 'Die Macht des Blutes'), ('regeneration', 'Regeneration')], default='', max_length=40)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vampir-Trait',
                'verbose_name_plural': 'Vampir-Traits',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VampireTraitSemanticEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_scope', models.CharField(choices=[('character', 'Charakter'), ('creature', 'Kreatur'), ('both', 'Charakter und Kreatur')], default='both', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('target_domain', models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack'), ('creature_attack_damage', 'creature_attack_damage'), ('creature_attack_type_damage', 'creature_attack_type_damage')], default='rule_flag', max_length=40)),
                ('target_key', models.CharField(blank=True, default='', max_length=120)),
                ('operator', models.CharField(choices=[('flat_add', 'flat_add'), ('flat_sub', 'flat_sub'), ('multiply', 'multiply'), ('floor_divide', 'floor_divide'), ('override', 'override'), ('min_value', 'min_value'), ('max_value', 'max_value'), ('set_flag', 'set_flag'), ('unset_flag', 'unset_flag'), ('add_tag', 'add_tag'), ('remove_tag', 'remove_tag'), ('grant_capability', 'grant_capability'), ('remove_capability', 'remove_capability'), ('grant_immunity', 'grant_immunity'), ('grant_vulnerability', 'grant_vulnerability'), ('change_resource_cap', 'change_resource_cap'), ('change_starting_funds', 'change_starting_funds'), ('change_appearance_class', 'change_appearance_class'), ('change_social_status', 'change_social_status'), ('reroll_grant', 'reroll_grant'), ('reroll_forbid', 'reroll_forbid'), ('repeat_action_allowed', 'repeat_action_allowed'), ('action_cost_change', 'action_cost_change'), ('conditional_bonus', 'conditional_bonus'), ('conditional_penalty', 'conditional_penalty')], default='flat_add', max_length=40)),
                ('mode', models.CharField(default='flat', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('value_min', models.IntegerField(blank=True, null=True)),
                ('value_max', models.IntegerField(blank=True, null=True)),
                ('formula', models.CharField(blank=True, default='', max_length=200)),
                ('scaling', models.JSONField(blank=True, default=dict)),
                ('stack_behavior', models.CharField(choices=[('stack', 'stack'), ('highest', 'highest'), ('lowest', 'lowest'), ('override', 'override'), ('unique_by_source', 'unique_by_source')], default='stack', max_length=40)),
                ('condition_set', models.JSONField(blank=True, default=dict)),
                ('active_flag', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('condition_text', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('rules_text', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('internal', 'internal'), ('story', 'story')], default='public', max_length=20)),
                ('hidden', models.BooleanField(default=False)),
                ('sheet_relevant', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Vampir-Trait Semantic Effect',
                'verbose_name_plural': 'Vampir-Trait Semantic Effects',
                'ordering': ['trait', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='current_aggravated_damage',
            field=models.PositiveIntegerField(default=0, help_text='Bereits im tödlichen Schaden enthaltener schwer heilbarer Anteil.'),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_age_cycle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_animal_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_blood_capacity_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_blood_capacity_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_day_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_intelligent_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_last_qualifying_kill_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_pending_starvation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_regeneration_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_state',
            field=models.CharField(choices=[('active', 'Aktiv'), ('torpor', 'Starre'), ('destroyed', 'Vernichtet')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='current_aggravated_damage',
            field=models.PositiveIntegerField(default=0, help_text='Bereits im Gesamtschaden enthaltener schwer heilbarer Anteil.'),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_age_cycle_override',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_animal_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_blood_capacity_bonus_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_blood_capacity_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_day_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_intelligent_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_last_qualifying_kill_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_mode',
            field=models.CharField(choices=[('inherit', 'Von Vorlage übernehmen'), ('enable', 'Vampirismus aktivieren'), ('disable', 'Vampirismus deaktivieren')], default='inherit', max_length=12),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_pending_starvation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_regeneration_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_state',
            field=models.CharField(choices=[('active', 'Aktiv'), ('torpor', 'Starre'), ('destroyed', 'Vernichtet')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='creature',
            name='vampire_age_cycle_default',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creature',
            name='vampire_animal_blood_default',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='vampire_blood_capacity_bonus_default',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='vampire_default_enabled',
            field=models.BooleanField(default=False, verbose_name='Vampir-Default'),
        ),
        migrations.AddField(
            model_name='creature',
            name='vampire_intelligent_blood_default',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='current_aggravated_damage',
            field=models.PositiveIntegerField(default=0, help_text='Bereits im tödlichen Schaden enthaltener schwer heilbarer Anteil.'),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_age_cycle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_animal_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_blood_capacity_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_blood_capacity_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_day_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_intelligent_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_last_qualifying_kill_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_mode',
            field=models.CharField(choices=[('inherit', 'Von Vorlage übernehmen'), ('enable', 'Vampirismus aktivieren'), ('disable', 'Vampirismus deaktivieren')], default='inherit', max_length=12),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_pending_starvation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_regeneration_blood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_state',
            field=models.CharField(choices=[('active', 'Aktiv'), ('torpor', 'Starre'), ('destroyed', 'Vernichtet')], default='active', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('current_aggravated_damage__lte', models.F('current_lethal_damage'))), name='character_aggravated_lte_lethal'),
        ),
        migrations.AddConstraint(
            model_name='charactercreature',
            constraint=models.CheckConstraint(condition=models.Q(('current_aggravated_damage__lte', models.F('current_damage'))), name='character_creature_aggravated_lte_damage'),
        ),
        migrations.AddConstraint(
            model_name='gamegroupcreature',
            constraint=models.CheckConstraint(condition=models.Q(('current_aggravated_damage__lte', models.F('current_lethal_damage'))), name='group_creature_aggravated_lte_lethal'),
        ),
        migrations.AddField(
            model_name='charactercreaturevampiretrait',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_trait_overrides', to='charsheet.charactercreature'),
        ),
        migrations.AddField(
            model_name='charactervampiretrait',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_trait_ownerships', to='charsheet.character'),
        ),
        migrations.AddField(
            model_name='creaturevampiretrait',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_trait_defaults', to='charsheet.creature'),
        ),
        migrations.AddField(
            model_name='gamegroupcreaturevampiretrait',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_trait_overrides', to='charsheet.gamegroupcreature'),
        ),
        migrations.AddField(
            model_name='vampiretrait',
            name='associated_weakness',
            field=models.ForeignKey(blank=True, limit_choices_to={'trait_type': 'weakness'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associated_powers', to='charsheet.vampiretrait'),
        ),
        migrations.AddField(
            model_name='gamegroupcreaturevampiretrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_group_creature_overrides', to='charsheet.vampiretrait'),
        ),
        migrations.AddField(
            model_name='creaturevampiretrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creature_defaults', to='charsheet.vampiretrait'),
        ),
        migrations.AddField(
            model_name='charactervampiretrait',
            name='trait',
            field=models.ForeignKey(limit_choices_to={'trait_type__in': ['power', 'weakness']}, on_delete=django.db.models.deletion.PROTECT, related_name='character_ownerships', to='charsheet.vampiretrait'),
        ),
        migrations.AddField(
            model_name='charactercreaturevampiretrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_creature_overrides', to='charsheet.vampiretrait'),
        ),
        migrations.AddField(
            model_name='vampiretraitsemanticeffect',
            name='target_skills',
            field=models.ManyToManyField(blank=True, related_name='vampire_trait_semantic_effects', to='charsheet.skill'),
        ),
        migrations.AddField(
            model_name='vampiretraitsemanticeffect',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_effects', to='charsheet.vampiretrait'),
        ),
        migrations.AddConstraint(
            model_name='gamegroupcreaturevampiretrait',
            constraint=models.UniqueConstraint(fields=('creature', 'trait'), name='uniq_group_creature_vampire_trait'),
        ),
        migrations.AddConstraint(
            model_name='creaturevampiretrait',
            constraint=models.UniqueConstraint(fields=('creature', 'trait'), name='uniq_creature_vampire_trait'),
        ),
        migrations.AddConstraint(
            model_name='charactervampiretrait',
            constraint=models.UniqueConstraint(fields=('character', 'trait'), name='uniq_character_vampire_trait'),
        ),
        migrations.AddConstraint(
            model_name='charactercreaturevampiretrait',
            constraint=models.UniqueConstraint(fields=('creature', 'trait'), name='uniq_character_creature_vampire_trait'),
        ),
    ]
