# Generated by Django 6.0.5 on 2026-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0308_seed_vampire_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_blood_capacity_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='vampire_blood_capacity_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_blood_capacity_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
