# Generated by Django 6.0.5 on 2026-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0309_charactercreature_vampire_blood_capacity_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='vampire_sacrament_age_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vampire_sacrament_rounds_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_sacrament_age_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_sacrament_rounds_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_sacrament_age_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_sacrament_rounds_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
