# Generated by Django 6.0.5 on 2026-08-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0310_character_vampire_sacrament_age_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='vampire_regeneration_target_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='vampire_regeneration_target_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamegroupcreature',
            name='vampire_regeneration_target_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
