# Generated by Django 6.0.5 on 2026-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0311_character_vampire_regeneration_target_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactercreaturevampiretrait',
            options={'ordering': ['creature', 'trait__sort_order', 'trait__name', 'id'], 'verbose_name': 'Character creature vampire trait', 'verbose_name_plural': 'Character creature vampire traits'},
        ),
        migrations.AlterModelOptions(
            name='charactervampiretrait',
            options={'ordering': ['character', 'trait__sort_order', 'trait__name', 'id'], 'verbose_name': 'Character vampire trait', 'verbose_name_plural': 'Character vampire traits'},
        ),
        migrations.AlterModelOptions(
            name='creaturevampiretrait',
            options={'ordering': ['creature', 'trait__sort_order', 'trait__name', 'id'], 'verbose_name': 'Creature vampire trait', 'verbose_name_plural': 'Creature vampire traits'},
        ),
        migrations.AlterModelOptions(
            name='gamegroupcreaturevampiretrait',
            options={'ordering': ['creature', 'trait__sort_order', 'trait__name', 'id'], 'verbose_name': 'Game group creature vampire trait', 'verbose_name_plural': 'Game group creature vampire traits'},
        ),
        migrations.AlterModelOptions(
            name='vampiretrait',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Vampire trait', 'verbose_name_plural': 'Vampire traits'},
        ),
        migrations.AlterModelOptions(
            name='vampiretraitsemanticeffect',
            options={'ordering': ['trait', 'sort_order', 'id'], 'verbose_name': 'Vampire trait semantic effect', 'verbose_name_plural': 'Vampire trait semantic effects'},
        ),
        migrations.AlterField(
            model_name='character',
            name='vampire_state',
            field=models.CharField(choices=[('active', 'Active'), ('torpor', 'Torpor'), ('destroyed', 'Destroyed')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='charactercreature',
            name='vampire_mode',
            field=models.CharField(choices=[('inherit', 'Inherit from template'), ('enable', 'Enable vampirism'), ('disable', 'Disable vampirism')], default='inherit', max_length=12),
        ),
        migrations.AlterField(
            model_name='charactercreature',
            name='vampire_state',
            field=models.CharField(choices=[('active', 'Active'), ('torpor', 'Torpor'), ('destroyed', 'Destroyed')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='charactercreaturevampiretrait',
            name='mode',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('override', 'Override')], default='add', max_length=12),
        ),
        migrations.AlterField(
            model_name='creature',
            name='vampire_default_enabled',
            field=models.BooleanField(default=False, verbose_name='Vampire default'),
        ),
        migrations.AlterField(
            model_name='gamegroupcreature',
            name='vampire_mode',
            field=models.CharField(choices=[('inherit', 'Inherit from template'), ('enable', 'Enable vampirism'), ('disable', 'Disable vampirism')], default='inherit', max_length=12),
        ),
        migrations.AlterField(
            model_name='gamegroupcreature',
            name='vampire_state',
            field=models.CharField(choices=[('active', 'Active'), ('torpor', 'Torpor'), ('destroyed', 'Destroyed')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='gamegroupcreaturevampiretrait',
            name='mode',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('override', 'Override')], default='add', max_length=12),
        ),
        migrations.AlterField(
            model_name='vampiretrait',
            name='handler',
            field=models.CharField(blank=True, choices=[('', 'No automated workflow'), ('manual_activation', 'Activation and blood cost'), ('blood_theft', 'Blood theft'), ('blood_sacrament', 'Blood sacrament'), ('attribute_boost', 'Blood-fuelled attribute boost'), ('regeneration', 'Regeneration')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='vampiretrait',
            name='trait_type',
            field=models.CharField(choices=[('base', 'Base vampirism'), ('power', 'Power'), ('weakness', 'Weakness')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vampiretraitsemanticeffect',
            name='application_scope',
            field=models.CharField(choices=[('character', 'Character'), ('creature', 'Creature'), ('both', 'Character and creature')], default='both', max_length=20),
        ),
    ]
