# Generated by Django 6.0.5 on 2026-08-01 15:10

from django.db import migrations, models


def remove_inert_vampire_effects(apps, schema_editor):
    VampireTrait = apps.get_model("charsheet", "VampireTrait")
    Effect = apps.get_model("charsheet", "VampireTraitSemanticEffect")
    VampireTrait.objects.filter(slug="grundvampirismus", trait_type="base").delete()
    Effect.objects.filter(
        trait__trait_type="weakness",
        target_domain="rule_flag",
        target_key__startswith="vampire_weakness_",
    ).delete()
    Effect.objects.filter(
        trait__slug="fliegen",
        target_domain="capability",
        target_key="flight",
        operator="grant_capability",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0312_alter_charactercreaturevampiretrait_options_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_inert_vampire_effects, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vampiretrait',
            name='trait_type',
            field=models.CharField(choices=[('power', 'Power'), ('weakness', 'Weakness')], max_length=20),
        ),
    ]
