# Generated by Django 6.0.5 on 2026-08-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0312_alter_charactercreaturevampiretrait_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vampiretrait',
            name='trait_type',
            field=models.CharField(choices=[('power', 'Power'), ('weakness', 'Weakness')], max_length=20),
        ),
    ]
