# Generated by Django 6.0.5 on 2026-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0313_alter_vampiretrait_trait_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='vampire_baptism_confirmed',
            field=models.BooleanField(default=False, help_text='GM confirmation that a rule-compliant blood baptism permits the 15 EP acquisition.'),
        ),
    ]
