# Generated by Django 6.0.5 on 2026-08-01 15:41

from django.db import migrations


def merge_vampire_anchor(apps, schema_editor):
    Trait = apps.get_model("charsheet", "Trait")
    CharacterTrait = apps.get_model("charsheet", "CharacterTrait")
    CharacterCreationDraft = apps.get_model("charsheet", "CharacterCreationDraft")

    canonical = Trait.objects.filter(slug="adv_vampire").first()
    duplicate = Trait.objects.filter(slug="vampirismus").first()
    if canonical is None and duplicate is not None:
        duplicate.slug = "adv_vampire"
        duplicate.name = "Vampir"
        duplicate.save(update_fields=["slug", "name"])
        canonical = duplicate
        duplicate = None
    if canonical is None:
        canonical = Trait.objects.create(
            slug="adv_vampire",
            name="Vampir",
            trait_type="advantage",
            min_level=1,
            max_level=1,
            points_per_level=15,
        )
    canonical.trait_type = "advantage"
    canonical.min_level = 1
    canonical.max_level = 1
    canonical.points_per_level = 15
    canonical.points_by_level = ""
    canonical.save(
        update_fields=["trait_type", "min_level", "max_level", "points_per_level", "points_by_level"]
    )

    if duplicate is not None:
        for ownership in CharacterTrait.objects.filter(trait=duplicate):
            if CharacterTrait.objects.filter(owner_id=ownership.owner_id, trait=canonical).exists():
                ownership.delete()
            else:
                ownership.trait = canonical
                ownership.save(update_fields=["trait"])
        duplicate.delete()

    for draft in CharacterCreationDraft.objects.all().iterator():
        state = dict(draft.state or {})
        phase_4 = dict(state.get("phase_4") or {})
        advantages = dict(phase_4.get("advantages") or {})
        if "vampirismus" not in advantages:
            continue
        advantages["adv_vampire"] = max(
            int(advantages.get("adv_vampire") or 0),
            int(advantages.pop("vampirismus") or 0),
        )
        phase_4["advantages"] = advantages
        state["phase_4"] = phase_4
        draft.state = state
        draft.save(update_fields=["state"])


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0314_character_vampire_baptism_confirmed'),
    ]

    operations = [migrations.RunPython(merge_vampire_anchor, migrations.RunPython.noop)]
