# Generated by Django 6.0.5 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0314_character_vampire_baptism_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vampiretrait",
            name="trait_type",
            field=models.CharField(
                choices=[("power", "Advantage"), ("weakness", "Disadvantage")],
                max_length=20,
            ),
        ),
    ]
