# Generated by Django 6.0.5 on 2026-08-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0316_alter_vampiretrait_trait_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactervampiretrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_ownerships', to='charsheet.vampiretrait'),
        ),
        migrations.AlterField(
            model_name='vampiretraitsemanticeffect',
            name='trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_effects', to='charsheet.vampiretrait'),
        ),
        migrations.CreateModel(
            name='VampirePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('blood_cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handler', models.CharField(blank=True, choices=[('', 'No automated workflow'), ('manual_activation', 'Activation and blood cost'), ('blood_theft', 'Blood theft'), ('blood_sacrament', 'Blood sacrament'), ('attribute_boost', 'Blood-fuelled attribute boost'), ('regeneration', 'Regeneration')], default='', max_length=40)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('weakness', models.ForeignKey(limit_choices_to={'trait_type': 'disadvantage'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associated_powers', to='charsheet.vampiretrait')),
            ],
            options={
                'verbose_name': 'Vampire power',
                'verbose_name_plural': 'Vampire powers',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vampiretraitsemanticeffect',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_effects', to='charsheet.vampirepower'),
        ),
        migrations.CreateModel(
            name='GameGroupCreatureVampirePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('override', 'Override')], default='add', max_length=12)),
                ('purchased_without_weakness', models.BooleanField(blank=True, null=True)),
                ('weakness_bought_off', models.BooleanField(blank=True, null=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_power_overrides', to='charsheet.gamegroupcreature')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_group_creature_overrides', to='charsheet.vampirepower')),
            ],
            options={
                'verbose_name': 'Game group creature vampire power',
                'verbose_name_plural': 'Game group creature vampire powers',
                'ordering': ['creature', 'power__sort_order', 'power__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('creature', 'power'), name='uniq_group_creature_vampire_power')],
            },
        ),
        migrations.CreateModel(
            name='CreatureVampirePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_without_weakness', models.BooleanField(default=False)),
                ('weakness_bought_off', models.BooleanField(default=False)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_power_defaults', to='charsheet.creature')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creature_defaults', to='charsheet.vampirepower')),
            ],
            options={
                'verbose_name': 'Creature vampire power',
                'verbose_name_plural': 'Creature vampire powers',
                'ordering': ['creature', 'power__sort_order', 'power__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('creature', 'power'), name='uniq_creature_vampire_power')],
            },
        ),
        migrations.CreateModel(
            name='CharacterVampirePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_without_weakness', models.BooleanField(default=False)),
                ('weakness_bought_off', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_power_ownerships', to='charsheet.character')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_ownerships', to='charsheet.vampirepower')),
            ],
            options={
                'verbose_name': 'Character vampire power',
                'verbose_name_plural': 'Character vampire powers',
                'ordering': ['character', 'power__sort_order', 'power__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('character', 'power'), name='uniq_character_vampire_power')],
            },
        ),
        migrations.CreateModel(
            name='CharacterCreatureVampirePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('override', 'Override')], default='add', max_length=12)),
                ('purchased_without_weakness', models.BooleanField(blank=True, null=True)),
                ('weakness_bought_off', models.BooleanField(blank=True, null=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampire_power_overrides', to='charsheet.charactercreature')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_creature_overrides', to='charsheet.vampirepower')),
            ],
            options={
                'verbose_name': 'Character creature vampire power',
                'verbose_name_plural': 'Character creature vampire powers',
                'ordering': ['creature', 'power__sort_order', 'power__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('creature', 'power'), name='uniq_character_creature_vampire_power')],
            },
        ),
    ]
