# Generated by Django 6.0.5 on 2026-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0326_normalize_disallowed_school_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercreature',
            name='semantic_effect_is_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='semantic_effect_key',
            field=models.CharField(blank=True, default='', help_text='Stable identity of a semantic effect that grants this card.', max_length=160),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='semantic_effect_label',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='creaturespecialskillsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_card', 'creature_card'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack'), ('creature_attack_damage', 'creature_attack_damage'), ('creature_attack_type_damage', 'creature_attack_type_damage')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich'),
        ),
        migrations.AlterField(
            model_name='creaturetraitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_card', 'creature_card'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack'), ('creature_attack_damage', 'creature_attack_damage'), ('creature_attack_type_damage', 'creature_attack_type_damage')], default='rule_flag', help_text='Wird im einfachen Admin-Editor automatisch gesetzt.', max_length=40, verbose_name='Technischer Bereich'),
        ),
        migrations.AlterField(
            model_name='daemonicpowersemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_card', 'creature_card'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack'), ('creature_attack_damage', 'creature_attack_damage'), ('creature_attack_type_damage', 'creature_attack_type_damage'), ('daemonic_power', 'daemonic_power')], default='rule_flag', max_length=40),
        ),
        migrations.AlterField(
            model_name='techniquesemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_card', 'creature_card')], default='skill', max_length=40),
        ),
        migrations.AlterField(
            model_name='traitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_card', 'creature_card')], default='rule_flag', max_length=40),
        ),
        migrations.AlterField(
            model_name='vampiretraitsemanticeffect',
            name='target_domain',
            field=models.CharField(choices=[('skill', 'skill'), ('skill_category', 'skill_category'), ('skill_rank', 'skill_rank'), ('skill_rank_cap', 'skill_rank_cap'), ('language', 'language'), ('proficiency_group', 'proficiency_group'), ('trait', 'trait'), ('attribute', 'attribute'), ('attribute_cap', 'attribute_cap'), ('derived_stat', 'derived_stat'), ('resource', 'resource'), ('resistance', 'resistance'), ('movement', 'movement'), ('combat', 'combat'), ('perception', 'perception'), ('economy', 'economy'), ('social', 'social'), ('rule_flag', 'rule_flag'), ('capability', 'capability'), ('behavior', 'behavior'), ('tag', 'tag'), ('metadata', 'metadata'), ('item', 'item'), ('item_category', 'item_category'), ('specialization', 'specialization'), ('entity', 'entity'), ('creature_card', 'creature_card'), ('creature_special_skill', 'creature_special_skill'), ('creature_attack', 'creature_attack'), ('creature_attack_damage', 'creature_attack_damage'), ('creature_attack_type_damage', 'creature_attack_type_damage')], default='rule_flag', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='charactercreature',
            constraint=models.UniqueConstraint(condition=models.Q(('semantic_effect_key', ''), _negated=True), fields=('owner', 'semantic_effect_key'), name='uniq_character_creature_semantic_effect'),
        ),
    ]
