# Generated by Django 6.0.5 on 2026-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0338_shieldstats_offensive_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shieldstats',
            name='maneuver_attribute_mode',
            field=models.CharField(choices=[('st', 'Stärke'), ('ge', 'Geschicklichkeit'), ('both', 'Stärke oder Geschicklichkeit')], default='st', help_text='Welcher Attributsmodifikator fuer offensive Schildaktionen gilt.', max_length=10),
        ),
    ]
