# Generated by Django 6.0.5 on 2026-08-09 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0340_trait_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shieldstats',
            name='damage_dice_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shieldstats',
            name='damage_dice_faces',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
