# Generated by Django 6.0.5 on 2026-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0344_ranged_weapon_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteritem',
            name='weapon_maneuver_attribute_override',
            field=models.CharField(blank=True, choices=[('none', '---'), ('st', 'Stärke'), ('ge', 'Geschicklichkeit'), ('both', 'Stärke oder Geschicklichkeit')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='rangedweaponstats',
            name='maneuver_attribute_mode',
            field=models.CharField(choices=[('none', '---'), ('st', 'Stärke'), ('ge', 'Geschicklichkeit'), ('both', 'Stärke oder Geschicklichkeit')], default='st', help_text='Welcher Attributsmodifikator fuer Fernkampf-Manoever und Waffenwuerfe gilt.', max_length=10),
        ),
        migrations.AlterField(
            model_name='shieldstats',
            name='maneuver_attribute_mode',
            field=models.CharField(choices=[('none', '---'), ('st', 'Stärke'), ('ge', 'Geschicklichkeit'), ('both', 'Stärke oder Geschicklichkeit')], default='st', help_text='Welcher Attributsmodifikator fuer offensive Schildaktionen gilt.', max_length=10),
        ),
        migrations.AlterField(
            model_name='weaponstats',
            name='maneuver_attribute_mode',
            field=models.CharField(choices=[('none', '---'), ('st', 'Stärke'), ('ge', 'Geschicklichkeit'), ('both', 'Stärke oder Geschicklichkeit')], default='st', help_text='Welcher Attributsmodifikator für Waffenmanöver und Waffenwürfe gilt.', max_length=10),
        ),
    ]
