# Generated by Django 6.0.5 on 2026-08-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0355_migrate_modifier_rows_to_semantic_effects'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='modifier',
            name='charsheet_m_source__1e69f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='modifier',
            name='charsheet_m_target__96bdf0_idx',
        ),
        migrations.RemoveIndex(
            model_name='modifier',
            name='charsheet_m_target__f7da17_idx',
        ),
        migrations.DeleteModel(
            name='Modifier',
        ),
    ]
