# Generated by Django 6.0.5 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0358_item_semantic_effect_toggleable'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritemsemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='%(class)s_conditions', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='daemonicpowersemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='daemonic_power_semantic_effect_conditions', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='itemsemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='%(class)s_conditions', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='racesemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='%(app_label)s_%(class)s_conditioned_effects', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='runesemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='%(app_label)s_%(class)s_conditioned_effects', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='schoolsemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='%(app_label)s_%(class)s_conditioned_effects', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='techniquesemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='technique_semantic_effect_conditions', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='traitsemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='trait_semantic_effect_conditions', to='charsheet.race'),
        ),
        migrations.AddField(
            model_name='vampiretraitsemanticeffect',
            name='condition_races',
            field=models.ManyToManyField(blank=True, help_text='Optional race condition. Leave empty to apply to every race.', related_name='vampire_trait_semantic_effect_conditions', to='charsheet.race'),
        ),
    ]
