# Generated by Django 6.0.5 on 2026-08-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0361_item_semantic_effect_display_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroupinvitation',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_group_invitations', to='charsheet.character'),
        ),
        migrations.AlterField(
            model_name='gamegroupmembership',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_group_memberships', to='charsheet.character'),
        ),
    ]
