# Generated by Django 6.0.5 on 2026-08-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0362_alter_gamegroupinvitation_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroupmembership',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='charsheet.gamegroupinvitation'),
        ),
    ]
