# Generated by Django 6.0.5 on 2026-08-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0363_alter_gamegroupmembership_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponstats',
            name='profile_name',
            field=models.CharField(blank=True, default='', help_text='Optionaler Name dieses Waffenprofils, z. B. Rapier oder Main-Gauche.', max_length=100),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='original_owner_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_owned_items', to='charsheet.character'),
        ),
        migrations.AlterField(
            model_name='weaponstats',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_stats', to='charsheet.item'),
        ),
    ]
