# Generated by Django 6.0.5 on 2026-08-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0364_weaponstats_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritemsemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='%(class)s_school_conditions', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='daemonicpowersemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='+', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='itemsemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='%(class)s_school_conditions', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='racesemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='%(app_label)s_%(class)s_school_conditioned_effects', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='runesemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='%(app_label)s_%(class)s_school_conditioned_effects', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='schoolsemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='%(app_label)s_%(class)s_school_conditioned_effects', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='techniquesemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='+', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='traitsemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='+', to='charsheet.school'),
        ),
        migrations.AddField(
            model_name='vampiretraitsemanticeffect',
            name='condition_schools',
            field=models.ManyToManyField(blank=True, help_text='Optional school condition. Leave empty to apply to every school.', related_name='+', to='charsheet.school'),
        ),
    ]
