# Generated by Django 6.0.5 on 2026-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0365_characteritemsemanticeffect_condition_schools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponstats',
            name='range_strength_multiplier',
            field=models.BooleanField(default=False),
        ),
    ]
