# Generated by Django 6.0.5 on 2026-08-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0366_weaponstats_range_strength_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('ms_modifier', models.IntegerField(default=0)),
                ('weight_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('apply_quality_effects', models.BooleanField(default=True, help_text='Wenn deaktiviert, überschreibt das Metall die angezeigte Qualität, ohne deren regeltechnische Qualitätsboni anzuwenden.')),
                ('quality_overwrite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metal_overwrites', to='charsheet.quality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='charsheet.metal'),
        ),
    ]
