# Generated by Django 6.0.5 on 2026-08-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0367_metal_item_metal'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='descirption',
            field=models.TextField(blank=True),
        ),
    ]
