# Generated by Django 6.0.5 on 2026-08-25 12:58

import charsheet.models.items
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0368_metal_descirption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='armor_encumbrance_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='armor_min_st_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='armor_rs_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='creature_kind_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quality',
            name='creature_training_advantage_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='creature_training_disadvantage_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='hardness_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='quality',
            name='holographic_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quality',
            name='is_default',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='quality',
            name='lifespan_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='quality',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='quality',
            name='skill_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='structure_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='quality',
            name='weapon_damage_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='weapon_maneuver_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charactercreature',
            name='quality',
            field=models.ForeignKey(db_column='quality', default=charsheet.models.items.default_quality_pk, on_delete=django.db.models.deletion.PROTECT, related_name='character_creatures', to='charsheet.quality'),
        ),
        migrations.AlterField(
            model_name='charactercreatureitem',
            name='quality',
            field=models.ForeignKey(db_column='quality', default=charsheet.models.items.default_quality_pk, on_delete=django.db.models.deletion.PROTECT, related_name='creature_items', to='charsheet.quality'),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='quality',
            field=models.ForeignKey(db_column='quality', default=charsheet.models.items.default_quality_pk, on_delete=django.db.models.deletion.PROTECT, related_name='character_items', to='charsheet.quality'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='quality',
            field=models.ForeignKey(db_column='quality', default=charsheet.models.items.default_quality_pk, on_delete=django.db.models.deletion.PROTECT, related_name='creatures', to='charsheet.quality'),
        ),
        migrations.AlterField(
            model_name='creaturesourcebinding',
            name='quality',
            field=models.ForeignKey(db_column='quality', default=charsheet.models.items.default_quality_pk, help_text="Quality used when this binding is triggered by a technique. Item-triggered creatures use the owned item's quality.", on_delete=django.db.models.deletion.PROTECT, related_name='creature_source_bindings', to='charsheet.quality'),
        ),
        migrations.AlterField(
            model_name='item',
            name='default_quality',
            field=models.ForeignKey(db_column='default_quality', default=charsheet.models.items.default_quality_pk, on_delete=django.db.models.deletion.PROTECT, related_name='default_items', to='charsheet.quality'),
        ),
        migrations.AddConstraint(
            model_name='quality',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_quality'),
        ),
    ]
