# Generated by Django 6.0.5 on 2026-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0369_quality_armor_encumbrance_modifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='holographic_display',
        ),
        migrations.AddField(
            model_name='quality',
            name='holographic_style',
            field=models.CharField(blank=True, choices=[('', 'Kein Holo'), ('gold', 'Gold'), ('rainbow', 'Rainbow')], default='', max_length=20),
        ),
    ]
