# Generated by Django 6.0.5 on 2026-08-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0371_repair_item_qualities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterItemIdentificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialized', models.BooleanField(default=True)),
                ('character_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification_state', to='charsheet.characteritem')),
            ],
            options={
                'ordering': ['character_item'],
            },
        ),
        migrations.CreateModel(
            name='CharacterItemDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=80)),
                ('revealed', models.BooleanField(default=True)),
                ('alternative_text', models.TextField(blank=True, default='')),
                ('character_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='charsheet.characteritem')),
            ],
            options={
                'ordering': ['character_item', 'field_key'],
                'constraints': [models.UniqueConstraint(fields=('character_item', 'field_key'), name='uniq_character_item_disclosure_field')],
            },
        ),
        migrations.CreateModel(
            name='CharacterItemEffectIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identified', models.BooleanField(default=False)),
                ('alternative_text', models.TextField(blank=True, default='')),
                ('character_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_identifications', to='charsheet.characteritem')),
                ('character_item_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='charsheet.characteritemsemanticeffect')),
                ('item_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_item_identifications', to='charsheet.itemsemanticeffect')),
            ],
            options={
                'ordering': ['character_item', 'item_effect', 'character_item_effect'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('item_effect__isnull', False), ('character_item_effect__isnull', True)), models.Q(('item_effect__isnull', True), ('character_item_effect__isnull', False)), _connector='OR'), name='character_item_identification_exactly_one_effect'), models.UniqueConstraint(condition=models.Q(('item_effect__isnull', False)), fields=('character_item', 'item_effect'), name='uniq_character_item_item_effect_identification'), models.UniqueConstraint(condition=models.Q(('character_item_effect__isnull', False)), fields=('character_item', 'character_item_effect'), name='uniq_character_item_instance_effect_identification')],
            },
        ),
    ]
