# Generated by Django 6.0.5 on 2026-08-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0372_character_item_disclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritemdisclosure',
            name='alternative_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_item_disclosures/'),
        ),
    ]
