# Generated by Django 6.0.5 on 2026-08-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0373_disclosure_alternative_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('armor', 'Rüstung'), ('weapon', 'Waffe'), ('shield', 'Schild'), ('clothing', 'Kleidung'), ('equipment', 'Ausrüstung'), ('ring', 'Ring'), ('amulet', 'Amulett'), ('magical_weapon', 'Magische Waffe'), ('magical_armor', 'Magisches Rüstzeug'), ('alchemical_brew', 'Alchemistische Gebräue'), ('consumable', 'Verbrauchsgegenstand'), ('ammo', 'Monition'), ('creature', 'Tiere & Kreaturen'), ('misc', 'Sonstiges')], max_length=20),
        ),
        migrations.CreateModel(
            name='AlchemicalBrewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_type', models.CharField(choices=[('potion', 'Trank'), ('salve', 'Salbe'), ('oil', 'Öl'), ('powder', 'Pulver'), ('other', 'Sonstiges')], max_length=20)),
                ('ingredient_cost_gm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Zutatenkosten (GM)')),
                ('craft_time_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Herstellungszeit')),
                ('craft_time_unit', models.CharField(blank=True, choices=[('hours', 'Stunde(n)'), ('days', 'Tag(e)'), ('weeks', 'Woche(n)'), ('months', 'Monat(e)')], default='', max_length=10, verbose_name='Zeiteinheit')),
                ('alchemy_required', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wissen: Alchemie')),
                ('craft_mw', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Herstellungs-MW')),
                ('craft_ep_cost', models.PositiveSmallIntegerField(default=0, verbose_name='EP-Kosten')),
                ('additional_requirements', models.TextField(blank=True, default='', verbose_name='Weitere Voraussetzungen')),
                ('duration', models.TextField(blank=True, default='', verbose_name='Wirkungsdauer')),
                ('application', models.TextField(blank=True, default='', verbose_name='Anwendung')),
                ('storage', models.TextField(blank=True, default='', verbose_name='Aufbewahrung')),
                ('dosage', models.TextField(blank=True, default='', verbose_name='Dosierung / Portionen')),
                ('heal_lp', models.PositiveSmallIntegerField(default=0, verbose_name='LP heilen')),
                ('restore_kp', models.PositiveSmallIntegerField(default=0, verbose_name='KP regenerieren')),
                ('heal_wound_grades', models.PositiveSmallIntegerField(default=0, verbose_name='Wundgrade heilen')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charsheet.item')),
            ],
        ),
    ]
