# Generated by Django 6.0.5 on 2026-08-29 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0374_alter_item_item_type_alchemicalbrewstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemicalBrewRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stufe')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('brew_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='charsheet.alchemicalbrewstats')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alchemical_brew_requirements', to='charsheet.school')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alchemical_brew_requirements', to='charsheet.skill')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('skill__isnull', False), ('school__isnull', True)), models.Q(('skill__isnull', True), ('school__isnull', False)), _connector='OR'), name='alchemical_requirement_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('skill__isnull', False)), fields=('brew_stats', 'skill'), name='unique_alchemical_brew_skill_requirement'), models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('brew_stats', 'school'), name='unique_alchemical_brew_school_requirement')],
            },
        ),
    ]
