# Generated by Django 6.0.5 on 2026-08-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0376_migrate_alchemy_required_to_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alchemicalbrewstats',
            name='alchemy_required',
        ),
        migrations.RemoveField(
            model_name='alchemicalbrewstats',
            name='application',
        ),
        migrations.RemoveField(
            model_name='alchemicalbrewstats',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='alchemicalbrewstats',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='alchemicalbrewstats',
            name='storage',
        ),
    ]
