# Generated by Django 6.0.5 on 2026-08-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0377_cleanup_alchemical_brew_stats'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alchemicalbrewrequirement',
            name='alchemical_requirement_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='alchemicalbrewrequirement',
            name='unique_alchemical_brew_skill_requirement',
        ),
        migrations.RemoveConstraint(
            model_name='alchemicalbrewrequirement',
            name='unique_alchemical_brew_school_requirement',
        ),
        migrations.AddField(
            model_name='alchemicalbrewrequirement',
            name='aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alchemical_brew_requirements', to='charsheet.aspect'),
        ),
        migrations.AddConstraint(
            model_name='alchemicalbrewrequirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('skill__isnull', False), ('school__isnull', True), ('aspect__isnull', True)), models.Q(('skill__isnull', True), ('school__isnull', False), ('aspect__isnull', True)), models.Q(('skill__isnull', True), ('school__isnull', True), ('aspect__isnull', False)), _connector='OR'), name='brew_requirement_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='alchemicalbrewrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('skill__isnull', False)), fields=('brew_stats', 'skill'), name='unique_brew_skill_requirement'),
        ),
        migrations.AddConstraint(
            model_name='alchemicalbrewrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('brew_stats', 'school'), name='unique_brew_school_requirement'),
        ),
        migrations.AddConstraint(
            model_name='alchemicalbrewrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('aspect__isnull', False)), fields=('brew_stats', 'aspect'), name='unique_brew_aspect_requirement'),
        ),
    ]
