# Generated by Django 6.0.5 on 2026-08-29 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0378_remove_alchemicalbrewrequirement_alchemical_requirement_exactly_one_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alchemicalbrewrequirement',
            name='alternative_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ODER-Gruppe'),
        ),
    ]
