# Generated by Django 6.0.5 on 2026-08-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0381_alter_characteritemsemanticeffect_target_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='support_level',
        ),
    ]
