# Generated by Django 6.0.5 on 2026-09-16 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0386_alter_characteritemsemanticeffect_target_domain_and_more",
        )
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterlesson",
            options={"ordering": ["character", "lesson__name"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="lessoncost",
            options={"ordering": ["lesson__name", "sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="lessonrequirement",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="lessonrequirement",
            name="creature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_requirements",
                to="charsheet.creature",
            ),
        ),
        migrations.AddField(
            model_name="lessonrequirement",
            name="druid_circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_requirements",
                to="charsheet.druidcult",
            ),
        ),
        migrations.AddField(
            model_name="lessonrequirement",
            name="magic_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="magic_lesson_requirements",
                to="charsheet.school",
            ),
        ),
        migrations.AddField(
            model_name="lessonrequirement",
            name="specialisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_requirements",
                to="charsheet.specialization",
            ),
        ),
        migrations.AlterField(
            model_name="lessonrequirement",
            name="minimum_value",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="lessonrequirement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("school_technique", "School + Technique"),
                    ("school_specialisation", "School + Specialisation"),
                    ("magic_school_level", "Magic School"),
                    ("clerical_magic_level", "Clerical Magic"),
                    ("druid_circle_level", "Druid Circle"),
                    ("specific_creature", "Creature"),
                ],
                max_length=24,
            ),
        ),
    ]
