# Generated by Django 6.0.5 on 2026-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("charsheet", "0388_migrate_lesson_requirements")]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonrequirementgroup",
            name="uniq_lesson_requirement_group_number",
        ),
        migrations.RemoveField(
            model_name="lessonrequirement",
            name="group",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="school",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="technique",
        ),
        migrations.RemoveField(
            model_name="lessonrequirement",
            name="required_lesson",
        ),
        migrations.RemoveField(
            model_name="lessonrequirement",
            name="required_skill",
        ),
        migrations.AddConstraint(
            model_name="lessonrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("creature__isnull", True),
                        ("druid_circle__isnull", True),
                        ("magic_school__isnull", True),
                        ("minimum_value__isnull", True),
                        ("required_school__isnull", False),
                        ("required_technique__isnull", False),
                        ("requirement_type", "school_technique"),
                        ("specialisation__isnull", True),
                    ),
                    models.Q(
                        ("creature__isnull", True),
                        ("druid_circle__isnull", True),
                        ("magic_school__isnull", True),
                        ("minimum_value__isnull", True),
                        ("required_school__isnull", False),
                        ("required_technique__isnull", True),
                        ("requirement_type", "school_specialisation"),
                        ("specialisation__isnull", False),
                    ),
                    models.Q(
                        ("creature__isnull", True),
                        ("druid_circle__isnull", True),
                        ("magic_school__isnull", False),
                        ("minimum_value__gte", 1),
                        ("minimum_value__isnull", False),
                        ("required_school__isnull", True),
                        ("required_technique__isnull", True),
                        ("requirement_type", "magic_school_level"),
                        ("specialisation__isnull", True),
                    ),
                    models.Q(
                        ("creature__isnull", True),
                        ("druid_circle__isnull", True),
                        ("magic_school__isnull", True),
                        ("minimum_value__gte", 1),
                        ("minimum_value__isnull", False),
                        ("required_school__isnull", True),
                        ("required_technique__isnull", True),
                        ("requirement_type", "clerical_magic_level"),
                        ("specialisation__isnull", True),
                    ),
                    models.Q(
                        ("creature__isnull", True),
                        ("druid_circle__isnull", False),
                        ("magic_school__isnull", True),
                        ("minimum_value__gte", 1),
                        ("minimum_value__isnull", False),
                        ("required_school__isnull", True),
                        ("required_technique__isnull", True),
                        ("requirement_type", "druid_circle_level"),
                        ("specialisation__isnull", True),
                    ),
                    models.Q(
                        ("creature__isnull", False),
                        ("druid_circle__isnull", True),
                        ("magic_school__isnull", True),
                        ("minimum_value__isnull", True),
                        ("required_school__isnull", True),
                        ("required_technique__isnull", True),
                        ("requirement_type", "specific_creature"),
                        ("specialisation__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="lesson_requirement_valid_fields",
            ),
        ),
        migrations.DeleteModel(
            name="LessonRequirementGroup",
        ),
    ]
