# Generated by Django 6.0.5 on 2026-09-17 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0390_lesson_cost_groups'),
    ]
    operations = [
        migrations.CreateModel(
            name='TraitSpecificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(editable=False, max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['trait__name', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='lessonrequirement',
            name='lesson_requirement_valid_fields',
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='charsheet.aspect'),
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='required_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='required_by_lessons', to='charsheet.lesson'),
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='required_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='charsheet.skill'),
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='required_trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='charsheet.trait'),
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='requirement_group',
            field=models.PositiveSmallIntegerField(default=1, help_text='Voraussetzungen derselben Gruppe gelten gemeinsam (UND); verschiedene Gruppen sind Alternativen (ODER).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lessonrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('school_technique', 'School + Technique'), ('school_specialisation', 'School + Specialisation'), ('magic_school_level', 'Magic School'), ('clerical_magic_level', 'Clerical Magic'), ('druid_circle_level', 'Druid Circle'), ('specific_creature', 'Creature'), ('school_level', 'School Level'), ('skill_level', 'Skill Level'), ('lesson', 'Lesson'), ('aspect_level', 'Aspect Level'), ('trait_level', 'Trait Level')], max_length=24),
        ),
        migrations.AddField(
            model_name='traitspecificationoption',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_options', to='charsheet.trait'),
        ),
        migrations.AddField(
            model_name='charactertrait',
            name='specification_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='character_traits', to='charsheet.traitspecificationoption'),
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='required_trait_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requirements', to='charsheet.traitspecificationoption'),
        ),
        migrations.AddConstraint(
            model_name='lessonrequirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requirement_type', 'school_technique'), ('required_school__isnull', False), ('required_technique__isnull', False), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', True)), models.Q(('requirement_type', 'school_specialisation'), ('required_school__isnull', False), ('required_technique__isnull', True), ('specialisation__isnull', False), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', True)), models.Q(('requirement_type', 'magic_school_level'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', False), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', False), ('minimum_value__gte', 1)), models.Q(('requirement_type', 'clerical_magic_level'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', False), ('minimum_value__gte', 1)), models.Q(('requirement_type', 'druid_circle_level'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', False), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', False), ('minimum_value__gte', 1)), models.Q(('requirement_type', 'specific_creature'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', False), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', True)), models.Q(('requirement_type', 'school_level'), ('required_school__isnull', False), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', False), ('minimum_value__gte', 1)), models.Q(('requirement_type', 'skill_level'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', False), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', False), ('minimum_value__gte', 1)), models.Q(('requirement_type', 'lesson'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', False), ('aspect__isnull', True), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', True)), models.Q(('requirement_type', 'aspect_level'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', False), ('required_trait__isnull', True), ('required_trait_specification__isnull', True), ('minimum_value__isnull', False), ('minimum_value__gte', 1)), models.Q(('requirement_type', 'trait_level'), ('required_school__isnull', True), ('required_technique__isnull', True), ('specialisation__isnull', True), ('magic_school__isnull', True), ('druid_circle__isnull', True), ('creature__isnull', True), ('required_skill__isnull', True), ('required_lesson__isnull', True), ('aspect__isnull', True), ('required_trait__isnull', False), ('minimum_value__isnull', False), ('minimum_value__gte', 1)), _connector='OR'), name='lesson_requirement_valid_fields'),
        ),
        migrations.AddConstraint(
            model_name='lessonrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('requirement_group__gte', 1)), name='lesson_requirement_group_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='lessonrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('required_lesson__isnull', True), models.Q(('lesson', models.F('required_lesson')), _negated=True), _connector='OR'), name='lesson_requirement_no_self_reference'),
        ),
        migrations.AddConstraint(
            model_name='traitspecificationoption',
            constraint=models.UniqueConstraint(fields=('trait', 'normalized_name'), name='uniq_trait_specification_option_normalized'),
        ),
    ]
