# Generated by Django 6.0.5 on 2026-09-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0392_spell_divine_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(
                    choices=[
                        ('update', 'Update'),
                        ('warning', 'Warnung'),
                        ('critical', 'Kritisch'),
                    ], max_length=8,
                )),
                ('text', models.TextField(max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
