# Generated by Django 5.2.11 on 2026-09-20 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0397_move_kraftbestie_flag_to_character_creature'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercreature',
            name='current_swarm_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aktuelle Schwarmgroesse'),
        ),
        migrations.AddField(
            model_name='charactercreature',
            name='swarm_mode',
            field=models.CharField(blank=True, choices=[('individual', 'Einzeltier'), ('swarm', 'Schwarm')], default='', help_text='Leer verwendet die Standarddarstellung des Schwarmprofils.', max_length=12, verbose_name='Schwarmdarstellung'),
        ),
        migrations.AddField(
            model_name='creature',
            name='is_swarm_creature',
            field=models.BooleanField(default=False, help_text='Kennzeichnet eine Kreatur ausdruecklich als schwarmfaehig.', verbose_name='Ist Schwarmkreatur'),
        ),
        migrations.CreateModel(
            name='CreatureSwarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_mode_available', models.BooleanField(default=True, verbose_name='Einzeltier verfuegbar')),
                ('swarm_mode_available', models.BooleanField(default=True, verbose_name='Schwarm verfuegbar')),
                ('default_display_mode', models.CharField(choices=[('individual', 'Einzeltier'), ('swarm', 'Schwarm')], default='swarm', max_length=12, verbose_name='Standarddarstellung')),
                ('individual_size_class', models.CharField(blank=True, choices=[('S', 'S'), ('F', 'F'), ('W', 'W'), ('K', 'K'), ('M', 'M'), ('G', 'G'), ('R', 'R'), ('Gi', 'Gi'), ('Kol', 'Kol')], default='', max_length=5, verbose_name='Einzeltier-GK')),
                ('swarm_size_class', models.CharField(blank=True, choices=[('S', 'S'), ('F', 'F'), ('W', 'W'), ('K', 'K'), ('M', 'M'), ('G', 'G'), ('R', 'R'), ('Gi', 'Gi'), ('Kol', 'Kol')], default='', max_length=5, verbose_name='Schwarm-GK')),
                ('individual_life_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Einzeltier-LP')),
                ('individual_wound_thresholds', models.CharField(blank=True, default='', max_length=100, verbose_name='Einzeltier-Wundschwellen')),
                ('swarm_life_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Schwarm-LP')),
                ('swarm_wound_thresholds', models.CharField(blank=True, default='', max_length=100, verbose_name='Schwarm-Wundschwellen')),
                ('min_swarm_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimale Schwarmgroesse')),
                ('max_swarm_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximale Schwarmgroesse')),
                ('individual_overrides', models.JSONField(blank=True, default=dict, help_text='Nur abweichende Basisfelder als JSON-Objekt eintragen.', verbose_name='Weitere Einzeltier-Overrides')),
                ('swarm_overrides', models.JSONField(blank=True, default=dict, help_text='Nur abweichende Basisfelder als JSON-Objekt eintragen.', verbose_name='Weitere Schwarm-Overrides')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Schwarm-Notes')),
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swarm_profile', to='charsheet.creature')),
            ],
            options={
                'verbose_name': 'Schwarmprofil',
                'verbose_name_plural': 'Schwarmprofile',
            },
        ),
        migrations.CreateModel(
            name='CreatureSwarmCountEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('target_key', models.SlugField(help_text='Semantisches Ziel, z. B. poison-strength oder poison-damage.', max_length=80)),
                ('interval', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('value_per_interval', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_effects', to='charsheet.creatureswarmprofile')),
            ],
            options={
                'ordering': ['order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreatureSwarmAttackOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_override', models.CharField(blank=True, default='', max_length=100)),
                ('attack_value_override', models.IntegerField(blank=True, null=True)),
                ('damage_dice_amount_override', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_dice_faces_override', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_flat_operator_override', models.CharField(blank=True, choices=[('', 'Kein Operator'), ('+', '+'), ('-', '-'), ('/', '/')], default=None, max_length=1, null=True)),
                ('damage_flat_bonus_override', models.IntegerField(blank=True, null=True)),
                ('damage_type_override', models.CharField(blank=True, choices=[('B', 'B'), ('T', 'T')], default=None, max_length=1, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('base_attack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swarm_override', to='charsheet.creatureattack')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_overrides', to='charsheet.creatureswarmprofile')),
            ],
            options={
                'ordering': ['base_attack__order', 'base_attack__name'],
            },
        ),
    ]
