# Generated by Django 6.0.5 on 2026-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0398_charactercreature_current_swarm_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercreature',
            name='swarm_image_override',
            field=models.ImageField(blank=True, null=True, upload_to='character_creatures/swarms/', verbose_name='Eigenes Schwarmbild'),
        ),
        migrations.AddField(
            model_name='creatureswarmprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Alternatives Vorlagenbild, das in der Schwarmdarstellung verwendet wird.', null=True, upload_to='creatures/swarms/', verbose_name='Schwarmbild'),
        ),
    ]
