# Generated by Django 6.0.5 on 2026-09-20 18:53

import django.db.models.deletion
from django.db import migrations, models


def migrate_country_names(apps, schema_editor):
    Character = apps.get_model('charsheet', 'Character')
    Country = apps.get_model('charsheet', 'Country')
    for character in Character.objects.exclude(
        legacy_country_of_origin__isnull=True
    ).exclude(legacy_country_of_origin=''):
        name = ' '.join(character.legacy_country_of_origin.split())
        if not name:
            continue
        country, _created = Country.objects.get_or_create(name=name)
        character.country_of_origin = country
        character.save(update_fields=['country_of_origin'])


def restore_country_names(apps, schema_editor):
    Character = apps.get_model('charsheet', 'Character')
    for character in Character.objects.select_related('country_of_origin'):
        country = character.country_of_origin
        character.legacy_country_of_origin = country.name if country else None
        character.save(update_fields=['legacy_country_of_origin'])


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0401_item_base_values_are_size_adjusted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                (
                    'default_native_language',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='default_for_countries',
                        to='charsheet.language',
                    ),
                ),
                (
                    'spoken_languages',
                    models.ManyToManyField(
                        blank=True,
                        related_name='countries',
                        to='charsheet.language',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='character',
            old_name='country_of_origin',
            new_name='legacy_country_of_origin',
        ),
        migrations.AddField(
            model_name='character',
            name='country_of_origin',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='characters',
                to='charsheet.country',
            ),
        ),
        migrations.RunPython(migrate_country_names, restore_country_names),
        migrations.RemoveField(
            model_name='character',
            name='legacy_country_of_origin',
        ),
    ]
