# Generated by Django 6.0.5 on 2026-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0408_repair_email_verification_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('key_digest', models.CharField(max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'updated_at'], name='auth_thr_category_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'key_digest'), name='unique_authentication_throttle_bucket')],
            },
        ),
    ]
