# Generated by Django 6.0.5 on 2026-09-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0409_authentication_throttle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_succeeded", "Successful login"),
                            ("login_failed", "Failed login attempt"),
                            ("password_changed", "Password changed"),
                            ("password_reset", "Password reset completed"),
                            ("email_changed", "Email address changed"),
                            (
                                "email_verified",
                                "Email verification completed",
                            ),
                            ("two_factor_enabled", "2FA enabled"),
                            ("two_factor_disabled", "2FA disabled"),
                            (
                                "recovery_codes_regenerated",
                                "Recovery codes regenerated",
                            ),
                            ("passkey_added", "Passkey added"),
                            ("passkey_removed", "Passkey removed"),
                            (
                                "other_sessions_logged_out",
                                "Other sessions logged out",
                            ),
                            ("session_terminated", "Session terminated"),
                            (
                                "account_deactivated",
                                "Account deactivated",
                            ),
                            (
                                "account_reactivated",
                                "Account reactivated",
                            ),
                            (
                                "deletion_requested",
                                "Permanent deletion requested",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("device", models.CharField(blank=True, max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": [
                    (
                        "inspect_accountsecurityevent",
                        "Can inspect account security activity",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="acct_sec_user_created_idx",
                    )
                ],
            },
        ),
    ]
