# Generated by Django 6.0.5 on 2026-10-01 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

EFFECT_MODELS = (
    "CharacterItemSemanticEffect",
    "CreatureSpecialSkillSemanticEffect",
    "CreatureTraitSemanticEffect",
    "DaemonicPowerSemanticEffect",
    "ItemSemanticEffect",
    "RaceSemanticEffect",
    "RuneSemanticEffect",
    "SchoolSemanticEffect",
    "SpecializationSemanticEffect",
    "TechniqueSemanticEffect",
    "TraitSemanticEffect",
    "VampireTraitSemanticEffect",
)


def migrate_rounding(apps, schema_editor):
    for name in EFFECT_MODELS:
        model = apps.get_model("charsheet", name)
        for effect in model.objects.using(
            schema_editor.connection.alias
        ).iterator():
            scaling = dict(effect.scaling or {})
            legacy = scaling.pop("round_mode", None)
            effect.round_up = legacy == "ceil"
            effect.round_down = legacy == "floor"
            effect.scaling = scaling
            effect.save(update_fields=["round_up", "round_down", "scaling"])


def restore_rounding(apps, schema_editor):
    for name in EFFECT_MODELS:
        model = apps.get_model("charsheet", name)
        for effect in model.objects.using(
            schema_editor.connection.alias
        ).iterator():
            scaling = dict(effect.scaling or {})
            if effect.round_up:
                scaling["round_mode"] = "ceil"
            elif effect.round_down:
                scaling["round_mode"] = "floor"
            effect.scaling = scaling
            effect.save(update_fields=["scaling"])


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0413_gamegroupcreature_kraftbestie_and_name"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSpecializationChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_item_category",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "selected_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "selected_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": [
                    "character_specialization",
                    "definition__sort_order",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecializationChoiceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("skill", "Skill"),
                            ("skill_category", "Skill Category"),
                            ("item", "Item"),
                            ("item_category", "Item Category"),
                            ("specialization", "Specialization"),
                            ("text", "Free Text"),
                            ("entity", "Other Entity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_choices", models.PositiveSmallIntegerField(default=1)),
                (
                    "max_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "allowed_skill_family",
                    models.SlugField(blank=True, default=""),
                ),
                ("unique_per_character", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["specialization", "sort_order", "name", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="characterspecialization",
            name="uniq_character_specialization",
        ),
        migrations.AddField(
            model_name="characteritemsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="characteritemsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="creaturespecialskillsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="creaturespecialskillsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="creaturetraitsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="creaturetraitsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="daemonicpowersemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="daemonicpowersemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="itemsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="itemsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="racesemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="racesemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="runesemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="runesemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="schoolsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="schoolsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="specialization",
            name="allow_multiple",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="specializationsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="specializationsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="techniquesemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="techniquesemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="traitsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="traitsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="vampiretraitsemanticeffect",
            name="round_down",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Standard: mathematisch runden – "
                    "ab einschließlich 0,5 aufrunden."
                ),
                verbose_name="Abrunden",
            ),
        ),
        migrations.AddField(
            model_name="vampiretraitsemanticeffect",
            name="round_up",
            field=models.BooleanField(default=False, verbose_name="Aufrunden"),
        ),
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="character_specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="charsheet.characterspecialization",
            ),
        ),
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="selected_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="selected_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="charsheet.item",
            ),
        ),
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="selected_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="charsheet.skill",
            ),
        ),
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="selected_skill_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="charsheet.skillcategory",
            ),
        ),
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="selected_specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="charsheet.specialization",
            ),
        ),
        migrations.AddField(
            model_name="specializationchoicedefinition",
            name="allowed_skill_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specialization_choice_definitions",
                to="charsheet.skillcategory",
            ),
        ),
        migrations.AddField(
            model_name="specializationchoicedefinition",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choice_definitions",
                to="charsheet.specialization",
            ),
        ),
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_choices",
                to="charsheet.specializationchoicedefinition",
            ),
        ),
        migrations.AddField(
            model_name="specializationsemanticeffect",
            name="target_choice_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semantic_effects",
                to="charsheet.specializationchoicedefinition",
            ),
        ),
        migrations.RunPython(migrate_rounding, restore_rounding),
    ]
