# Generated by Django 6.0.5 on 2026-10-01 19:15

import django.db.models.deletion
from django.db import migrations, models


def link_existing_choices(apps, schema_editor):
    Choice = apps.get_model("charsheet", "CharacterTechniqueChoice")
    Instance = apps.get_model("charsheet", "CharacterSpecialization")
    database = schema_editor.connection.alias
    choices = Choice.objects.using(database).filter(
        selected_specialization__isnull=False,
        specialization_instance__isnull=True,
    ).order_by("pk")
    for choice in choices.iterator():
        instances = Instance.objects.using(database).filter(
            character_id=choice.character_id,
            specialization_id=choice.selected_specialization_id,
            source_choice__isnull=True,
            source_technique_id=choice.technique_id,
        )
        instance = instances.first()
        if instance is None:
            Instance.objects.using(database).create(
                character_id=choice.character_id,
                specialization_id=choice.selected_specialization_id,
                source_technique_id=choice.technique_id,
                source_choice_id=choice.pk,
            )
        else:
            instance.source_choice_id = choice.pk
            instance.save(using=database, update_fields=["source_choice"])


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0414_specialization_choices_and_semantic_rounding"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="charactertechniquechoice",
            name="uniq_character_technique_selected_specialization",
        ),
        migrations.AddField(
            model_name="characterspecialization",
            name="source_choice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialization_instance",
                to="charsheet.charactertechniquechoice",
            ),
        ),
        migrations.RunPython(
            link_existing_choices, migrations.RunPython.noop,
        ),
    ]
