# Generated by Django 6.0.5 on 2026-10-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0415_link_technique_specialization_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterspecializationchoice",
            name="selected_character_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialization_choices",
                to="charsheet.characterskill",
            ),
        ),
    ]
