# Generated by Django 6.0.5 on 2026-10-04 10:36

import django.db.models.deletion
from django.db import migrations, models


def configure_compendium(apps, schema_editor):
    Technique = apps.get_model("charsheet", "Technique")
    Rule = apps.get_model("charsheet", "ProgressionRule")
    Skill = apps.get_model("charsheet", "Skill")
    Race = apps.get_model("charsheet", "Race")
    Effect = apps.get_model("charsheet", "TechniqueSemanticEffect")
    database = schema_editor.connection.alias
    definitions = (
        ({"dämonenjäger", "demon hunter"}, {"erzfeind", "nemesis"}, "text"),
        (
            {"barde", "bard", "bardenschule"},
            {"musisches talent", "musikalisches talent", "musical talent"},
            "skill",
        ),
        (
            {"nachtgeist", "nightghost"},
            {"kopfjäger", "kopfgeldjäger", "bounty hunter"},
            "race",
        ),
    )
    for school_names, technique_names, kind in definitions:
        grouped = {}
        for technique in (
            Technique.objects.using(database)
            .select_related(
                "school__type",
            )
            .filter(school__type__slug__in=["combat", "school_combat"])
        ):
            if (
                technique.school.name.casefold() in school_names
                and technique.name.casefold() in technique_names
            ):
                grouped.setdefault(technique.school_id, []).append(technique)
        for techniques in grouped.values():
            techniques.sort(key=lambda entry: (entry.level, entry.pk))
            technique = techniques[0]
            effects = list(
                Effect.objects.using(database)
                .filter(
                    technique=technique,
                    active_flag=True,
                    operator="flat_add",
                    target_domain="skill" if kind == "skill" else "combat",
                )
                .values_list("pk", flat=True)
            )
            if not effects:
                continue
            options = []
            if kind == "skill":
                for skill in Skill.objects.using(database).exclude(
                    category__slug="skill_combat",
                ):
                    if skill.family == "family_art" or skill.name in {
                        "Rhetorik",
                        "Turnen",
                        "Schauspielern",
                        "Singen",
                        "Musizieren",
                    }:
                        options.append(
                            {
                                "target": f"skill:{skill.pk}",
                                "label": skill.name,
                                "skill_id": skill.pk,
                            }
                        )
            elif kind == "race":
                allowed = {
                    "sidhe",
                    "morai",
                    "arborim",
                    "orks",
                    "ork",
                    "drakodrim",
                    "trolle",
                    "troll",
                    "menschen",
                    "mensch",
                    "halblinge",
                    "halbling",
                    "echsenmenschen",
                    "echsenmensch",
                }
                for race in Race.objects.using(database).all():
                    if race.name.casefold() in allowed:
                        options.append(
                            {
                                "target": "text:" + race.name.casefold(),
                                "label": race.name,
                            }
                        )
            Rule.objects.using(database).get_or_create(
                school_type_id=technique.school.type_id,
                grant_kind="advanced_bonus",
                min_level=10,
                params__technique_id=technique.pk,
                defaults={
                    "params": {
                        "technique_id": technique.pk,
                        "source_technique_ids": [
                            entry.pk for entry in techniques
                        ],
                        "effect_ids": effects,
                        "ep_cost": 10,
                        "increment": 1,
                        "initial_value": 1,
                        "maximum": 10,
                        "allow_new": True,
                        "allow_free_text": kind == "text",
                        "options": options,
                    }
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0418_additional_creature_choice_bindings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressionrule",
            name="grant_kind",
            field=models.CharField(
                choices=[
                    ("technique_choice", "Technique Choice"),
                    ("spell_choice", "Spell Choice"),
                    ("aspect_access", "Aspect Access"),
                    ("aspect_spell", "Aspect Spell"),
                    (
                        "advanced_simple",
                        "Zusätzliche einfache Spezialisierung",
                    ),
                    ("advanced_bonus", "Bonus-Spezialisierung steigern"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CharacterAdvancedBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("value", models.PositiveSmallIntegerField()),
                ("base_value", models.PositiveSmallIntegerField(default=0)),
                ("purchases", models.JSONField(default=list)),
                ("configuration", models.JSONField(default=dict)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced_bonuses",
                        to="charsheet.character",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="charsheet.technique",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "technique", "target"),
                        name="uniq_character_advanced_bonus_target",
                    )
                ],
            },
        ),
        migrations.RunPython(configure_compendium, migrations.RunPython.noop),
    ]
