# Generated by Django 6.0.5 on 2026-10-04 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0419_advanced_bonus_specializations"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterweaponmastery",
            name="purchased_steps",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="characterweaponmasteryarcana",
            name="paid_ep",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="characterweaponmastery",
            name="pick_order",
            field=models.PositiveSmallIntegerField(
                help_text=(
                    "The order in which this concrete weapon was chosen "
                    "on school levels 1-10."
                ),
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
