# Generated by Django 6.0.5 on 2026-10-04 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0420_advanced_weapon_mastery"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpath",
            name="additional_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolpath",
            name="additional_progression",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolpath",
            name="arcane_power_increase",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="schoolpath",
            name="completion_purchase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolpath",
            name="ep_cost",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="schoolpath",
            name="required_school_level",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.CreateModel(
            name="CareerPathTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "effective_level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_steps",
                        to="charsheet.schoolpath",
                    ),
                ),
                (
                    "technique",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="career_step",
                        to="charsheet.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "order"],
            },
        ),
        migrations.CreateModel(
            name="CharacterCareerPathPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_ep", models.PositiveSmallIntegerField(default=20)),
                (
                    "arcane_power_increase",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_path_purchases",
                        to="charsheet.character",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="charsheet.schoolpath",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="charsheet.careerpathtechnique",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="careerpathtechnique",
            constraint=models.UniqueConstraint(
                fields=("path", "order"), name="uniq_career_step_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="careerpathtechnique",
            constraint=models.CheckConstraint(
                condition=models.Q(("effective_level__lte", 10)),
                name="career_level_at_most_ten",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactercareerpathpurchase",
            constraint=models.UniqueConstraint(
                fields=("character", "step"), name="uniq_character_career_step"
            ),
        ),
        migrations.AddConstraint(
            model_name="charactercareerpathpurchase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("step__isnull", True)),
                fields=("character", "path"),
                name="uniq_character_career_completion",
            ),
        ),
    ]
