# Generated by Django 6.0.5 on 2026-10-04 14:40

from django.db import migrations, models


def transfer_manual_fame(apps, schema_editor):
    Character = apps.get_model("charsheet", "Character")
    for character in Character.objects.all().iterator():
        character.reputation_personal_points = (
            character.personal_fame_rank * 10 + character.personal_fame_point
        )
        character.save(update_fields=["reputation_personal_points"])


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0423_kriegshund_two_weapon_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="reputation_artefact_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="reputation_group_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="reputation_personal_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(transfer_manual_fame, migrations.RunPython.noop),
    ]
