# Generated by Django 6.0.5 on 2026-10-04 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0425_artefact_rank_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="personal_fame_rank_cost",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Persönliche Ruhmränge",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncost",
            name="cost_type",
            field=models.CharField(
                choices=[
                    ("kp", "KP"),
                    ("lp", "LP"),
                    ("ep", "EP"),
                    ("fame", "Ruhmpunkt"),
                    ("personal_fame_rank", "Persönlicher Ruhmrang"),
                    ("custom", "Frei definiert"),
                ],
                max_length=20,
            ),
        ),
    ]
