# Generated by Django 6.0.5 on 2026-10-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0426_personal_fame_rank_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="artefact_rank",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Der aktive Artefaktrang entsteht ausschließlich durch SemanticEffects.",
                verbose_name="Dauerhaft in Artefakte investierte Ruhmränge",
            ),
        ),
    ]
