# Generated by Django 6.0.5 on 2026-10-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0430_remove_redundant_entity_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="max_level",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Leave empty for an unbounded maximum level.",
                null=True,
            ),
        ),
    ]
