# Generated by Django 6.0.5 on 2026-10-05 19:47

import django.db.models.deletion
from django.db import migrations, models

# Stable legacy identities; these definitions are migration data only.
LEGACY_TYPES = [
    ("weapon", "Waffe", "Waffen"),
    ("armor", "R\u00fcstung", "R\u00fcstungen"),
    ("shield", "Schild", "Schilde"),
    ("clothing", "Kleidung", "Kleidung"),
    ("ring", "Ring", "Ringe"),
    ("amulet", "Amulett", "Amulette"),
    ("magical_weapon", "Magische Waffe", "Magische Waffen"),
    ("magical_armor", "Magisches R\u00fcstzeug", "Magische R\u00fcstungen"),
    ("ammo", "Monition", "Munition"),
    ("consumable", "Verbrauchsgegenstand", "Verbrauchsgegenst\u00e4nde"),
    (
        "alchemical_brew",
        "Alchemistische Gebr\u00e4ue",
        "Alchemistische Gebr\u00e4ue",
    ),
    ("creature", "Tiere & Kreaturen", "Tiere & Kreaturen"),
    ("equipment", "Ausr\u00fcstung", "Ausr\u00fcstung"),
    ("misc", "Sonstiges", "Sonstiges"),
]
FORM_ORDER = [
    "misc",
    "creature",
    "consumable",
    "ammo",
    "weapon",
    "armor",
    "shield",
    "clothing",
    "ring",
    "amulet",
    "magical_weapon",
    "magical_armor",
    "alchemical_brew",
    "equipment",
]


def seed_item_types(apps, schema_editor):
    ItemType = apps.get_model("charsheet", "ItemType")
    Item = apps.get_model("charsheet", "Item")
    alias = schema_editor.connection.alias
    known = {slug for slug, _, _ in LEGACY_TYPES}
    existing = set(
        Item.objects.using(alias).values_list("item_type", flat=True)
    )
    unknown = existing - known
    if unknown:
        raise ValueError(f"Unknown legacy item types: {sorted(unknown)!r}")
    for order, (slug, name, plural) in enumerate(LEGACY_TYPES):
        weapon = slug in {"weapon", "magical_weapon"}
        armor = slug in {"armor", "magical_armor"}
        shield = slug == "shield"
        clothing = slug == "clothing"
        magic = slug in {"ring", "amulet", "magical_weapon", "magical_armor"}
        equipped = weapon or armor or shield or clothing or magic
        ItemType.objects.using(alias).create(
            slug=slug,
            name=name,
            plural_name=plural,
            sort_order=order,
            form_sort_order=FORM_ORDER.index(slug),
            is_weapon=weapon,
            is_armor=armor,
            is_shield=shield,
            is_clothing=clothing,
            is_magic_equipment=magic,
            forces_magic=slug in {"magical_weapon", "magical_armor"},
            supports_weapon_stats=weapon,
            supports_weapon_mastery=slug == "weapon",
            supports_armor_stats=armor or slug in {"ring", "amulet"},
            supports_shield_stats=shield or slug == "magical_armor",
            supports_alchemical_stats=slug == "alchemical_brew",
            is_consumable=slug in {"consumable", "alchemical_brew"},
            is_ammunition=slug == "ammo",
            is_creature=slug == "creature",
            is_equippable=equipped,
            forbids_stacking=equipped,
            excludes_equipped_carry_weight=armor or shield or clothing,
            shows_quality=equipped,
            icon_key=slug if slug in {"ring", "amulet"} else "",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0432_organizations_and_trait_entity_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "form_sort_order",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("plural_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_weapon", models.BooleanField(default=False)),
                ("is_armor", models.BooleanField(default=False)),
                ("is_shield", models.BooleanField(default=False)),
                ("is_clothing", models.BooleanField(default=False)),
                ("is_magic_equipment", models.BooleanField(default=False)),
                ("forces_magic", models.BooleanField(default=False)),
                ("supports_weapon_stats", models.BooleanField(default=False)),
                (
                    "supports_weapon_mastery",
                    models.BooleanField(default=False),
                ),
                ("supports_armor_stats", models.BooleanField(default=False)),
                ("supports_shield_stats", models.BooleanField(default=False)),
                (
                    "supports_alchemical_stats",
                    models.BooleanField(default=False),
                ),
                ("is_consumable", models.BooleanField(default=False)),
                ("is_ammunition", models.BooleanField(default=False)),
                ("is_creature", models.BooleanField(default=False)),
                ("is_equippable", models.BooleanField(default=False)),
                ("forbids_stacking", models.BooleanField(default=False)),
                (
                    "excludes_equipped_carry_weight",
                    models.BooleanField(default=False),
                ),
                ("shows_quality", models.BooleanField(default=False)),
                ("icon_key", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["sort_order", "name", "slug"],
            },
        ),
        migrations.RunPython(seed_item_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.ForeignKey(
                db_column="item_type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="charsheet.itemtype",
            ),
        ),
    ]
