# Generated by Django 6.0.5 on 2026-10-05 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_race_grants(apps, schema_editor):
    alias = schema_editor.connection.alias
    OldGrant = apps.get_model("charsheet", "RaceStartingItem")
    Grant = apps.get_model("charsheet", "StartingItemGrant")
    Receipt = apps.get_model("charsheet", "CharacterStartingItemGrant")
    Inventory = apps.get_model("charsheet", "CharacterItem")
    for old in OldGrant.objects.using(alias).all().iterator():
        grant = Grant.objects.using(alias).create(
            race_id=old.race_id, item_id=old.item_id, amount=old.amount,
            quality_id=old.quality_id, equipped=True, equip_locked=True,
        )
        # The old creation engine always equipped and locked race equipment.
        # Register already materialized items without altering inventory.
        for entry in Inventory.objects.using(alias).filter(
            owner__race_id=old.race_id, item_id=old.item_id,
            equip_locked=True,
        ).order_by("pk"):
            Receipt.objects.using(alias).get_or_create(
                character_id=entry.owner_id, grant_id=grant.pk,
                defaults={"character_item_id": entry.pk},
            )


def restore_race_grants(apps, schema_editor):
    alias = schema_editor.connection.alias
    OldGrant = apps.get_model("charsheet", "RaceStartingItem")
    Grant = apps.get_model("charsheet", "StartingItemGrant")
    for grant in Grant.objects.using(alias).filter(race__isnull=False):
        OldGrant.objects.using(alias).create(
            race_id=grant.race_id, item_id=grant.item_id,
            amount=grant.amount, quality_id=grant.quality_id,
            equipped=grant.equipped,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0433_database_item_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterStartingItemGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StartingItemGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("equipped", models.BooleanField(default=False)),
                ("equip_locked", models.BooleanField(default=False)),
                ("stored", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="racestartingitem",
            name="uniq_race_starting_item",
        ),
        migrations.AddField(
            model_name="characterstartingitemgrant",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="charsheet.character",
            ),
        ),
        migrations.AddField(
            model_name="characterstartingitemgrant",
            name="character_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="charsheet.characteritem",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="divine_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_items",
                to="charsheet.divineentity",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="druid_cult",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_items",
                to="charsheet.druidcult",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_item_grants",
                to="charsheet.item",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                db_column="quality",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="starting_item_grants",
                to="charsheet.quality",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_items",
                to="charsheet.race",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_items",
                to="charsheet.school",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="shaman_patron",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_items",
                to="charsheet.shamanpatron",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="technique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_items",
                to="charsheet.technique",
            ),
        ),
        migrations.AddField(
            model_name="startingitemgrant",
            name="trait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_items",
                to="charsheet.trait",
            ),
        ),
        migrations.AddField(
            model_name="characterstartingitemgrant",
            name="grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="charsheet.startingitemgrant",
            ),
        ),
        migrations.RunPython(migrate_race_grants, restore_race_grants),
        migrations.RemoveField(
            model_name="racestartingitem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="racestartingitem",
            name="quality",
        ),
        migrations.RemoveField(
            model_name="racestartingitem",
            name="race",
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("divine_entity__isnull", True),
                        ("druid_cult__isnull", True),
                        ("race__isnull", False),
                        ("school__isnull", True),
                        ("shaman_patron__isnull", True),
                        ("technique__isnull", True),
                        ("trait__isnull", True),
                    ),
                    models.Q(
                        ("divine_entity__isnull", True),
                        ("druid_cult__isnull", True),
                        ("race__isnull", True),
                        ("school__isnull", False),
                        ("shaman_patron__isnull", True),
                        ("technique__isnull", True),
                        ("trait__isnull", True),
                    ),
                    models.Q(
                        ("divine_entity__isnull", True),
                        ("druid_cult__isnull", True),
                        ("race__isnull", True),
                        ("school__isnull", True),
                        ("shaman_patron__isnull", True),
                        ("technique__isnull", False),
                        ("trait__isnull", True),
                    ),
                    models.Q(
                        ("divine_entity__isnull", True),
                        ("druid_cult__isnull", True),
                        ("race__isnull", True),
                        ("school__isnull", True),
                        ("shaman_patron__isnull", True),
                        ("technique__isnull", True),
                        ("trait__isnull", False),
                    ),
                    models.Q(
                        ("divine_entity__isnull", False),
                        ("druid_cult__isnull", True),
                        ("race__isnull", True),
                        ("school__isnull", True),
                        ("shaman_patron__isnull", True),
                        ("technique__isnull", True),
                        ("trait__isnull", True),
                    ),
                    models.Q(
                        ("divine_entity__isnull", True),
                        ("druid_cult__isnull", True),
                        ("race__isnull", True),
                        ("school__isnull", True),
                        ("shaman_patron__isnull", False),
                        ("technique__isnull", True),
                        ("trait__isnull", True),
                    ),
                    models.Q(
                        ("divine_entity__isnull", True),
                        ("druid_cult__isnull", False),
                        ("race__isnull", True),
                        ("school__isnull", True),
                        ("shaman_patron__isnull", True),
                        ("technique__isnull", True),
                        ("trait__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="starting_item_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 1)),
                name="starting_item_positive_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("race", "item"), name="uniq_race_starting_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("school", "item"), name="uniq_school_starting_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("technique", "item"),
                name="uniq_technique_starting_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("trait", "item"), name="uniq_trait_starting_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("divine_entity", "item"),
                name="uniq_divine_entity_starting_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("shaman_patron", "item"),
                name="uniq_shaman_patron_starting_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="startingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("druid_cult", "item"),
                name="uniq_druid_cult_starting_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterstartingitemgrant",
            constraint=models.UniqueConstraint(
                fields=("character", "grant"),
                name="unique_character_starting_grant",
            ),
        ),
        migrations.DeleteModel(
            name="RaceStartingItem",
        ),
    ]
