# Generated by Django 6.0.5 on 2026-10-05 20:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charsheet",
            "0434_characterstartingitemgrant_startingitemgrant_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumableEffectStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heal_lp", models.PositiveSmallIntegerField(default=0)),
                (
                    "heal_lp_dice_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "heal_lp_dice_faces",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "heal_lp_modifier",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "heal_lp_divisor",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("restore_kp", models.PositiveSmallIntegerField(default=0)),
                (
                    "restore_kp_dice_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "restore_kp_dice_faces",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "restore_kp_modifier",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "restore_kp_divisor",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "heal_wound_grades",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charsheet.item",
                    ),
                ),
            ],
        ),
    ]
