# Generated by Django 6.0.5 on 2026-10-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0436_character_creation_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboardannouncement",
            options={"ordering": ["sort_order", "-created_at", "-pk"]},
        ),
        migrations.AddField(
            model_name="dashboardannouncement",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
