# Generated by Django 6.0.5 on 2026-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0437_dashboard_announcement_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteritem",
            name="structure_damage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="hardness",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="structure_points",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
