# Generated by Django 6.0.5 on 2026-10-06 11:41

from django.db import migrations, models


def configure_drakonium(apps, schema_editor):
    Metal = apps.get_model("charsheet", "Metal")
    Metal.objects.using(schema_editor.connection.alias).filter(
        slug="drakonium",
    ).update(
        hardness_override=40, quality_overwrite=None,
        apply_quality_effects=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0438_item_structure_damage"),
    ]

    operations = [
        migrations.AddField(
            model_name="metal",
            name="hardness_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            configure_drakonium, migrations.RunPython.noop,
        ),
    ]
