# Generated by Django 6.0.5 on 2026-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0440_divine_entity_semantic_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="allowed_divine_entity_types",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Schränkt die Wahl unter den dieser Schule "
                    "zugeordneten Wesen ein. Leer lassen, "
                    "um alle Typen zu erlauben."
                ),
                related_name="restricted_schools",
                to="charsheet.divineentitytype",
                verbose_name="Erlaubte Typen göttlicher Wesen",
            ),
        ),
    ]
