# Generated by Django 6.0.5 on 2026-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0441_divine_entity_semantic_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="divineentity",
            name="grammatical_gender",
            field=models.CharField(
                choices=[
                    ("masculine", "♂ — maskulin"),
                    ("feminine", "♀ — feminin"),
                    ("neuter", "⚲ — neutral"),
                    ("plural", "♊︎ — plural"),
                ],
                default="masculine",
                max_length=12,
                verbose_name="Grammatisches Geschlecht",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="feminine_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Leer lassen, wenn die Bezeichnung für alle gleich ist."
                ),
                max_length=100,
                verbose_name="Weibliche Bezeichnung",
            ),
        ),
    ]
