# Generated by Django 6.0.5 on 2026-10-06 17:22

from django.db import migrations, models


def seed_existing_school_types(apps, schema_editor):
    """Transfer old assignments only where no type selection exists yet."""
    School = apps.get_model("charsheet", "School")
    Entity = apps.get_model("charsheet", "DivineEntity")
    alias = schema_editor.connection.alias
    for school in School.objects.using(alias).all():
        if not school.allowed_divine_entity_types.using(alias).exists():
            type_ids = Entity.objects.using(alias).filter(
                school_id=school.pk,
            ).values_list("entity_type_id", flat=True).distinct()
            school.allowed_divine_entity_types.add(*type_ids)


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0442_divine_school_display_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="allowed_divine_entity_types",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Alle Wesen dieser Typen stehen für diese Schule "
                    "zur Wahl. "
                    "Ohne erlaubte Typen stehen keine Wesen zur Wahl."
                ),
                related_name="restricted_schools",
                to="charsheet.divineentitytype",
                verbose_name="Erlaubte Typen göttlicher Wesen",
            ),
        ),
        migrations.RunPython(
            seed_existing_school_types, migrations.RunPython.noop,
        ),
    ]
