# Generated by Django 6.0.5 on 2026-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0444_rename_metal_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="quality_modifier",
            field=models.SmallIntegerField(
                default=0,
                help_text=(
                    "Qualitätsstufen relativ zur normalen Qualität: "
                    "+1 verbessert, -1 verschlechtert. Eine feste "
                    "Qualitätsüberschreibung hat Vorrang."
                ),
                verbose_name="Qualitätsverschiebung",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="apply_quality_effects",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Wenn deaktiviert, verändert das Material die angezeigte "
                    "Qualität, ohne deren regeltechnische Qualitätsboni "
                    "anzuwenden."
                ),
            ),
        ),
    ]
