# Generated by Django 6.0.5 on 2026-10-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0446_usersettings_critical_result_texts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="radial_menu_enabled",
        ),
    ]
