# Generated by Django 6.0.5 on 2026-10-09 09:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0449_character_quickslot_layout"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "months_per_year",
                    models.PositiveIntegerField(
                        default=12,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
                (
                    "days_per_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_character_date",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CalendarLeapRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_days",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                ("offset", models.IntegerField(default=0)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leap_rules",
                        to="charsheet.calendardefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarLeapException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                ("offset", models.IntegerField(default=0)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="charsheet.calendarleaprule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "days",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="months",
                        to="charsheet.calendardefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.AddField(
            model_name="calendarleaprule",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="charsheet.calendarmonth",
            ),
        ),
        migrations.CreateModel(
            name="CalendarSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("abbreviation", models.CharField(max_length=20)),
                ("anchor_year", models.BigIntegerField(default=0)),
                ("anchor_month", models.PositiveIntegerField(default=1)),
                ("anchor_day", models.PositiveIntegerField(default=1)),
                ("reference_year", models.BigIntegerField(default=0)),
                ("reference_month", models.PositiveIntegerField(default=1)),
                ("reference_day", models.PositiveIntegerField(default=1)),
                (
                    "calendar_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="systems",
                        to="charsheet.calendardefinition",
                    ),
                ),
                (
                    "reference_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referencing_systems",
                        to="charsheet.calendarsystem",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="CharacterDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absolute_day", models.BigIntegerField()),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_date",
                        to="charsheet.character",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="charsheet.calendarsystem",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="calendarmonth",
            constraint=models.UniqueConstraint(
                fields=("calendar", "sort_order"),
                name="calendar_month_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarsystem",
            constraint=models.UniqueConstraint(
                models.Value(1),
                condition=models.Q(("reference_system__isnull", True)),
                name="single_calendar_timeline_root",
            ),
        ),
    ]
