# Generated by Django 6.0.5 on 2026-10-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0450_calendar_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Jahreszeit",
                "verbose_name_plural": "Jahreszeiten",
                "ordering": ("name", "pk"),
            },
        ),
        migrations.AddField(
            model_name="calendarmonth",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="months",
                to="charsheet.calendarseason",
                verbose_name="Jahreszeit",
            ),
        ),
    ]
