# Generated by Django 6.0.5 on 2026-10-09 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0451_calendar_seasons"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendardefinition",
            options={
                "verbose_name": "Kalenderdefinition",
                "verbose_name_plural": "Kalenderdefinitionen",
            },
        ),
        migrations.AlterModelOptions(
            name="calendarleapexception",
            options={
                "verbose_name": "Ausnahme von der Schaltjahrregel",
                "verbose_name_plural": "Ausnahmen von der Schaltjahrregel",
            },
        ),
        migrations.AlterModelOptions(
            name="calendarleaprule",
            options={
                "verbose_name": "Schaltjahrregel",
                "verbose_name_plural": "Schaltjahrregeln",
            },
        ),
        migrations.AlterModelOptions(
            name="calendarmonth",
            options={
                "ordering": ("sort_order",),
                "verbose_name": "Monat",
                "verbose_name_plural": "Monate",
            },
        ),
        migrations.AlterModelOptions(
            name="calendarsystem",
            options={
                "ordering": ("name", "pk"),
                "verbose_name": "Zeitrechnung",
                "verbose_name_plural": "Zeitrechnungen",
            },
        ),
        migrations.AddField(
            model_name="calendarleapexception",
            name="effect",
            field=models.CharField(
                choices=[
                    ("exclude", "Schalttage entfallen"),
                    ("include", "Schalttage gelten trotzdem"),
                ],
                default="exclude",
                help_text="‚Gelten trotzdem‘ hat Vorrang vor ‚entfallen‘. "
                "Beide gelten nur in Jahren der Grundregel.",
                max_length=7,
                verbose_name="Wirkung",
            ),
        ),
        migrations.AddField(
            model_name="calendarsystem",
            name="root_origin_day",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="calendardefinition",
            name="days_per_year",
            field=models.PositiveIntegerField(
                help_text="Reguläre Jahreslänge ohne zusätzliche Schalttage.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Tage pro Jahr",
            ),
        ),
        migrations.AlterField(
            model_name="calendardefinition",
            name="months_per_year",
            field=models.PositiveIntegerField(
                default=12,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Anzahl der Monate",
            ),
        ),
        migrations.AlterField(
            model_name="calendardefinition",
            name="name",
            field=models.CharField(
                max_length=120, verbose_name="Kalendername"
            ),
        ),
        migrations.AlterField(
            model_name="calendarleapexception",
            name="offset",
            field=models.IntegerField(
                default=0,
                help_text="0: Jahre 0, X, 2X …; 1: Jahre 1, X+1, 2X+1 … "
                "Optional; auch negative Werte sind erlaubt.",
                verbose_name="Versatz der Ausnahme",
            ),
        ),
        migrations.AlterField(
            model_name="calendarleapexception",
            name="period",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Wiederholung alle X Jahre",
            ),
        ),
        migrations.AlterField(
            model_name="calendarleapexception",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exceptions",
                to="charsheet.calendarleaprule",
                verbose_name="Schaltjahrregel",
            ),
        ),
        migrations.AlterField(
            model_name="calendarleaprule",
            name="added_days",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Zusätzliche Tage",
            ),
        ),
        migrations.AlterField(
            model_name="calendarleaprule",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leap_rules",
                to="charsheet.calendardefinition",
                verbose_name="Kalender",
            ),
        ),
        migrations.AlterField(
            model_name="calendarleaprule",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="charsheet.calendarmonth",
                verbose_name="Monat mit Schalttagen",
            ),
        ),
        migrations.AlterField(
            model_name="calendarleaprule",
            name="offset",
            field=models.IntegerField(
                default=0,
                help_text="0: Jahre 0, X, 2X …; 1: Jahre 1, X+1, 2X+1 … "
                "Die Regel gilt ebenso für negative Jahre.",
                verbose_name="Versatz der Schaltjahrregel",
            ),
        ),
        migrations.AlterField(
            model_name="calendarleaprule",
            name="period",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Wiederholung alle X Jahre",
            ),
        ),
        migrations.AlterField(
            model_name="calendarmonth",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="months",
                to="charsheet.calendardefinition",
                verbose_name="Kalender",
            ),
        ),
        migrations.AlterField(
            model_name="calendarmonth",
            name="days",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Anzahl der Tage",
            ),
        ),
        migrations.AlterField(
            model_name="calendarmonth",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Monatsname"),
        ),
        migrations.AlterField(
            model_name="calendarmonth",
            name="sort_order",
            field=models.PositiveIntegerField(
                help_text="Aufsteigende Position im Jahr; "
                "jede Position nur einmal.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Reihenfolge",
            ),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="abbreviation",
            field=models.CharField(
                help_text="Darf mehrfach verwendet werden.",
                max_length=20,
                verbose_name="Kürzel",
            ),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="anchor_day",
            field=models.PositiveIntegerField(default=1, verbose_name="Tag"),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="anchor_month",
            field=models.PositiveIntegerField(default=1, verbose_name="Monat"),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="anchor_year",
            field=models.BigIntegerField(default=0, verbose_name="Jahr"),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="calendar_definition",
            field=models.ForeignKey(
                help_text="Legt fest, wie viele Monate und Tage "
                "ein Jahr besitzt.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="systems",
                to="charsheet.calendardefinition",
                verbose_name="Verwendeter Kalender",
            ),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="name",
            field=models.CharField(
                max_length=120, verbose_name="Name der Zeitrechnung"
            ),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="reference_day",
            field=models.PositiveIntegerField(default=1, verbose_name="Tag"),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="reference_month",
            field=models.PositiveIntegerField(default=1, verbose_name="Monat"),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="reference_system",
            field=models.ForeignKey(
                blank=True,
                help_text="Legt fest, auf welche andere Zeitrechnung sich "
                "diese Zeitrechnung bezieht. Leer: Ausgangszeitrechnung.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referencing_systems",
                to="charsheet.calendarsystem",
                verbose_name="Bezugszeitrechnung",
            ),
        ),
        migrations.AlterField(
            model_name="calendarsystem",
            name="reference_year",
            field=models.BigIntegerField(default=0, verbose_name="Jahr"),
        ),
    ]
