# Generated by Django 6.0.5 on 2026-10-09 10:15

from django.db import migrations, models


def assign_existing_season_styles(apps, schema_editor):
    seasons = apps.get_model("charsheet", "CalendarSeason")
    for name, style in (
        ("Frühling", "spring"),
        ("Sommer", "summer"),
        ("Herbst", "autumn"),
        ("Winter", "winter"),
    ):
        seasons.objects.using(schema_editor.connection.alias).filter(
            name__iexact=name
        ).update(visual_style=style)


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0452_calendar_admin_ux"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarseason",
            name="visual_style",
            field=models.CharField(
                choices=[
                    ("neutral", "Arkanes Metall"),
                    ("spring", "Frühling – Blüten und Smaragd"),
                    ("summer", "Sommer – Gold und Glut"),
                    ("autumn", "Herbst – Kupfer und Blätter"),
                    ("winter", "Winter – Silber und Schnee"),
                ],
                default="neutral",
                help_text=(
                    "Die Monatszuordnung bestimmt, wann dieses "
                    "Erscheinungsbild auf dem Charakterbogen verwendet wird."
                ),
                max_length=7,
                verbose_name="Erscheinungsbild des Kalenders",
            ),
        ),
        migrations.AddField(
            model_name="calendarsystem",
            name="default_for_characters",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Wird bei der erstmaligen Datumsinitialisierung "
                    "verwendet. "
                    "Ohne Auswahl wird die Ausgangszeitrechnung verwendet."
                ),
                verbose_name="Standardzeitrechnung für neue Charakterdaten",
            ),
        ),
        migrations.AddField(
            model_name="calendarsystem",
            name="real_date_reference",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Nur für einen vollständig gregorianisch konfigurierten "
                    "Kalender. Ermöglicht die einmalige Übernahme des "
                    "heutigen "
                    "Datums; bestehende Charakterdaten laufen nicht "
                    "automatisch weiter."
                ),
                verbose_name=(
                    "Gregorianische Bezugszeitrechnung für das reale Datum"
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarsystem",
            constraint=models.UniqueConstraint(
                models.Value(1),
                condition=models.Q(("default_for_characters", True)),
                name="single_character_default_calendar",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarsystem",
            constraint=models.UniqueConstraint(
                models.Value(1),
                condition=models.Q(("real_date_reference", True)),
                name="single_real_date_calendar",
            ),
        ),
        migrations.RunPython(
            assign_existing_season_styles, migrations.RunPython.noop
        ),
    ]
