# Generated by Django 6.0.5 on 2026-10-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0453_magical_character_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterdiaryentry",
            name="calendar_absolute_day",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characterdiaryentry",
            name="calendar_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diary_entries",
                to="charsheet.calendarsystem",
            ),
        ),
    ]
