# Generated by Django 6.0.5 on 2026-10-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0454_diary_calendar_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarseason",
            name="falling_rain",
            field=models.BooleanField(
                default=True, verbose_name="Fallender Regen",
            ),
        ),
        migrations.AddField(
            model_name="calendarseason",
            name="rain_intensity",
            field=models.CharField(
                choices=[
                    ("none", "Kein Regen"),
                    ("drizzle", "Nieselregen"),
                    ("rain", "Regen"),
                    ("monsoon", "Monsun"),
                ],
                default="none",
                help_text="Zusätzlicher Effekt, unabhängig vom "
                "Erscheinungsbild. Wird über die Monatszuordnung "
                "mit dieser Jahreszeit aktiviert.",
                max_length=7,
                verbose_name="Regen / Monsun",
            ),
        ),
        migrations.AddField(
            model_name="calendarseason",
            name="surface_drops",
            field=models.BooleanField(
                default=True, verbose_name="Oberflächentropfen",
            ),
        ),
    ]
