# Generated by Django 6.0.5 on 2026-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0455_calendar_season_rain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarseason",
            name="rain_intensity",
            field=models.CharField(
                choices=[
                    ("none", "Kein zusätzlicher Regen"),
                    ("drizzle", "Nieselregen"),
                    ("rain", "Regen"),
                    ("monsoon", "Monsun"),
                ],
                default="none",
                help_text="Zusätzlicher Effekt, unabhängig vom "
                "Erscheinungsbild. Wird über die Monatszuordnung mit "
                "dieser Jahreszeit aktiviert. Das Erscheinungsbild "
                "Regenzeit verwendet standardmäßig Regen; hier kann "
                "dessen Intensität angepasst werden.",
                max_length=7,
                verbose_name="Regen / Monsun",
            ),
        ),
        migrations.AlterField(
            model_name="calendarseason",
            name="visual_style",
            field=models.CharField(
                choices=[
                    ("neutral", "Arkanes Metall"),
                    ("spring", "Frühling – Blüten und Smaragd"),
                    ("summer", "Sommer – Gold und Glut"),
                    ("autumn", "Herbst – Kupfer und Blätter"),
                    ("winter", "Winter – Silber und Schnee"),
                    ("rain", "Regenzeit – Regen / Monsun"),
                ],
                default="neutral",
                help_text="Die Monatszuordnung bestimmt, wann dieses "
                "Erscheinungsbild auf dem Charakterbogen verwendet wird.",
                max_length=7,
                verbose_name="Erscheinungsbild des Kalenders",
            ),
        ),
    ]
