# Generated by Django 6.0.5 on 2026-10-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0456_calendar_rain_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="mw_failure_text",
            field=models.CharField(
                blank=True,
                default="Nicht erfolgreich",
                max_length=64,
                verbose_name="Text bei nicht erreichtem MW",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="mw_success_text",
            field=models.CharField(
                blank=True,
                default="Erfolgreich",
                max_length=64,
                verbose_name="Text bei erreichtem MW",
            ),
        ),
    ]
