# Generated by Django 6.0.5 on 2026-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0457_user_settings_mw_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="special_failure_text",
            field=models.CharField(
                blank=True,
                default="Fehlschlag",
                max_length=64,
                verbose_name="Text bei Fehlschlag (1 + 3)",
            ),
        ),
    ]
