# Generated by Django 6.0.5 on 2026-10-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0458_user_settings_special_failure_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="special_failure_text",
            field=models.CharField(
                blank=True,
                default="Fehlschlag",
                max_length=64,
                verbose_name="Text bei Fehlschlag (1 + 2)",
            ),
        ),
    ]
