# Generated by Django 6.0.5 on 2026-10-09 15:17

import charsheet.calendar_layout
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charsheet", "0459_special_failure_pair"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarsystem",
            name="date_layout",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "Ohne eigenes Layout wird die bisherige Anzeige verwendet."
                ),
                null=True,
                validators=[charsheet.calendar_layout.validate_layout],
                verbose_name="Standardlayout der Datumsanzeige",
            ),
        ),
        migrations.CreateModel(
            name="UserCalendarLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        validators=[charsheet.calendar_layout.validate_layout]
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charsheet.calendarsystem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "system"),
                        name="unique_user_calendar_layout",
                    )
                ],
            },
        ),
    ]
