"""Public exports for the central modifier system."""

from .build_validation import BuildValidationIssue, CharacterBuildValidator, TraitBuildRule
from .definitions import (
    BaseModifier,
    AttributeCapModifier,
    AttributeModifier,
    CombatModifier,
    ConditionSet,
    ConditionalModifier,
    DerivedStatModifier,
    EconomyModifier,
    EntityModifier,
    ItemModifier,
    ModifierOperator,
    MovementModifier,
    PerceptionModifier,
    ResourceModifier,
    ResistanceModifier,
    RuleFlagModifier,
    SkillModifier,
    SocialModifier,
    SpecializationModifier,
    StackBehavior,
    TargetDomain,
    TraitModifier,
)
from .engine import CombatProfile, ModifierEngine, MovementProfile, ResistanceProfile, SocialProfile
from .migration import (
    LegacyModifierInventoryRow,
    LegacyModifierMigrationRecord,
    LegacyModifierMigrationService,
    LegacyModifierRelation,
    MigrationConfidence,
    MigrationStrategy,
    ModifierResolutionMode,
    NumericResolutionComparison,
)

__all__ = [
    "BaseModifier",
    "AttributeCapModifier",
    "AttributeModifier",
    "BuildValidationIssue",
    "CharacterBuildValidator",
    "CombatModifier",
    "CombatProfile",
    "ConditionSet",
    "ConditionalModifier",
    "DerivedStatModifier",
    "EconomyModifier",
    "EntityModifier",
    "ItemModifier",
    "LegacyModifierInventoryRow",
    "LegacyModifierMigrationRecord",
    "LegacyModifierMigrationService",
    "LegacyModifierRelation",
    "MigrationConfidence",
    "MigrationStrategy",
    "ModifierEngine",
    "ModifierOperator",
    "ModifierResolutionMode",
    "MovementModifier",
    "MovementProfile",
    "NumericResolutionComparison",
    "PerceptionModifier",
    "ResourceModifier",
    "ResistanceModifier",
    "ResistanceProfile",
    "RuleFlagModifier",
    "SkillModifier",
    "SocialModifier",
    "SocialProfile",
    "SpecializationModifier",
    "StackBehavior",
    "TargetDomain",
    "TraitBuildRule",
    "TraitModifier",
]
